-- Part A — Schema changes
ALTER TABLE achievement_definitions ADD COLUMN IF NOT EXISTS rarity text NOT NULL DEFAULT 'Common';
ALTER TABLE achievement_definitions ADD COLUMN IF NOT EXISTS lore text NOT NULL DEFAULT '';
ALTER TABLE achievement_definitions ADD COLUMN IF NOT EXISTS creature text NOT NULL DEFAULT '';
ALTER TABLE achievement_definitions ADD COLUMN IF NOT EXISTS category text NOT NULL DEFAULT '';

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS badge_stats jsonb NOT NULL DEFAULT '{}'::jsonb;

-- Part B — Replace achievements
DELETE FROM user_achievements;
DELETE FROM achievement_definitions;

INSERT INTO achievement_definitions (key, label, icon_emoji, description, rarity, creature, category, lore, threshold) VALUES
-- First Completion
('first_verbal', 'Baby Wordumph', '🐣💬', 'Completed your first Verbal challenge.', 'Common', 'Wordumph', 'First Completion', 'A Wordumph is a small, pompous creature that knows every word in the dictionary and will absolutely use all of them in one sentence if given the opportunity. This is the baby version. It only knows ''antonym'' so far. It is already insufferable.', 1),
('first_quantitative', 'Baby Seriesnake', '🐍🔢', 'Completed your first Quantitative challenge.', 'Common', 'Seriesnake', 'First Completion', 'A Seriesnake''s body IS a number sequence — its head is the first term and its tail predicts the next one. This baby Seriesnake only goes up to 10. It''s trying its best. Its tail keeps guessing wrong and it''s very embarrassed about it.', 1),
('first_reading', 'Baby Pageslobber', '📘🤤', 'Completed your first Reading challenge.', 'Common', 'Pageslobber', 'First Completion', 'Pageslobbers absorb knowledge by physically slobbering on books. Scientists are deeply uncomfortable with this. The Pageslobber is not. This baby has slobbered on exactly one passage. It understood the main idea. It is very proud of itself.', 1),
('first_mathematics', 'Baby Numbskull', '💀🔢', 'Completed your first Mathematics challenge.', 'Common', 'Numbskull', 'First Completion', 'Numbskulls look dopey. They have enormous, lumpy heads and a perpetually confused expression. They are in fact mathematical geniuses. This is the baby version, which means it looks even more confused than usual. Do not be fooled. It just solved for x while you were reading this.', 1),
('first_language', 'Baby Grammarpede', '🐛✏️', 'Completed your first Language challenge.', 'Common', 'Grammarpede', 'First Completion', 'A Grammarpede is a centipede where each of its one hundred legs is a different punctuation mark. The baby version only has twelve legs so far. Three of them are commas. It will judge you for every run-on sentence you have ever written, including that one.', 1),

-- Perfect Score
('perfect_verbal', 'Grand Wordumph', '🎩💬', '10/10 correct on a Verbal challenge.', 'Rare', 'Grand Wordumph', 'Perfect Score', 'The Grand Wordumph has read every thesaurus ever printed and considers this the bare minimum. It speaks in analogies so layered that linguists need three weeks to unpack one sentence. It reviewed your perfect score, said ''adequate,'' and handed you a vocabulary list for next time.', 1),
('perfect_quantitative', 'Infinite Seriesnake', '🐍♾️', '10/10 correct on a Quantitative challenge.', 'Rare', 'Infinite Seriesnake', 'Perfect Score', 'The Infinite Seriesnake has no tail — it goes on forever, each segment the correct next term in an ever-more-complex sequence. Mathematicians have been following it for three years trying to find the pattern. You found it in 34 seconds. The Seriesnake is impressed. It does not show this.', 1),
('perfect_reading', 'Sopping Pageslobber', '📚💦', '10/10 correct on a Reading challenge.', 'Rare', 'Sopping Pageslobber', 'Perfect Score', 'The Sopping Pageslobber has absorbed so many passages it is perpetually drenched. Libraries ban it for obvious reasons. It has perfect recall of every main idea, every inference, every vocabulary word in context. It read your mind to check your work. Your mind was correct. It slobbered approvingly.', 1),
('perfect_mathematics', 'Colossal Numbskull', '💀💎', '10/10 correct on a Mathematics challenge.', 'Rare', 'Colossal Numbskull', 'Perfect Score', 'The Colossal Numbskull has a head so large from accumulated math knowledge that it tips over occasionally. It does not care. It rights itself, solves another theorem, and looks confused about everything that isn''t a number. Your perfect score caused a small crystal to grow on its enormous skull. You put it there.', 1),
('perfect_language', 'Hundred-Legged Grammarpede', '🐛👑', '10/10 correct on a Language challenge.', 'Rare', 'Hundred-Legged Grammarpede', 'Perfect Score', 'The Hundred-Legged Grammarpede has all one hundred legs and every one of them is a correctly used punctuation mark. It has never, in its entire life, used a comma splice. It once fainted when someone said ''I could care less.'' It reviewed your perfect score and wept a single, grammatically appropriate tear.', 1),

-- Speed
('speed_verbal', 'Blabbering Wordumph', '🎩💨', 'Blazing speed through a Verbal challenge.', 'Rare', 'Blabbering Wordumph', 'Speed', 'The Blabbering Wordumph talks so fast that its synonyms come out in alphabetical order. It answered all ten verbal questions before it finished clearing its throat. It is now mid-sentence on a different topic entirely. Nobody has ever successfully interrupted one.', 1),
('speed_quantitative', 'Turbo Seriesnake', '🐍💨', 'Blazing speed through a Quantitative challenge.', 'Rare', 'Turbo Seriesnake', 'Speed', 'The Turbo Seriesnake moves so fast that it laps its own tail and accidentally extends the sequence. Mathematicians chasing the Infinite Seriesnake have never seen one move this fast. You matched its speed. It zipped past and left a number in your hair. That number is the next term.', 1),
('speed_reading', 'Frantic Pageslobber', '📘⚡', 'Blazing speed through a Reading challenge.', 'Rare', 'Frantic Pageslobber', 'Speed', 'The Frantic Pageslobber ingests passages so quickly that it sometimes slobbers on the questions too. This is considered rude but also impressive. It absorbed all five passages in the time it takes most creatures to read the first sentence. It still got every inference right. It is a menace.', 1),
('speed_mathematics', 'Zippy Numbskull', '💀💨', 'Blazing speed through a Mathematics challenge.', 'Rare', 'Zippy Numbskull', 'Speed', 'The Zippy Numbskull looks confused at all times but solves equations before the pencil hits the paper. Its enormous head gives it so much calculating power that it experiences time slightly differently. By the time you finished reading the problem, it had already checked the answer twice.', 1),
('speed_language', 'Stampeding Grammarpede', '🐛💨', 'Blazing speed through a Language challenge.', 'Rare', 'Stampeding Grammarpede', 'Speed', 'The Stampeding Grammarpede moves so fast its hundred legs blur into a grammatical smear. Each step it takes corrects a different error in the English language. It spotted your dangling modifier before you finished the sentence. It fixed it before it moved on. You barely saw it happen.', 1),

-- Combo 2-section
('combo_verbal_quant', 'The Algebraggart', '🧮💬', 'High score in Verbal AND Quantitative.', 'Epic', 'Algebraggart', 'Combo', 'An Algebraggart brags about both vocabulary and number sequences simultaneously, often in the same breath. It will compliment your analogy, point out the Fibonacci structure of your sentence, and then correct your synonym — all before you can respond. It is exhausting to be around. It is very proud of this.', 1),
('combo_verbal_reading', 'The Blabberphage', '📖💬', 'High score in Verbal AND Reading.', 'Epic', 'Blabberphage', 'Combo', 'A Blabberphage eats books whole and then immediately, at length, tells everyone exactly what they were about. It recounts main ideas, inferences, and vocabulary words in context, using extremely impressive synonyms. It once summarized a novel in thirty-seven analogies. The novel was shorter than the summary.', 1),
('combo_verbal_math', 'The Calculoquist', '🗣️🧮', 'High score in Verbal AND Mathematics.', 'Epic', 'Calculoquist', 'Combo', 'A Calculoquist is a ventriloquist — but instead of a puppet, it uses algebra. It speaks in elaborate metaphors that, upon examination, also happen to be proofs. Its dummy is a quadratic equation named Gerald. Gerald has never said anything grammatically incorrect. Gerald is terrifying.', 1),
('combo_verbal_language', 'The Snootifax', '🎩📝', 'High score in Verbal AND Language.', 'Epic', 'Snootifax', 'Combo', 'A Snootifax is unbearably correct about everything related to language. It knows every word, uses all of them properly, and will — without being asked — point out when you haven''t. It once spent forty-five minutes explaining the difference between ''further'' and ''farther'' to a parking meter. The parking meter did not change. The Snootifax felt it had made its point.', 1),
('combo_quant_math', 'The Numberwump', '🐻🔢', 'High score in Quantitative AND Mathematics.', 'Epic', 'Numberwump', 'Combo', 'A Numberwump is a large, round, wumpus-adjacent creature that simply loves numbers with its entire body. It collects number series the way other animals collect acorns. It sleeps on a bed of solved equations. When it woke up and saw your scores, it made a sound like a calculator hitting a high note. This is its version of a standing ovation.', 1),
('combo_quant_reading', 'The Inferbat', '🦇📊', 'High score in Quantitative AND Reading.', 'Epic', 'Inferbat', 'Combo', 'The Inferbat reads everything and immediately infers more than is probably warranted. It hangs upside down for optimal comprehension and echolocates inference. It once read a bus schedule and inferred that the author was going through something emotionally. It was statistically likely. The Inferbat is always right.', 1),
('combo_quant_language', 'The Syntactodon', '🦕⚙️', 'High score in Quantitative AND Language.', 'Epic', 'Syntactodon', 'Combo', 'The Syntactodon is ancient, enormous, and absolutely will not tolerate a sentence that doesn''t also follow a numerical pattern. It roamed the prehistoric era correcting cave paintings for comma splices and arranging boulders into Fibonacci sequences. It is still doing this. It will never stop.', 1),
('combo_reading_math', 'The Theorebeast', '🐗📐', 'High score in Reading AND Mathematics.', 'Epic', 'Theorebeast', 'Combo', 'A Theorebeast reads math textbooks for fun. For FUN. It does not consider this unusual. It takes detailed notes in the margins. Its favorite genre is ''proof.'' When it finishes a particularly satisfying theorem it closes the book, nods slowly, and makes a sound like ''mmmm.'' It has made this sound fourteen thousand times. It will make it again.', 1),
('combo_reading_language', 'The Palimpsestopus', '🐙📜', 'High score in Reading AND Language.', 'Epic', 'Palimpsestopus', 'Combo', 'A Palimpsestopus is an octopus made entirely of layered old manuscripts, and each of its eight arms is holding a different grammar rule. It reads with six arms, edits with one, and uses the last to gesture dramatically at incorrectly placed apostrophes. It cannot believe what it has to deal with.', 1),
('combo_math_language', 'The Proofreadacorn', '🌰✏️', 'High score in Mathematics AND Language.', 'Epic', 'Proofreadacorn', 'Combo', 'A Proofreadacorn is small, persistent, and always correct. It arrives unannounced, sits on your shoulder, and quietly points out that your equation is wrong AND your sentence is a fragment. It does this in a tiny but confident voice. It has no memory of ever being wrong. This is because it has never been wrong.', 1),

-- Combo 3-section
('combo_v_q_m', 'The Mathemoggart', '🧮💬🐗', 'High score in Verbal, Quantitative, AND Mathematics.', 'Legendary', 'Mathemoggart', 'Combo', 'A Mathemoggart is what happens when an Algebraggart and a Numberwump collide at high speed. The result is a creature that brags in three disciplines simultaneously: vocabulary, sequences, and equations. Conversations with one last approximately four hours and are secretly educational. Nobody admits they enjoyed it.', 1),
('combo_v_r_l', 'The Snabberphage', '📚🎩🐛', 'High score in Verbal, Reading, AND Language.', 'Legendary', 'Snabberphage', 'Combo', 'A Snabberphage is what you get when a Blabberphage and a Snootifax have an argument and a Grammarpede referees. It eats books, describes them using extraordinarily precise vocabulary, and corrects its own grammar mid-sentence. It once hyphenated a word it was physically saying out loud. Nobody questioned it.', 1),
('combo_q_m_l', 'The Syntumberwump', '🦕🐻⚙️', 'High score in Quantitative, Mathematics, AND Language.', 'Legendary', 'Syntumberwump', 'Combo', 'A Syntumberwump is a Numberwump that got into a heated argument with a Syntactodon about whether semicolons can separate terms in a series. The resulting fusion loves numbers AND grammar with equal, unsettling intensity. It writes number sequences with perfect punctuation and considers this its greatest achievement. It is correct.', 1),
('combo_r_q_m', 'The Infernumbeast', '🦇🐗🔢', 'High score in Reading, Quantitative, AND Mathematics.', 'Legendary', 'Infernumbeast', 'Combo', 'An Infernumbeast is what happens when a Theorebeast starts hanging upside down and the Inferbat starts solving equations. The resulting creature reads data like passages, processes passages like equations, and infers mathematical proofs from context clues. It finds all of this very normal. It is not very normal.', 1),
('combo_v_r_m', 'The Blabberore', '📖💬🐗', 'High score in Verbal, Reading, AND Mathematics.', 'Legendary', 'Blabberore', 'Combo', 'A Blabberore is a Blabberphage that went through a math phase and never came back out. It now summarizes novels using geometric proofs and describes triangles using extended metaphors. It once explained the Pythagorean theorem using three analogies and a passage about frogs. Everyone understood immediately.', 1),
('combo_v_q_l', 'The Algebraggardpede', '🧮💬🐛', 'High score in Verbal, Quantitative, AND Language.', 'Legendary', 'Algebraggardpede', 'Combo', 'The Algebraggardpede is an Algebraggart that absorbed a Grammarpede and is now even harder to argue with. It brags about sequences AND vocabulary AND grammar in rapid rotation. Each of its many legs is a punctuation mark or a number. It is very long. It has a lot to say. It is already saying it.', 1),
('combo_r_m_l', 'The Proofreadabeast', '🌰📐📜', 'High score in Reading, Mathematics, AND Language.', 'Legendary', 'Proofreadabeast', 'Combo', 'A Proofreadabeast is a Theorebeast that found a Proofreadacorn on its shoulder and decided not to remove it. The Proofreadacorn did not ask for permission. Together they read, solve, and correct everything in their path. The Proofreadacorn points. The Proofreadabeast nods. Nothing escapes them.', 1),
('combo_q_r_l', 'The Inferbatopus', '🦇🐙🔢', 'High score in Quantitative, Reading, AND Language.', 'Legendary', 'Inferbatopus', 'Combo', 'An Inferbatopus is a Palimpsestopus that merged with an Inferbat during a grammatical dispute. It now hangs upside down from a manuscript, reads everything, edits everything, and then infers seventeen additional things about the author''s emotional state. It is usually right.', 1),

-- All Five
('combo_all_five', 'The Grand Snabberumbwump', '🌟🐉🎩', 'High score in ALL FIVE sections.', 'Mythic', 'Grand Snabberumbwump', 'Combo', 'Nobody planned the Grand Snabberumbwump. It happened when every single one of the lesser creatures got into an argument about which subject was most important and fused together mid-debate. The result is enormous, pedantic, slightly soggy from Pageslobber residue, covered in punctuation legs, and absolutely correct about everything all the time. It is bragging right now. It cannot stop. It scored perfectly on the HSPT in 1987 and has never emotionally moved on from this achievement. Neither should you.', 1),

-- Milestone
('milestone_3', 'The Tryagain', '🔁🐾', 'Completed 3 total challenges.', 'Uncommon', 'Tryagain', 'Milestone', 'The Tryagain is a creature with no memory of failure and no concept of giving up. It simply appears whenever someone completes their third attempt at something. Nobody knows where it lives in between. It shows up, nods approvingly, and wanders off. It will be back.', 1),
('milestone_10', 'The Decadoofus', '🏆🤪', 'Completed 10 total challenges.', 'Rare', 'Decadoofus', 'Milestone', 'The Decadoofus has done everything ten times. Every time. It has ten horns, ten tails, and an expression that says ''I''ve seen this before'' about literally everything. It arrived when you finished your tenth run, handed you an invisible trophy, tripped over its own tails, and somehow made it look intentional.', 1),
('milestone_all_sections', 'The Pentaflop', '🌐🫠', 'Completed at least one challenge in every section.', 'Epic', 'Pentaflop', 'Milestone', 'The Pentaflop is a creature that has attempted every discipline and is, frankly, a little tired. It respects that you''ve done the same. It doesn''t excel at any one thing. It shows up for all of them. It would rather be napping but here it is. Here you both are. Five sections down. The Pentaflop gives you a tired high five.', 1),
('milestone_all_perfect', 'The Flawlesswump', '💎🐻', 'Perfect score (10/10) in ALL five sections.', 'Mythic', 'Flawlesswump', 'Milestone', 'The Flawlesswump looks like a regular Numberwump except every single one of its hairs is a correct answer. It has 4,200 hairs. All of them are right. It achieved a perfect score across all five sections sometime in the early 2000s and has been extremely calm about it ever since. It saw your scores and simply sat down next to you. That''s the whole thing. That''s the compliment.', 1);

-- Part C — Replace questions
TRUNCATE questions;

INSERT INTO questions (section, difficulty, prompt, passage, options, correct_index, explanation) VALUES
-- VERBAL
('verbal', 1, 'HAPPY most nearly means:', NULL, '["Sad","Joyful","Angry","Tired"]', 1, 'Joyful and happy both mean feeling pleasure or contentment.'),
('verbal', 1, 'ANCIENT is the opposite of:', NULL, '["Old","Large","Modern","Quiet"]', 2, 'Ancient means very old; modern means recent — direct opposites.'),
('verbal', 1, 'All cats are animals. All animals need food. All cats need food — true, false, or uncertain?', NULL, '["True","False","Uncertain","Neither"]', 0, 'By syllogism: cats → animals → need food. True.'),
('verbal', 2, 'Paintbrush is to painter as scalpel is to:', NULL, '["Hospital","Surgeon","Nurse","Patient"]', 1, 'A paintbrush is the primary tool of a painter; a scalpel is the primary tool of a surgeon.'),
('verbal', 2, 'Which word does NOT belong with the others?', NULL, '["Hammer","Wrench","Screwdriver","Paintbrush"]', 3, 'Hammer, wrench, screwdriver are repair tools; paintbrush is an art tool.'),
('verbal', 2, 'ELOQUENT most nearly means:', NULL, '["Loud","Articulate","Confused","Brief"]', 1, 'Eloquent means expressing ideas fluently and persuasively.'),
('verbal', 2, 'Some musicians are teachers. All teachers are college graduates. Some musicians are college graduates — true, false, or uncertain?', NULL, '["True","False","Uncertain","Cannot be determined"]', 0, 'Musicians who are teachers must be graduates, so at least some musicians are graduates.'),
('verbal', 3, 'Sycophant is to flattery as martyr is to:', NULL, '["Religion","Sacrifice","Courage","Victory"]', 1, 'A sycophant is defined by flattery; a martyr is defined by sacrifice.'),
('verbal', 3, 'LOQUACIOUS most nearly means:', NULL, '["Silent","Logical","Talkative","Lazy"]', 2, 'Loquacious means tending to talk a great deal.'),
('verbal', 3, 'No reptiles are warm-blooded. Some egg-layers are warm-blooded. Some egg-layers are reptiles — true, false, or uncertain?', NULL, '["True","False","Uncertain","Impossible"]', 2, 'Reptiles lay eggs, but whether warm-blooded egg-layers overlap with reptiles cannot be determined.'),

-- QUANTITATIVE
('quantitative', 1, 'What number comes next?  2, 4, 6, 8, ___', NULL, '["9","10","12","11"]', 1, 'Adding 2 each time: 8 + 2 = 10.'),
('quantitative', 1, 'A number multiplied by 3 gives 21. What is the number?', NULL, '["6","9","7","8"]', 2, '21 ÷ 3 = 7.'),
('quantitative', 1, 'What number comes next?  100, 90, 80, 70, ___', NULL, '["55","65","60","50"]', 2, 'Subtracting 10 each time: 70 − 10 = 60.'),
('quantitative', 2, 'What number comes next?  3, 6, 12, 24, ___', NULL, '["36","42","48","30"]', 2, 'Each term doubles: 24 × 2 = 48.'),
('quantitative', 2, 'Examine: (A) 3/4 vs. (B) 7/10. Which is greater?', NULL, '["A is greater","B is greater","Equal","Cannot determine"]', 0, '3/4 = 0.75; 7/10 = 0.70. A is greater.'),
('quantitative', 2, 'A number is divided by 5, then 8 is added, giving 12. What was the original number?', NULL, '["20","25","15","30"]', 0, '12 − 8 = 4; 4 × 5 = 20.'),
('quantitative', 2, 'What number comes next?  1, 4, 9, 16, ___', NULL, '["20","25","21","24"]', 1, 'Perfect squares: 1², 2², 3², 4², 5² = 25.'),
('quantitative', 3, 'What number comes next?  2, 3, 5, 8, 13, ___', NULL, '["18","19","21","20"]', 2, 'Fibonacci: each = sum of prior two. 8 + 13 = 21.'),
('quantitative', 3, 'Examine: (A) 5² − 3²  vs.  (B) (5−3)². Which is greater?', NULL, '["A is greater","B is greater","Equal","Cannot determine"]', 0, 'A: 25 − 9 = 16. B: 2² = 4. A is greater.'),
('quantitative', 3, 'The average of five consecutive even numbers is 18. What is the largest?', NULL, '["20","22","24","26"]', 1, 'Numbers centered on 18: 14,16,18,20,22. Largest = 22.'),

-- READING
('reading', 1, 'Where do monarchs spend the winter?', 'Monarch butterflies migrate up to 3,000 miles from Canada and the US to their wintering grounds in the mountains of central Mexico. Scientists study how they navigate using the sun as a compass.', '["Canada","United States","Mountains of central Mexico","South America"]', 2, 'The passage directly states monarchs travel to the mountains of central Mexico.'),
('reading', 1, 'As used in the passage, ''navigate'' most nearly means:', 'Monarch butterflies migrate up to 3,000 miles from Canada and the US to their wintering grounds in the mountains of central Mexico. Scientists study how they navigate using the sun as a compass.', '["Fly fast","Find one''s way","Avoid danger","Rest and recover"]', 1, 'Navigate means to find one''s way.'),
('reading', 1, 'What percentage of Earth''s surface do rain forests cover?', 'Rain forests cover about 6% of Earth''s surface but house more than half of the world''s plant and animal species. They regulate climate by absorbing large amounts of carbon dioxide.', '["25%","50%","6%","12%"]', 2, 'The passage states rain forests cover about 6% of Earth''s surface.'),
('reading', 2, 'Which conclusion is best supported by the passage?', 'In 1869, the Transcontinental Railroad let passengers travel coast-to-coast in about a week — versus months by wagon or ship. It accelerated westward settlement and created a national market for goods.', '["The railroad hurt the wagon industry.","The railroad had mostly negative effects.","The railroad connected the nation economically and geographically.","Most Americans moved to California."]', 2, 'The passage emphasizes both geographic and economic impact.'),
('reading', 2, 'What is the main idea of this passage?', 'In 1869, the Transcontinental Railroad let passengers travel coast-to-coast in about a week — versus months by wagon or ship. It accelerated westward settlement and created a national market for goods.', '["The railroad was completed in 1869.","Travel to California was once slow.","The Transcontinental Railroad greatly changed American society and economy.","Thousands of families moved west."]', 2, 'The passage''s main idea is its sweeping national impact.'),
('reading', 2, 'As used in the passage, ''accelerated'' most nearly means:', 'In 1869, the Transcontinental Railroad let passengers travel coast-to-coast in about a week — versus months by wagon or ship. It accelerated westward settlement and created a national market for goods.', '["Slowed","Stopped","Sped up","Reversed"]', 2, 'Accelerated means increased in speed or rate.'),
('reading', 2, 'Before the printing press, why were books rare?', 'The printing press, invented by Gutenberg around 1440, let books be produced quickly and cheaply. Before it, books were copied by hand — making them rare and expensive. Literacy spread as ideas circulated freely.', '["Paper hadn''t been invented.","Books were copied by hand — slow and expensive.","Governments restricted production.","Most people couldn''t read."]', 1, 'The passage states books were ''copied by hand, making them rare and expensive.'''),
('reading', 3, 'Why do advertisers use cognitive dissonance principles?', 'Cognitive dissonance (Festinger, 1957) describes the discomfort of holding two conflicting beliefs simultaneously. People resolve it by changing a belief, acquiring new information, or minimizing one conflict. Advertisers design messages that shift audiences toward resolving dissonance in a preferred direction.', '["To confuse audiences so they buy more.","To guide audiences to resolve internal conflicts in ways that favor the advertiser.","To introduce psychology to the public.","To ensure audiences feel comfortable."]', 1, 'The passage states advertisers shift audiences toward resolving dissonance in a preferred direction.'),
('reading', 3, 'The author ends with advertisers primarily to:', 'Cognitive dissonance (Festinger, 1957) describes the discomfort of holding two conflicting beliefs simultaneously. People resolve it by changing a belief, acquiring new information, or minimizing one conflict. Advertisers design messages that shift audiences toward resolving dissonance in a preferred direction.', '["Criticize the ad industry.","Show the concept has real-world applications beyond psychology.","Prove dissonance is harmful.","Discourage readers from ads."]', 1, 'The final sentence extends a psychological concept into practical application.'),
('reading', 3, 'The phrase ''luxury of ethical deliberation'' suggests:', 'Societies have long debated whether prosperity causes virtue or virtue causes prosperity. Ancient Greeks believed character preceded wealth. Later thinkers argued the reverse: material security frees people to pursue moral development, since desperate people rarely have the luxury of ethical deliberation.', '["Ethics is only for the wealthy.","People in desperate circumstances may lack time or resources for moral choices.","Ancient Greeks were wrong.","Ethical deliberation is unimportant."]', 1, '''Luxury'' implies ethical deliberation requires conditions of security that desperate people may not have.'),

-- MATHEMATICS
('math', 1, 'What is 15% of 200?', NULL, '["25","30","35","40"]', 1, '0.15 × 200 = 30.'),
('math', 1, 'What is 3² + 4²?', NULL, '["25","49","14","7"]', 0, '9 + 16 = 25.'),
('math', 1, 'What is the remainder when 47 is divided by 6?', NULL, '["4","5","6","3"]', 1, '47 ÷ 6 = 7 remainder 5.'),
('math', 2, 'If 4x − 5 = 19, what is x?', NULL, '["5","6","7","8"]', 1, '4x = 24 → x = 6.'),
('math', 2, 'A rectangle has length 12 and width 7. What is the area?', NULL, '["38","74","84","19"]', 2, 'Area = 12 × 7 = 84.'),
('math', 2, 'Maria drives 60 mph. How long to drive 210 miles?', NULL, '["3 hours","3.5 hours","4 hours","2.5 hours"]', 1, '210 ÷ 60 = 3.5 hours.'),
('math', 2, 'A $120 jacket is 25% off. What is the sale price?', NULL, '["$85","$90","$95","$80"]', 1, '25% of 120 = 30; 120 − 30 = $90.'),
('math', 3, 'The sum of two consecutive integers is 85. What is the larger integer?', NULL, '["41","42","43","44"]', 2, 'n + (n+1) = 85 → n = 42. Larger = 43.'),
('math', 3, 'A right triangle has legs 5 and 12. What is the hypotenuse?', NULL, '["11","13","15","17"]', 1, 'c² = 25 + 144 = 169 → c = 13.'),
('math', 3, 'Pump A fills a pool in 6 hours; Pump B in 4 hours. Together, how long?', NULL, '["2 hours","2.4 hours","3 hours","5 hours"]', 1, 'Combined rate: 1/6 + 1/4 = 5/12 per hour → 12/5 = 2.4 hours.'),

-- LANGUAGE
('language', 1, 'Which sentence uses punctuation correctly?', NULL, '["She went to the store, and bought milk.","She went to the store and bought milk.","She went to the store and, bought milk.","She went, to the store and bought milk."]', 1, 'No comma before ''and'' when joining two verbs with the same subject.'),
('language', 1, 'Which sentence is correctly capitalized?', NULL, '["We visited the grand canyon last Summer.","we visited the Grand Canyon last summer.","We visited the Grand Canyon last summer.","We visited The Grand Canyon last summer."]', 2, 'Grand Canyon is a proper noun; summer is not.'),
('language', 1, 'Which word is spelled correctly?', NULL, '["Recieve","Recive","Receive","Receeve"]', 2, 'R-E-C-E-I-V-E — i before e except after c.'),
('language', 2, 'Choose the grammatically correct sentence.', NULL, '["Each of the students have completed their project.","Each of the students has completed their project.","Each of the students have completed his project.","Each of the students has completed their projects."]', 1, '''Each'' is singular → ''has.'' ''Their'' is accepted as singular gender-neutral.'),
('language', 2, 'Which sentence uses the apostrophe correctly?', NULL, '["The dog''s bone is buried in the yard''s.","The dogs bone is buried in the yard.","The dog''s bone is buried in the yard.","The dogs'' bone is buried in the yard."]', 2, 'Dog''s (singular possessive) is correct.'),
('language', 2, 'Which sentence best fits as a topic sentence about exercise benefits?', NULL, '["Many people find exercise boring.","Running shoes come in many styles.","Regular exercise offers numerous physical and mental health benefits.","Some athletes train many hours per day."]', 2, 'A topic sentence states the paragraph''s main idea.'),
('language', 2, 'Choose the correctly written sentence.', NULL, '["Between you and I, this is a great idea.","Between you and me, this is a great idea.","Between you and myself, this is a great idea.","Between I and you, this is a great idea."]', 1, '''Between'' is a preposition requiring object pronouns. ''Me'' is correct.'),
('language', 3, 'Choose the grammatically correct sentence.', NULL, '["Neither the coach nor the players was ready.","Neither the coach nor the players were ready.","Neither the coach nor the players is ready.","Neither the coach nor the players are ready."]', 1, 'With ''neither…nor,'' verb agrees with closer subject — ''players'' (plural) → ''were.'''),
('language', 3, 'Which sentence uses the semicolon correctly?', NULL, '["She studied hard; but she failed.","She studied hard; she passed with high marks.","She studied; hard and passed.","She; studied hard and passed."]', 1, 'Semicolons join two independent clauses without a conjunction.'),
('language', 3, 'Which sentence contains a dangling modifier?', NULL, '["Running through the park, the dog chased the squirrel.","Running through the park, the squirrel was chased by Sarah.","Sarah chased the squirrel through the park.","The squirrel ran as Sarah chased it."]', 1, 'In B, ''Running through the park'' modifies ''squirrel'' — but Sarah was running.');
