-- 020 — Add 114 reading questions
--
-- 64 passage-based questions across 16 passages (4 each)
-- plus 50 standalone vocabulary questions (passage IS NULL).
-- Pure insert. Ids are deterministic: md5(section || '|' || prompt)::UUID,
-- so re-running this file is a no-op. Nothing existing is deleted or updated.

-- ── 1. Passage-based questions ──────────────────────────────────────────────
WITH p(pkey, body) AS (VALUES
  ('p01', 'Deep beneath the Antarctic surface lies a record of the planet''s past that no library contains. Each year, snow falls on the ice sheet and is buried by the snow of the following year. Under the weight of the layers above, the older snow is squeezed into solid ice, and tiny bubbles of air are sealed inside it. Those bubbles are samples of the atmosphere exactly as it was on the day that snow fell.

Scientists recover these records by drilling long cylinders of ice, called cores, out of the sheet and raising them to the surface in sections. Because the layers stack in order, a core can be read much as the rings of a tree are read: the ice near the top is recent, while the ice at the bottom may be hundreds of thousands of years old. By measuring the gases trapped in each layer, researchers can determine how much carbon dioxide the air held at a given moment in the past. The chemistry of the ice itself also indicates how cold the air was when the snow formed.

The results have reshaped our understanding of climate. Cores drawn from the deepest Antarctic ice show that carbon dioxide levels and temperature have risen and fallen together for as long as the record extends. No written account reaches back nearly so far, yet the ice has kept its measurements faithfully, one winter at a time.'),
  ('p02', 'The tardigrade is among the least impressive animals a person could look at and among the most difficult to kill. Rarely longer than a millimeter, it has eight stubby legs, a rounded body, and a lumbering walk that earned it the nickname water bear. Tardigrades live in mosses, in soil, in lakes, and in the sea, and they feed by piercing plant cells and drawing out the contents.

What sets them apart is what they do when conditions turn hostile. Deprived of water, a tardigrade pulls in its legs, expels most of the moisture from its body, and curls into a barrel-shaped form called a tun. In this state its chemical activity nearly stops. It does not eat, grow, or age in any ordinary sense. Researchers have revived tuns that spent years in dry moss, and specimens in the tun state have endured boiling temperatures, pressures greater than those at the bottom of the ocean, and even direct exposure to the vacuum of space during an orbital experiment.

None of this makes the tardigrade invincible. An active, hydrated tardigrade is a fragile creature that a careless footstep or a warm afternoon can destroy. Its survival depends entirely on entering the tun before trouble arrives. Endurance, in the tardigrade''s case, is less a matter of toughness than of timing.'),
  ('p03', 'A forest looks like a collection of separate trees. Underground, it behaves more like a single connected system. Threads of fungus far thinner than a human hair wrap around and grow into the roots of most forest trees, forming a partnership that biologists call mycorrhiza. The fungus reaches into soil that roots cannot penetrate and delivers water and minerals such as phosphorus to the tree. In exchange, the tree passes down sugars it has made in its leaves, which the fungus cannot produce for itself.

Because a single fungal network may link the roots of many trees at once, the exchange does not stop at one pair of partners. Experiments in which trees were supplied with labeled carbon have traced that carbon moving through fungal threads into neighboring trees, sometimes of an entirely different species. Shaded seedlings on the forest floor, too small to gather much sunlight, appear to receive a share of what taller trees produce.

Researchers disagree about how to describe this. Some see cooperation among trees. Others argue that the fungus is the one in charge, moving resources in whatever way benefits itself, with the trees merely trading partners in an ancient bargain. What is not disputed is the scale of the arrangement. Sever the fungal threads in a patch of forest soil, and the trees above grow measurably more slowly.'),
  ('p04', 'The yellows and oranges of autumn leaves are not new colors. They were present in the leaf all summer, hidden beneath something stronger.

Through the growing season a leaf is crowded with chlorophyll, the green pigment that captures sunlight and drives the making of sugar. Chlorophyll is unstable and breaks down constantly, so the tree must keep manufacturing more to replace what is lost. Alongside it sit other pigments, the carotenoids, which absorb light chlorophyll cannot use and which are yellow and orange. As long as green chlorophyll is being replenished, it overwhelms them.

Shorter days and colder nights signal the tree to prepare for winter. It stops producing chlorophyll, and a layer of cells begins to close off the base of each leaf stem. The chlorophyll already in the leaf continues to break down and is not replaced. Within days the green fades and the carotenoids that were there all along become visible.

Reds are a different story. Many trees actively produce a pigment called anthocyanin in autumn, manufacturing it in the leaf just before the leaf is discarded. Because that production depends on sugar trapped in the leaf, bright sunny days followed by cool nights tend to produce the most brilliant red displays. A warm, cloudy autumn yields a duller forest, though the yellows still arrive on schedule.'),
  ('p05', 'More than nine-tenths of the water on Earth is salt water, and none of it can be drunk. For coastal cities running short of fresh water, the ocean is therefore both an enormous resource and a useless one, unless the salt can be taken out.

The oldest method is to imitate the weather. Heat seawater until it becomes vapor, and the salt is left behind; cool the vapor, and pure water condenses. This approach works reliably, but boiling water on a citywide scale consumes a great deal of fuel, which is why large distillation plants have been built mainly where energy is cheap.

Most new plants use a different method, called reverse osmosis. Seawater is forced under high pressure against a membrane that water molecules can pass through but dissolved salt cannot. Fresh water collects on the far side. Reverse osmosis needs far less energy than boiling, and improvements in membranes have steadily lowered its cost.

Even so, desalination remains expensive compared with pumping water from a river or a well, and every plant produces a stream of extremely salty leftover water, or brine, that must go somewhere. Returned carelessly to a shallow bay, that brine can harm the life already there. Engineers now treat the disposal of brine as a problem equal in importance to the removal of the salt itself.'),
  ('p06', 'By the 1700s astronomers could describe the shape of the solar system with confidence. They knew the order of the planets and the proportions of their orbits. What they did not know was its actual size. Every distance was expressed in relative terms, and a single true measurement would have settled all of them at once.

Edmond Halley proposed a method. Occasionally Venus passes directly between Earth and the sun, appearing as a small black dot crossing the solar disk. Observers standing far apart on Earth see that dot follow slightly different paths and therefore record slightly different crossing times. From the difference, Halley argued, the distance to the sun could be calculated. Halley knew he would not live to test the idea; the next transits would occur in 1761 and 1769.

What followed was one of the first scientific efforts organized across national borders. Hundreds of observers sailed to remote stations, including Siberia, Hudson Bay, and Tahiti, in an era when such voyages took months and often ended badly. Clouds ruined some observations. Wars interfered with others. Yet enough measurements survived to yield a figure for the distance between Earth and the sun within a few percent of the value accepted today. A dot crossing the sun for a few hours had given the solar system a scale.'),
  ('p07', 'The Silk Road was never a road, and silk was only part of what moved along it. The name, invented by a German geographer in the 1800s, describes a shifting web of caravan routes that linked the markets of China with those of Central Asia, Persia, and the Mediterranean.

Few travelers covered the whole distance. A merchant typically carried goods to the next major market town, sold them, and turned back with whatever that town offered. The cargo continued in other hands, gaining value at every exchange, so that a bolt of cloth worth little at its origin might be a luxury by the time it reached the far end. Along the way it passed through oasis cities such as Samarkand and Kashgar, which grew wealthy less from what they produced than from where they sat.

Goods were not the only cargo. Paper-making spread westward from China along these routes, and Buddhism traveled eastward into China with merchants and monks. So did disease: historians link the same networks to the movement of plague. When sea routes between Europe and Asia became safer and cheaper in the 1500s, the overland traffic thinned, and many of the great caravan cities declined. Their ruins remain in places that now seem remote, which is itself a reminder that the map of what counts as remote can change.'),
  ('p08', 'In 1817 New York began digging a ditch four feet deep and forty feet wide across the width of the state. Critics called the project Clinton''s Ditch, after the governor who championed it, and predicted it would bankrupt New York. It was 363 miles long, and the men who built it had no engineering school to have attended; they learned the work by doing it.

The problem the canal solved was cost. Before it opened, moving a ton of flour from Buffalo to New York City by wagon cost roughly a hundred dollars and took weeks. Farmers west of the Appalachians had land and grain but no affordable way to reach an eastern buyer, so much of what they grew stayed where it was grown.

The canal opened in 1825, and freight charges collapsed to under ten dollars a ton. Grain flowed east; manufactured goods and settlers flowed west. Towns along the route, among them Rochester and Syracuse, grew from villages into cities within a generation. New York City, now the natural outlet for a continental interior, passed its rival ports and never surrendered the lead.

The canal''s tolls repaid its construction cost within about a decade. By then railroads were already being built, and they would eventually take the traffic, but the pattern of settlement the canal created did not move.'),
  ('p09', 'In July 1848, about three hundred people gathered in a chapel in Seneca Falls, New York, for a meeting that had been announced only days earlier in a local newspaper. The organizers, among them Elizabeth Cady Stanton and Lucretia Mott, had met years before at an antislavery convention in London, where the women delegates had been seated behind a curtain and forbidden to speak.

The convention produced a document called the Declaration of Sentiments, modeled closely on the Declaration of Independence. Where the original listed the offenses of a king, this one listed the legal disadvantages of married women, who in most states could not own property, keep their own wages, or sign a contract. Nearly every resolution passed easily. One did not. The demand for the vote struck many in the room as so far beyond possibility that it would make the whole meeting look ridiculous, and it passed only after Frederick Douglass, the sole prominent Black man present, spoke in its favor.

Newspapers mocked the convention for weeks, and some who had signed the declaration asked to have their names removed. Yet the meeting gave a scattered movement a written statement of its aims. The resolution judged most extreme in that room, the one for suffrage, became the movement''s central demand, and it was won in 1920, seventy-two years later.'),
  ('p10', 'Between roughly 1915 and 1970, some six million Black Americans left the rural South for cities in the North and West. Historians call this movement the Great Migration, though no one organized it. It was made up of individual decisions, repeated in millions of households over half a century.

The reasons for leaving were plain. In the South, Black families faced laws that stripped them of the vote, schools deliberately starved of funding, and a farming system in which a sharecropper could work an entire year and end it owing money to the landowner. The reasons for going north arrived at a particular moment: the First World War halted the flow of European immigrants just as northern factories needed workers, and wages in those factories were several times what a day of field labor paid.

News traveled through letters home and through Black newspapers that circulated hand to hand, carried south by railroad porters. Chains formed. One relative sent for another, and whole southern counties emptied toward particular northern neighborhoods.

What migrants found was better paid and still bounded. Housing was restricted to a few neighborhoods, rents there were higher than elsewhere in the same city, and the better-paying jobs were often closed to them. The migration nonetheless reshaped American cities, politics, and music, and it moved a population that had been overwhelmingly rural into an overwhelmingly urban one.'),
  ('p11', 'Between 1883 and 1929, more than 1,600 public libraries were built in the United States with money from a single donor, the steel manufacturer Andrew Carnegie. Many towns had never had a library of any kind before.

Carnegie''s offer came with conditions, and they mattered more than the buildings. He paid for construction only. The town had to supply the site, and it had to pledge public tax money each year, usually a tenth of the building''s cost, to buy books and pay a librarian. The library also had to be free to every resident. A town that would not commit the tax revenue did not get the grant.

The reasoning behind those terms came from Carnegie''s own history. He had grown up poor and credited his education to a man who opened a private library to working boys on Saturdays. Charity that simply handed people things, he argued, did little good; what helped was giving people the means to improve themselves through their own effort. A library that a community had voted to fund was, in his view, a library that community would use.

Not everyone accepted. Some towns refused the money on the grounds that it had come from the profits of a company known for crushing a strike. Most, however, said yes, and the free public library, funded by local taxes, became an ordinary American institution.'),
  ('p12', 'Today the name Timbuktu is used to mean anywhere impossibly far away. For several centuries it meant the opposite: a destination worth the journey.

The city sits near the southern edge of the Sahara, where the Niger River comes closest to the desert. That position made it a place of exchange. Caravans arrived from the north carrying slabs of salt, which was scarce and valuable in the south, and boats came upriver with gold, grain, and other goods from the forest regions. Traders met at Timbuktu because the desert route and the river route met there.

Wealth from that trade paid for something less expected. By the 1500s Timbuktu held several centers of learning attached to its mosques, where scholars studied law, astronomy, mathematics, and medicine. Books arrived by caravan alongside the salt, and copying manuscripts became a paying trade in the city. Private families assembled libraries of thousands of volumes and passed them down through generations.

A Moroccan army took the city in 1591 and carried leading scholars away, and as European ships began to carry West African trade by sea, the caravan routes grew quiet. The manuscripts, however, stayed. Families hid them in trunks and buried them in the sand through centuries of upheaval, and hundreds of thousands of them survive, a written record of a city later described as having no history.'),
  ('p13', 'Look at a European painting made before about 1420 and something seems off. Buildings do not recede. Figures in the back are the same size as those in front, or are sized by importance rather than distance. The painters were not clumsy. They were working without a rule that had not yet been written down.

That rule is linear perspective, and it was demonstrated in Florence by the architect Filippo Brunelleschi. Its principle is simple. Lines that are parallel in the real world and run away from the viewer are drawn so that they converge on a single point on the horizon, called the vanishing point. Objects are drawn smaller in exact proportion to their distance. Follow the rule and a flat panel produces the sensation of depth.

The technique spread quickly because it could be taught. It was a procedure with steps, not a talent, and workshops across Italy adopted it within a generation. Painters began building rooms and streets on their panels that a viewer could imagine walking into.

There was a cost. Perspective fixes the viewer in one spot, since the picture is correct from a single position only. Medieval painters had been free to show a figure from whatever angle carried the most meaning. In exchange for depth, painting gave up that freedom, and later artists would spend considerable effort trying to take it back.'),
  ('p14', 'A haiku is a Japanese poem built from seventeen sound units, grouped five, seven, and five; English versions count these as syllables and set them in three lines. That description is accurate and almost useless, because it makes the form sound like a puzzle about counting.

The traditional haiku has two other requirements that matter more. The first is a seasonal word. A mention of cherry blossoms places the poem in spring; frost places it in late autumn; a single cicada places it in the heat of summer. The reader supplies everything the season implies, so the poet does not have to. The second requirement is a break, a point where the poem turns and sets two images beside each other without explaining the connection. Meaning appears in the gap between them, and the reader is the one who closes it.

Matsuo Basho, writing in the 1600s, is the poet most associated with the form. His best-known poem describes an old pond, a frog jumping in, and the sound of water. Nothing is stated about what it means. The poem offers stillness, then motion, then sound, and stops.

English haiku often keep the syllable count and drop the rest, which is why so many of them feel like statements chopped into three lines. The counting was never the point. The restraint was.'),
  ('p15', 'The Globe Theatre, where many of Shakespeare''s plays were first performed, was a round wooden building open to the sky. Its shape was not chosen for beauty. It was chosen to pack as many paying people as possible around a stage that jutted into the middle of them.

A penny bought standing room in the yard, the bare ground directly in front of the stage. Those who stood there, called groundlings, were close enough to touch the platform and were not quiet. Another penny or two bought a bench in the roofed galleries that circled the yard. The wealthiest spectators paid more still for the lords'' rooms, roofed boxes beside the stage where they could be seen by everyone.

Performances took place in the afternoon, because there was no lighting beyond daylight. There was almost no scenery either. A play''s setting had to be established in its lines, which is one reason characters so often announce where they are. Nor were there intermissions; the action ran continuously, and a scene ended when its characters walked off and the next ones walked on.

These conditions shaped the writing. A playwright working for the Globe had to hold the attention of a standing, restless, mixed audience for two hours or more, using words and bodies and very little else. The plays that resulted were built for that room.'),
  ('p16', 'The first museums were not public. In sixteenth-century Europe a wealthy collector might fill a room with curiosities, a narwhal tusk, a Roman coin, a stuffed crocodile hung from the ceiling, arranged to impress the visitors who were granted permission to see them. The room was called a cabinet of curiosities, and admission depended on knowing the owner.

Two changes turned such rooms into museums. The first was ownership. Collections began passing into public hands, and institutions opened to any visitor who came to the door. The second was organization. Objects that had been grouped because they were strange were regrouped by category and period, so that a visitor walking through the rooms was walking through an argument about how the objects related to one another.

That second change is easy to overlook, because a museum''s arrangement tends to feel like the natural order of things rather than a set of decisions. Yet every display reflects choices about what belongs together, what is worth a whole room, and what stays in storage, and those choices teach as much as the labels do.

Recent decades have added a further question, one of ownership again: how objects taken during periods of conquest should be handled, and whether some belong in the places they came from rather than in the cities that collected them.')
),
q(pkey, prompt, options, correct_index, difficulty, explanation) AS (VALUES
  ('p01', 'According to the passage, what is sealed inside the bubbles found in ice cores?', '["Samples of the atmosphere from the day the snow fell", "Meltwater that refroze during warm summers", "Dust carried in from other continents", "Seawater pushed upward through the ice sheet"]'::JSONB, 0, 1, 'The passage states that tiny bubbles of air are sealed in the ice and are samples of the atmosphere as it was when that snow fell.'),
  ('p01', 'As used in the last sentence of the passage, the word "faithfully" most nearly means', '["reliably", "devoutly", "reluctantly", "briefly"]'::JSONB, 0, 1, 'The final sentence contrasts written accounts, which do not reach back far, with the ice, which ''has kept its measurements'' one winter at a time. ''Faithfully'' there describes a record that holds accurate and dependable, not one that is religious, unwilling, or short.'),
  ('p01', 'The author compares an ice core to the rings of a tree mainly in order to', '["show that ice cores are found in forests as well as in Antarctica", "argue that trees record climate more accurately than ice does", "explain how scientists cut a core into sections", "help the reader understand that the layers can be read in order of age"]'::JSONB, 3, 2, 'The comparison appears right after the point that the layers stack in order, so it is there to make that ordering familiar to the reader.'),
  ('p01', 'Which conclusion about ice cores is best supported by the passage?', '["They can supply climate information for periods long before any written records existed", "They are the only reliable way to measure present-day carbon dioxide", "They show that temperature and carbon dioxide are unrelated", "They must be drilled every year to remain useful"]'::JSONB, 0, 3, 'The passage ends by noting that no written account reaches back as far as the ice record, which supports this conclusion; the other choices contradict the passage.'),
  ('p02', 'According to the passage, what does a tardigrade do when it loses access to water?', '["It burrows deeper into the soil to find moisture", "It expels most of its moisture and curls into a form called a tun", "It grows a hard outer shell and continues feeding", "It swims to the sea, where water is always available"]'::JSONB, 1, 1, 'The passage directly describes the tardigrade pulling in its legs, expelling moisture, and curling into a barrel-shaped tun.'),
  ('p02', 'As used in the passage, the word "hostile" most nearly means', '["crowded", "unfamiliar", "life-threatening", "poisonous"]'::JSONB, 2, 2, 'The conditions described afterward are drying, heat, and pressure, which threaten survival; the word is broader than poisonous.'),
  ('p02', 'The author mentions the orbital experiment in order to', '["show how far scientists must travel to find tardigrades", "suggest that tardigrades originally came from space", "explain why tardigrades are difficult to photograph", "illustrate how extreme the conditions a tun can survive really are"]'::JSONB, 3, 2, 'The space exposure is the last and most extreme item in a list of conditions tuns have endured, so it serves as an illustration of that endurance.'),
  ('p02', 'The final paragraph suggests that a tardigrade is most likely to die when', '["conditions worsen before it has entered the tun state", "it remains in the tun state for several years", "it is exposed to boiling water while in a tun", "it has too much food available"]'::JSONB, 0, 3, 'The passage says an active, hydrated tardigrade is fragile and that survival depends on entering the tun before trouble arrives.'),
  ('p03', 'According to the passage, what does the tree give the fungus in their partnership?', '["Phosphorus drawn from deep soil", "Shelter from sunlight", "Sugars made in its leaves", "Water absorbed through its roots"]'::JSONB, 2, 1, 'The passage states that the tree passes down sugars made in its leaves, which the fungus cannot produce itself.'),
  ('p03', 'As used in the last sentence of the passage, the word "sever" most nearly means', '["cut", "measure", "fertilize", "bury"]'::JSONB, 0, 2, 'The sentence states a cause and effect: do this to the fungal threads and the trees above grow measurably more slowly. Since those threads deliver water and minerals to the trees, the action that would slow growth is cutting them apart. Measuring, fertilizing, or burying them would not break the connection.'),
  ('p03', 'The passage indicates that researchers disagree about', '["whether fungal threads actually connect tree roots", "whether carbon can move between trees at all", "whether cutting fungal threads slows tree growth", "how to interpret the arrangement between the trees and the fungus"]'::JSONB, 3, 2, 'The disagreement described is over interpretation, cooperation among trees versus a fungus managing resources for itself, not over the facts.'),
  ('p03', 'Which statement would the author most likely agree with?', '["The underground connections between forest trees matter to how the forest grows", "Trees would grow better if fungi were removed from forest soil", "The fungus receives nothing of value from the partnership", "Seedlings on the forest floor are entirely independent of larger trees"]'::JSONB, 0, 3, 'The closing detail, that severing the fungal threads measurably slows growth, shows the author regards the connections as consequential.'),
  ('p04', 'According to the passage, why do leaves look green during the summer?', '["Carotenoids are not yet present in the leaf", "Chlorophyll is constantly replaced and overwhelms the other pigments", "Sunlight reflects off the surface of the leaf", "Anthocyanin is produced only in warm weather"]'::JSONB, 1, 1, 'The passage explains that as long as chlorophyll keeps being replenished, it overwhelms the yellow and orange pigments present alongside it.'),
  ('p04', 'Based on the passage, how do yellow pigments differ from red ones in autumn leaves?', '["Yellow pigments were in the leaf all along, while red ones are newly produced", "Red pigments were present all summer, while yellow ones are newly produced", "Both are produced only after the leaf falls from the tree", "Neither is affected by the amount of sunlight a tree receives"]'::JSONB, 0, 2, 'Carotenoids are described as present all summer and simply revealed, while anthocyanin is actively manufactured in autumn.'),
  ('p04', 'Based on the passage, an autumn that is warm and cloudy would most likely produce', '["no color change at all", "brighter reds than usual", "yellows without especially bright reds", "leaves that stay green into winter"]'::JSONB, 2, 2, 'The passage states that a warm, cloudy autumn yields duller color but that the yellows still arrive on schedule.'),
  ('p04', 'The author''s main purpose in the passage is to', '["persuade readers to plant more maple trees", "compare autumn in different parts of the world", "describe the life cycle of a single leaf from bud to fall", "explain the causes of the color changes seen in autumn leaves"]'::JSONB, 3, 3, 'The passage is an explanation of what causes the yellows, oranges, and reds of autumn, not a persuasive or comparative piece.'),
  ('p05', 'According to the passage, what happens to salt when seawater is boiled during distillation?', '["It is left behind as the water becomes vapor", "It rises with the vapor and is collected separately", "It dissolves completely and disappears", "It passes through a membrane"]'::JSONB, 0, 1, 'The passage states that heating seawater into vapor leaves the salt behind, and cooling the vapor yields pure water.'),
  ('p05', 'According to the passage, what is brine?', '["Seawater that has been heated but not yet cooled", "A membrane used in reverse osmosis", "Fresh water produced by a desalination plant", "Extremely salty leftover water produced by desalination"]'::JSONB, 3, 1, 'The passage defines brine as the stream of extremely salty leftover water that every plant produces.'),
  ('p05', 'What advantage does reverse osmosis have over distillation, according to the passage?', '["It removes more of the salt", "It requires far less energy", "It produces no leftover brine", "It can be used far from the coast"]'::JSONB, 1, 2, 'The passage states that reverse osmosis needs far less energy than boiling and that improvements have lowered its cost.'),
  ('p05', 'The last paragraph suggests that engineers now view a desalination plant as successful only if it', '["operates without any use of electricity", "supplies water more cheaply than a well does", "handles its leftover brine responsibly as well as removing salt", "is built beside a shallow bay"]'::JSONB, 2, 3, 'The final sentence says engineers treat brine disposal as a problem equal in importance to removing the salt.'),
  ('p06', 'According to the passage, what did astronomers of the 1700s already understand about the solar system?', '["The exact distance from Earth to the sun", "The order of the planets and the proportions of their orbits", "The chemical composition of Venus", "The reason transits occur only rarely"]'::JSONB, 1, 1, 'The passage states they knew the order of the planets and the proportions of the orbits but not the system''s actual size.'),
  ('p06', 'According to the passage, why did observers have to be stationed far apart on Earth?', '["So that at least one of them would have clear weather", "So that the transit would be visible in daylight somewhere", "Because the calculation depended on their timings disagreeing slightly", "Because Venus is visible only from the far north and south"]'::JSONB, 2, 2, 'Halley''s method worked only because widely separated observers watch the black dot follow slightly different paths and therefore write down slightly different crossing times. It is the size of that disagreement that the distance to the sun is computed from, so the observers had to be spread far apart to produce it.'),
  ('p06', 'The detail that Halley knew he would not live to test his idea mainly emphasizes', '["how long a wait the test of his idea would require", "that Halley doubted his own method", "that transits of Venus had never been seen before", "that Halley was in poor health"]'::JSONB, 0, 2, 'The sentence is immediately followed by the transit dates of 1761 and 1769, underscoring the long wait before the method could be tried, not any doubt or illness.'),
  ('p06', 'Which conclusion is best supported by the third paragraph?', '["Scientific results sometimes require cooperation and risk on a large scale", "Ocean voyages in the 1700s were generally safe and quick", "Cloudy weather made the entire effort worthless", "Only astronomers from one country took part"]'::JSONB, 0, 3, 'The paragraph describes hundreds of observers from different nations traveling to dangerous remote stations and still producing a usable result.'),
  ('p07', 'According to the passage, who invented the name "Silk Road"?', '["Merchants traveling between Samarkand and Kashgar", "A German geographer in the 1800s", "Buddhist monks who traveled east into China", "Historians studying the spread of plague"]'::JSONB, 1, 1, 'The passage states directly that the name was invented by a German geographer in the 1800s.'),
  ('p07', 'Why did goods become more valuable as they moved along the routes?', '["Because they were taxed only once, at the final market", "Because the routes grew shorter over time", "Because they were resold at each market town along the way", "Because only luxury items were permitted on the caravans"]'::JSONB, 2, 2, 'The passage explains that merchants carried goods to the next market and sold them, so the cargo gained value at every exchange.'),
  ('p07', 'The passage indicates that cities such as Samarkand grew wealthy mainly because of', '["the goods they manufactured themselves", "the size of their farms", "their military strength", "their position along the trading routes"]'::JSONB, 3, 2, 'The passage says these cities grew wealthy less from what they produced than from where they sat.'),
  ('p07', 'The last sentence of the passage suggests that', '["places now considered remote were once at the center of trade", "the ruins of the caravan cities have never been found", "sea routes were more dangerous than overland routes", "trade along the Silk Road never fully stopped"]'::JSONB, 0, 3, 'The author points out that ruins sit in places that now seem remote, and adds that what counts as remote can change.'),
  ('p08', 'According to the passage, what happened to the cost of shipping a ton of flour after the canal opened?', '["It rose from about ten dollars to about a hundred", "It fell from about a hundred dollars to under ten", "It stayed roughly the same but the trip grew faster", "It fell only after the railroads were built"]'::JSONB, 1, 1, 'The passage gives roughly a hundred dollars a ton before the canal and under ten dollars a ton after it opened in 1825.'),
  ('p08', 'Before the canal was built, what problem did farmers west of the Appalachians face?', '["Their land produced very little grain", "Eastern buyers refused to purchase western grain", "They had no affordable way to get their grain to eastern buyers", "Wagons were not yet in use in that part of the country"]'::JSONB, 2, 2, 'The passage says these farmers had land and grain but no affordable way to reach an eastern buyer, so much of the crop stayed put.'),
  ('p08', 'The author mentions that the builders "had no engineering school to have attended" mainly to show that', '["the canal was built badly and had to be repaired often", "New York refused to hire trained workers", "engineering schools existed but were too expensive", "the project was undertaken without established expertise"]'::JSONB, 3, 2, 'The detail follows the description of a huge, doubted project and stresses that the workers learned the job as they went.'),
  ('p08', 'Which conclusion about the canal is best supported by the final paragraph?', '["Its effects outlasted its usefulness as a shipping route", "It never earned back the money spent to build it", "Railroads made the canal impossible to operate", "Its tolls were the main source of New York''s wealth"]'::JSONB, 0, 3, 'The paragraph notes that railroads eventually took the traffic but that the settlement pattern the canal created remained.'),
  ('p09', 'The detail that the women delegates in London were seated behind a curtain mainly helps explain', '["why the organizers took up women''s exclusion as its own cause", "why the convention was announced only days before it met", "why the Declaration of Sentiments listed the offenses of a king", "why newspapers mocked the convention for several weeks afterward"]'::JSONB, 0, 1, 'Stanton and Mott met while working for another reform, and at that meeting they themselves were hidden behind a curtain and forbidden to speak. The detail shows women being shut out of the very cause they had come to serve, which explains why they went on to organize a convention about the standing of women.'),
  ('p09', 'According to the passage, what document was the Declaration of Sentiments modeled on?', '["The Constitution", "A London antislavery petition", "The Declaration of Independence", "A New York state law"]'::JSONB, 2, 1, 'The passage says the document was modeled closely on the Declaration of Independence, listing offenses as the original did.'),
  ('p09', 'According to the passage, why was the resolution demanding the vote nearly rejected?', '["Frederick Douglass spoke against it during the debate", "It had not appeared in the newspaper announcement", "Married women could already vote in most states", "Many present thought it hopeless and embarrassing"]'::JSONB, 3, 2, 'The room regarded the demand for suffrage as so far out of reach that backing it would only invite mockery of the entire convention. It survived the vote only after Douglass argued in its favor.'),
  ('p09', 'The passage''s final paragraph is best described as showing that', '["a proposal ridiculed at the time eventually became the movement''s central goal", "the convention had no lasting effect on American law", "most signers regretted attending the convention", "newspapers of the era generally supported the convention"]'::JSONB, 0, 3, 'The last paragraph pairs the mockery and withdrawn signatures with the fact that the most extreme resolution became the central demand and was won in 1920.'),
  ('p10', 'According to the passage, about how many Black Americans left the South during the Great Migration?', '["Six hundred thousand", "One million", "Six million", "Fifteen million"]'::JSONB, 2, 1, 'The passage states that some six million Black Americans left the rural South between about 1915 and 1970.'),
  ('p10', 'According to the passage, how did the First World War contribute to the migration?', '["It created factory jobs in the South", "It stopped European immigration just as northern factories needed workers", "It ended the sharecropping system", "It lowered the cost of railroad travel"]'::JSONB, 1, 2, 'The passage explains that the war halted the flow of European immigrants at the moment northern factories needed labor.'),
  ('p10', 'The author states that no one organized the Great Migration mainly to emphasize that it', '["happened by accident and had no clear causes", "was kept secret from southern landowners", "was directed by northern factory owners", "resulted from millions of separate family decisions"]'::JSONB, 3, 2, 'The sentence is followed immediately by the point that the movement was made up of individual decisions repeated in millions of households.'),
  ('p10', 'Which statement best captures the passage''s view of what migrants found in the North?', '["Conditions were an improvement but remained restricted", "Conditions were no different from those in the South", "Migrants generally returned south within a few years", "Migrants encountered no limits on housing or employment"]'::JSONB, 0, 3, 'The passage calls what migrants found better paid and still bounded, then lists restricted housing, higher rents, and closed jobs.'),
  ('p11', 'According to the passage, what did Carnegie''s grants pay for?', '["The librarian''s salary", "The construction of the building", "The purchase of books", "The cost of the land"]'::JSONB, 1, 1, 'The passage says he paid for construction only; the town supplied the site and the yearly tax money for books and staff.'),
  ('p11', 'Why did Carnegie require towns to pledge tax money every year?', '["To repay him gradually for the cost of the building", "To keep poorer towns from applying", "Because he believed a community that funded a library would use it", "Because the law required public buildings to be locally financed"]'::JSONB, 2, 2, 'The passage states his view that a library a community had voted to fund was one that community would use.'),
  ('p11', 'The passage suggests that Carnegie''s experience with a private library opened to working boys', '["convinced him that libraries should charge a small fee", "shaped his belief in giving people the means to improve themselves", "led him to build his first library in Scotland", "made him distrust public education"]'::JSONB, 1, 2, 'The passage links that memory directly to his argument that useful giving supplies the means for self-improvement rather than handing things over.'),
  ('p11', 'Which statement about Carnegie''s library program does the passage best support?', '["The conditions attached to the gift did more to establish libraries than the money alone", "Most towns rejected Carnegie''s offer because of how he had made his fortune", "Carnegie libraries were open only to residents who paid dues", "The libraries closed once Carnegie stopped funding them"]'::JSONB, 0, 3, 'The passage says the conditions mattered more than the buildings, and that they made tax-funded free libraries an ordinary institution.'),
  ('p12', 'According to the passage, what did caravans bring to Timbuktu from the north?', '["Gold", "Grain", "Salt", "Boats"]'::JSONB, 2, 1, 'The passage states that caravans arrived from the north carrying slabs of salt, while gold and grain came upriver by boat.'),
  ('p12', 'Why did Timbuktu become a center of trade, according to the passage?', '["It had the largest gold mines in West Africa", "It was the capital of a Moroccan empire", "It produced more grain than the surrounding regions", "The desert caravan route and the river route met there"]'::JSONB, 3, 2, 'The passage explains that the city sits where the Niger comes closest to the Sahara, so traders from both routes met there.'),
  ('p12', 'The passage indicates that scholarship in Timbuktu was made possible mainly by', '["the wealth produced by the city''s trade", "the arrival of the Moroccan army", "the founding of a European university", "the discovery of paper-making in the region"]'::JSONB, 0, 2, 'The passage says wealth from the trade paid for the centers of learning, and that books arrived by caravan alongside the salt.'),
  ('p12', 'The last sentence, describing Timbuktu as "a city later described as having no history," is best understood as', '["a statement the author accepts as accurate", "a claim the surviving manuscripts contradict", "an explanation of why the manuscripts were buried", "a quotation from a Timbuktu scholar"]'::JSONB, 1, 3, 'The author sets the hundreds of thousands of surviving written manuscripts against that description, using them to refute it.'),
  ('p13', 'According to the passage, what is the vanishing point?', '["The spot where the viewer must stand", "The single point on the horizon where receding parallel lines meet", "The edge of the painted panel", "The point at which a painting is finished"]'::JSONB, 1, 1, 'The passage defines it as the single point on the horizon on which parallel lines running away from the viewer converge.'),
  ('p13', 'The author says the early painters "were not clumsy" mainly to', '["show that the flatness reflected a missing method, not poor skill", "praise medieval painting as superior to the work that followed", "suggest that early painters worked more quickly than later ones", "explain why so few paintings survive from before about 1420"]'::JSONB, 0, 1, 'The remark comes immediately before ''They were working without a rule that had not yet been written down.'' The author raises it to head off the natural assumption that odd-looking pictures mean untalented painters: what was absent was a technique nobody had yet worked out.'),
  ('p13', 'According to the passage, why did the technique spread so quickly?', '["Painters were required by law to use it", "It made paintings much faster to produce", "It was a teachable procedure rather than an inborn talent", "It was kept secret within a single workshop"]'::JSONB, 2, 2, 'The passage states that it spread because it could be taught, being a procedure with steps rather than a talent.'),
  ('p13', 'The passage suggests that what medieval painters had, and perspective painters gave up, was', '["the ability to paint on wooden panels", "the use of bright color", "an audience that understood their work", "freedom to show a figure from whatever angle carried the most meaning"]'::JSONB, 3, 3, 'The final paragraph names exactly that freedom as the cost of adopting perspective, which fixes the viewer in one position.'),
  ('p14', 'According to the passage, how many syllables does a traditional haiku contain?', '["Twelve", "Fifteen", "Seventeen", "Twenty-one"]'::JSONB, 2, 1, 'The passage says a haiku is built from seventeen sound units, grouped five, seven, and five, which English versions count as syllables.'),
  ('p14', 'According to the passage, what is the purpose of the seasonal word?', '["It leaves the reader to fill in the poem''s setting", "It helps the poet reach the required syllable count", "It identifies the poet who wrote the poem", "It marks where the poem should be divided into lines"]'::JSONB, 0, 2, 'A word such as frost or cicada carries an entire season with it. Because readers already know what that season suggests, the poet can leave the atmosphere unstated and spend the few available syllables elsewhere.'),
  ('p14', 'The author calls the standard three-line, seventeen-syllable description "almost useless" because it', '["gives the wrong number of syllables", "applies only to poems written after 1600", "reduces the form to counting and leaves out what matters most", "describes Japanese haiku but not English ones"]'::JSONB, 2, 2, 'The passage objects that the description makes the form sound like a counting puzzle, then identifies the seasonal word and the break as more important.'),
  ('p14', 'The final paragraph suggests that many English haiku fall short because they', '["are too long to be read aloud", "keep the syllable rule but abandon the restraint that gives the form its power", "use seasonal words that English readers do not recognize", "imitate Basho''s poems too closely"]'::JSONB, 1, 3, 'The author says English haiku often keep the count and drop the rest, and concludes that the restraint, not the counting, was the point.'),
  ('p15', 'According to the passage, where did the groundlings watch a play?', '["In the roofed galleries", "In the lords'' rooms beside the stage", "Standing in the yard in front of the stage", "Outside the theatre walls"]'::JSONB, 2, 1, 'The passage says a penny bought standing room in the yard directly in front of the stage, and that those who stood there were called groundlings.'),
  ('p15', 'According to the passage, why were performances held in the afternoon?', '["Because most of the audience worked in the evening", "Because the theatre had no lighting other than daylight", "Because plays were forbidden after dark by law", "Because the galleries grew too cold at night"]'::JSONB, 1, 2, 'The passage explains that performances were in the afternoon because there was no lighting beyond daylight.'),
  ('p15', 'The passage suggests that a modern production of a Shakespeare play with elaborate sets would', '["require the audience to stand throughout the performance", "make some of the characters'' spoken descriptions unnecessary", "be impossible to stage without adding several intermissions", "shorten the running time by more than an hour"]'::JSONB, 1, 2, 'The passage explains that a play''s setting had to be established in its lines because the Globe had almost no scenery. If a production shows the setting on stage instead, the lines written to tell the audience where they are would be doing work the set has already done.'),
  ('p15', 'The main idea of the passage is that', '["the physical conditions of the Globe shaped how its plays were written", "the Globe was the largest theatre in England", "Shakespeare preferred wealthy audiences to poor ones", "outdoor theatres are better suited to drama than indoor ones"]'::JSONB, 0, 2, 'Each detail, from the round shape to the daylight to the missing scenery, builds toward the closing claim that the plays were built for that room.'),
  ('p16', 'According to the passage, what was a cabinet of curiosities?', '["A cupboard used to store museum labels", "A room of unusual objects shown to visitors the owner permitted in", "A public museum funded by a city government", "A catalog listing objects for sale"]'::JSONB, 1, 1, 'The passage describes it as a room a wealthy collector filled with curiosities, seen only by visitors granted permission.'),
  ('p16', 'According to the passage, how did the organization of collections change?', '["Objects were arranged by size rather than by owner", "Objects were removed from display and placed in storage", "Objects grouped for their strangeness were regrouped by category and period", "Objects were returned to the countries they came from"]'::JSONB, 2, 2, 'The passage states that objects once grouped because they were strange were regrouped by category and period.'),
  ('p16', 'The author says a museum''s arrangement "is easy to overlook" because it', '["is usually hidden from ordinary visitors", "changes too often for visitors to notice", "is explained only in the wall labels", "seems inevitable rather than deliberately chosen"]'::JSONB, 3, 2, 'The passage contrasts how an arrangement feels with what it actually is. Grouping by category and period strikes a visitor as simply the way things are, so nothing about it invites a second look; yet it reflects decisions about what belongs together and what never leaves storage. Something that looks unavoidable is exactly what a viewer stops noticing.'),
  ('p16', 'Which conclusion about museums is best supported by the passage?', '["A museum makes claims through its choices, not only through its objects", "Museums were more useful when they were private", "Objects in storage are more valuable than those on display", "Museums have changed very little since the sixteenth century"]'::JSONB, 0, 3, 'The passage argues that walking through a museum means walking through an argument, and that display choices teach as much as labels do.')
)
INSERT INTO questions (id, section, passage, prompt, options, correct_index, difficulty, explanation)
SELECT md5('reading' || '|' || q.prompt)::UUID, 'reading'::section_type, p.body,
       q.prompt, q.options, q.correct_index, q.difficulty, q.explanation
FROM q JOIN p ON p.pkey = q.pkey
ON CONFLICT (id) DO NOTHING;

-- ── 2. Standalone vocabulary questions (no passage) ─────────────────────────
WITH q(prompt, options, correct_index, difficulty, explanation) AS (VALUES
  ('Choose the word that means the same as the underlined word: a RAPID decision', '["quick", "careful", "delayed", "unpopular"]'::JSONB, 0, 1, 'Rapid means happening very fast, so quick is the closest match.'),
  ('Choose the word that means the same as the underlined word: a FRAGILE vase', '["heavy", "delicate", "colorful", "expensive"]'::JSONB, 1, 1, 'Fragile means easily broken; delicate carries that same sense of being easily damaged.'),
  ('Choose the word that means the same as the underlined word: an ANCIENT ruin', '["modern", "hidden", "aged", "crowded"]'::JSONB, 2, 1, 'An ancient ruin is one that has stood for a very long time, and ''aged'' carries that sense of great age. ''Modern'' is its opposite, and neither ''hidden'' nor ''crowded'' has anything to do with age.'),
  ('Choose the word that means the same as the underlined word: a GENEROUS gift', '["borrowed", "giving", "tiny", "surprising"]'::JSONB, 1, 2, 'A generous gift is a large, freely given one; giving captures that openhandedness.'),
  ('Choose the word that means the same as the underlined word: a VACANT lot', '["muddy", "fenced", "busy", "empty"]'::JSONB, 3, 1, 'Vacant means unoccupied, and empty is the plainest word for that.'),
  ('Choose the word that means the same as the underlined word: a strong ODOR in the kitchen', '["smell", "noise", "stain", "glow"]'::JSONB, 0, 1, 'An odor is something you detect with your nose, so smell is the synonym.'),
  ('Choose the word that means the same as the underlined word: to ASSIST a neighbor', '["ignore", "hire", "help", "visit"]'::JSONB, 2, 1, 'To assist someone is to give them help, which makes help the direct synonym.'),
  ('Choose the word that means the same as the underlined word: an ENORMOUS crowd', '["polite", "distant", "restless", "huge"]'::JSONB, 3, 1, 'Enormous refers to size, not behavior, so huge is the correct match.'),
  ('Choose the word that means the same as the underlined word: to CONCEAL the evidence', '["hide", "destroy", "examine", "report"]'::JSONB, 0, 1, 'To conceal is to keep something out of sight; destroying or reporting it is a different action.'),
  ('Choose the word that means the same as the underlined word: a WEARY traveler', '["lost", "tired", "wealthy", "cheerful"]'::JSONB, 1, 1, 'Weary describes exhaustion, so tired is the closest synonym.'),
  ('Choose the word that means the same as the underlined word: a CAUTIOUS driver', '["reckless", "elderly", "careful", "skilled"]'::JSONB, 2, 1, 'Cautious means acting with care to avoid risk; reckless is its opposite.'),
  ('Choose the word that means the same as the underlined word: to PERMIT entry', '["deny", "delay", "charge", "allow"]'::JSONB, 3, 1, 'To permit something is to allow it to happen.'),
  ('Choose the word that means the same as the underlined word: a BRIEF speech', '["short", "boring", "famous", "loud"]'::JSONB, 0, 1, 'Brief refers to length of time, so short is the match; a speech can be brief and still interesting.'),
  ('Choose the word that means the same as the underlined word: a PEACEFUL morning', '["rainy", "calm", "early", "chilly"]'::JSONB, 1, 1, 'Peaceful means free from disturbance, which is exactly what calm describes.'),
  ('Choose the word that means the same as the underlined word: a DILIGENT student', '["gifted", "hardworking", "popular", "polite"]'::JSONB, 1, 2, 'Diligent describes steady, careful effort rather than natural talent, so hardworking fits best.'),
  ('Choose the word that means the same as the underlined word: an ABUNDANT harvest', '["plentiful", "early", "ruined", "unexpected"]'::JSONB, 0, 2, 'Abundant means existing in great quantity, which plentiful states directly.'),
  ('Choose the word that means the same as the underlined word: a NOVEL approach', '["risky", "simple", "original", "familiar"]'::JSONB, 2, 2, 'As an adjective, novel means new and not seen before, so original is correct.'),
  ('Choose the word that means the same as the underlined word: to PROVOKE a reaction', '["prevent", "predict", "record", "trigger"]'::JSONB, 3, 2, 'To provoke is to stir something up or bring it about, which is what trigger means.'),
  ('Choose the word that means the same as the underlined word: a RELUCTANT volunteer', '["unwilling", "inexperienced", "eager", "anonymous"]'::JSONB, 0, 2, 'Reluctant means hesitant or resistant; eager is its opposite.'),
  ('Choose the word that means the same as the underlined word: a VIVID description', '["lengthy", "striking", "accurate", "confusing"]'::JSONB, 1, 2, 'Vivid means producing a strong, clear picture in the mind, which striking conveys.'),
  ('Choose the word that means the same as the underlined word: to DIMINISH in size', '["shrink", "swell", "stiffen", "settle"]'::JSONB, 0, 2, 'To diminish is to become smaller, so shrink is the synonym.'),
  ('Choose the word that means the same as the underlined word: an OBSTINATE mule', '["gentle", "clumsy", "stubborn", "aging"]'::JSONB, 2, 2, 'Obstinate means refusing to change course, which is the definition of stubborn.'),
  ('Choose the word that means the same as the underlined word: a PLAUSIBLE excuse', '["dishonest", "lengthy", "rehearsed", "believable"]'::JSONB, 3, 2, 'Plausible means it seems reasonable enough to be true, whether or not it actually is.'),
  ('Choose the word that means the same as the underlined word: to SCRUTINIZE the contract', '["sign", "inspect", "shorten", "reject"]'::JSONB, 1, 2, 'To scrutinize is to look at something very closely, so inspect is the match.'),
  ('Choose the word that means the same as the underlined word: a TRANQUIL lake', '["serene", "shallow", "frozen", "remote"]'::JSONB, 0, 2, 'Tranquil describes stillness and quiet, which serene captures.'),
  ('Choose the word that means the same as the underlined word: an ELOQUENT speaker', '["famous", "nervous", "articulate", "brief"]'::JSONB, 2, 3, 'Eloquent means expressing ideas fluently and persuasively, which is what articulate means.'),
  ('Choose the word that means the same as the underlined word: to ALLEVIATE the pain', '["relieve", "endure", "describe", "ignore"]'::JSONB, 0, 2, 'To alleviate is to make something less severe, so relieve is correct.'),
  ('Choose the word that means the same as the underlined word: a PRUDENT investment', '["daring", "sensible", "costly", "sudden"]'::JSONB, 1, 2, 'Prudent means showing good judgment and caution, which sensible expresses.'),
  ('Choose the word that means the same as the underlined word: a CANDID answer', '["clever", "lengthy", "rude", "honest"]'::JSONB, 3, 2, 'Candid means frank and open; a candid answer is honest, though not necessarily rude.'),
  ('Choose the word that means the same as the underlined word: an INEVITABLE outcome', '["unfortunate", "unavoidable", "surprising", "disputed"]'::JSONB, 1, 2, 'Inevitable means certain to happen no matter what, which unavoidable states.'),
  ('Choose the word that means the same as the underlined word: to FORFEIT the game', '["postpone", "win", "surrender", "replay"]'::JSONB, 2, 2, 'To forfeit is to give something up or lose it by default rather than by playing.'),
  ('Choose the word that means the same as the underlined word: a MEAGER portion', '["scanty", "spicy", "generous", "cold"]'::JSONB, 0, 3, 'Meager means noticeably small or inadequate, which scanty conveys; generous is its opposite.'),
  ('Choose the word that means the same as the underlined word: a TENACIOUS competitor', '["talented", "persistent", "arrogant", "cheerful"]'::JSONB, 1, 3, 'Tenacious means holding on and refusing to quit, so persistent is the closest match.'),
  ('Choose the word that means the same as the underlined word: an AMBIVALENT response', '["enthusiastic", "hostile", "conflicted", "immediate"]'::JSONB, 2, 3, 'Ambivalent means having mixed or opposing feelings, which conflicted describes.'),
  ('Choose the word that means the same as the underlined word: SUPERFLUOUS detail', '["unnecessary", "confusing", "technical", "colorful"]'::JSONB, 0, 3, 'Superfluous means more than is needed, so unnecessary is correct.'),
  ('Choose the word that means the same as the underlined word: an INNOCUOUS remark', '["clever", "harmless", "insulting", "whispered"]'::JSONB, 1, 3, 'Innocuous means causing no harm or offense, which is what harmless means.'),
  ('Choose the word that means the same as the underlined word: a LACONIC reply', '["angry", "delayed", "terse", "confusing"]'::JSONB, 2, 3, 'Laconic means using very few words, which is exactly what terse means.'),
  ('Choose the word that means the same as the underlined word: to EXACERBATE the problem', '["solve", "explain", "avoid", "worsen"]'::JSONB, 3, 3, 'To exacerbate is to make a bad situation worse.'),
  ('Choose the word that means the same as the underlined word: an INTREPID explorer', '["fearless", "wealthy", "famous", "lost"]'::JSONB, 0, 1, 'Intrepid means showing no fear in the face of danger, so fearless is the synonym.'),
  ('Choose the word that means the same as the underlined word: a SPURIOUS claim', '["complicated", "false", "popular", "modest"]'::JSONB, 1, 3, 'Spurious means not genuine, so a spurious claim is a false one.'),
  ('Choose the word that means the same as the underlined word: to CAPITULATE to demands', '["object", "listen", "surrender", "respond"]'::JSONB, 2, 3, 'To capitulate is to stop resisting and give in, which is what surrender means.'),
  ('Choose the word that means the same as the underlined word: an EPHEMERAL trend', '["long-lasting", "recurring", "seasonal", "short-lived"]'::JSONB, 3, 3, 'Ephemeral means lasting only a very short time. Every choice here describes duration, so the item turns on which kind: ''long-lasting'' is the opposite, ''recurring'' and ''seasonal'' describe things that come back, and only ''short-lived'' names something that passes quickly.'),
  ('Choose the word that means the same as the underlined word: a GARRULOUS neighbor', '["talkative", "nosy", "unfriendly", "elderly"]'::JSONB, 0, 3, 'Garrulous specifically means excessively talkative, not merely curious or unpleasant.'),
  ('Choose the word that means the same as the underlined word: to ASSUAGE her guilt', '["admit", "ease", "hide", "deserve"]'::JSONB, 1, 3, 'To assuage is to soothe or lessen an unpleasant feeling, so ease is correct.'),
  ('Choose the word that means the same as the underlined word: an AUSTERE room', '["elegant", "crowded", "bare", "damp"]'::JSONB, 2, 3, 'Austere means plain and without decoration or comfort, which bare conveys.'),
  ('Choose the word that means the same as the underlined word: a PRECARIOUS ledge', '["narrow", "shaded", "distant", "unstable"]'::JSONB, 3, 3, 'Precarious means dangerously insecure, so unstable is the best match; a ledge could be narrow yet solid.'),
  ('Choose the word that means the same as the underlined word: to REPUDIATE the treaty', '["reject", "sign", "translate", "delay"]'::JSONB, 0, 3, 'To repudiate is to formally refuse to accept something, so reject is correct.'),
  ('Choose the word that means the same as the underlined word: an INDIGENT family', '["large", "impoverished", "grateful", "distant"]'::JSONB, 1, 3, 'Indigent means extremely poor; the word refers to poverty, not to size or attitude.'),
  ('Choose the word that means the same as the underlined word: a MAGNANIMOUS gesture', '["hasty", "public", "generous", "puzzling"]'::JSONB, 2, 3, 'Magnanimous means noble and generous, especially toward a rival.'),
  ('Choose the word that means the same as the underlined word: an INSCRUTABLE expression', '["angry", "familiar", "pained", "unreadable"]'::JSONB, 3, 3, 'Inscrutable means impossible to interpret, so unreadable is the match.')
)
INSERT INTO questions (id, section, passage, prompt, options, correct_index, difficulty, explanation)
SELECT md5('reading' || '|' || q.prompt)::UUID, 'reading'::section_type, NULL,
       q.prompt, q.options, q.correct_index, q.difficulty, q.explanation
FROM q
ON CONFLICT (id) DO NOTHING;

-- ── 3. Group questions that share a passage under one passage_id ────────────
DO $$
DECLARE rec RECORD; new_id UUID;
BEGIN
  FOR rec IN SELECT DISTINCT passage FROM questions
             WHERE passage IS NOT NULL AND passage_id IS NULL LOOP
    SELECT passage_id INTO new_id FROM questions
      WHERE passage = rec.passage AND passage_id IS NOT NULL LIMIT 1;
    IF new_id IS NULL THEN new_id := gen_random_uuid(); END IF;
    UPDATE questions SET passage_id = new_id
      WHERE passage = rec.passage AND passage_id IS NULL;
  END LOOP;
END $$;

-- ── Verification: expected 114 rows, 16 passage groups ─────────────────
SELECT '020 reading' AS migration, COUNT(*) AS present, 114 AS expected,
       COUNT(DISTINCT passage_id) AS passage_groups, 16 AS expected_groups
FROM questions
WHERE id IN (
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a RAPID decision')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a FRAGILE vase')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: an ANCIENT ruin')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a GENEROUS gift')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a VACANT lot')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a strong ODOR in the kitchen')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: to ASSIST a neighbor')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: an ENORMOUS crowd')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: to CONCEAL the evidence')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a WEARY traveler')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a CAUTIOUS driver')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: to PERMIT entry')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a BRIEF speech')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a PEACEFUL morning')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a DILIGENT student')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: an ABUNDANT harvest')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a NOVEL approach')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: to PROVOKE a reaction')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a RELUCTANT volunteer')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a VIVID description')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: to DIMINISH in size')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: an OBSTINATE mule')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a PLAUSIBLE excuse')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: to SCRUTINIZE the contract')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a TRANQUIL lake')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: an ELOQUENT speaker')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: to ALLEVIATE the pain')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a PRUDENT investment')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a CANDID answer')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: an INEVITABLE outcome')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: to FORFEIT the game')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a MEAGER portion')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a TENACIOUS competitor')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: an AMBIVALENT response')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: SUPERFLUOUS detail')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: an INNOCUOUS remark')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a LACONIC reply')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: to EXACERBATE the problem')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: an INTREPID explorer')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a SPURIOUS claim')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: to CAPITULATE to demands')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: an EPHEMERAL trend')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a GARRULOUS neighbor')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: to ASSUAGE her guilt')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: an AUSTERE room')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a PRECARIOUS ledge')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: to REPUDIATE the treaty')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: an INDIGENT family')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: a MAGNANIMOUS gesture')::UUID,
  md5('reading' || '|' || 'Choose the word that means the same as the underlined word: an INSCRUTABLE expression')::UUID,
  md5('reading' || '|' || 'According to the passage, what is sealed inside the bubbles found in ice cores?')::UUID,
  md5('reading' || '|' || 'As used in the last sentence of the passage, the word "faithfully" most nearly means')::UUID,
  md5('reading' || '|' || 'The author compares an ice core to the rings of a tree mainly in order to')::UUID,
  md5('reading' || '|' || 'Which conclusion about ice cores is best supported by the passage?')::UUID,
  md5('reading' || '|' || 'According to the passage, what does a tardigrade do when it loses access to water?')::UUID,
  md5('reading' || '|' || 'As used in the passage, the word "hostile" most nearly means')::UUID,
  md5('reading' || '|' || 'The author mentions the orbital experiment in order to')::UUID,
  md5('reading' || '|' || 'The final paragraph suggests that a tardigrade is most likely to die when')::UUID,
  md5('reading' || '|' || 'According to the passage, what does the tree give the fungus in their partnership?')::UUID,
  md5('reading' || '|' || 'As used in the last sentence of the passage, the word "sever" most nearly means')::UUID,
  md5('reading' || '|' || 'The passage indicates that researchers disagree about')::UUID,
  md5('reading' || '|' || 'Which statement would the author most likely agree with?')::UUID,
  md5('reading' || '|' || 'According to the passage, why do leaves look green during the summer?')::UUID,
  md5('reading' || '|' || 'Based on the passage, how do yellow pigments differ from red ones in autumn leaves?')::UUID,
  md5('reading' || '|' || 'Based on the passage, an autumn that is warm and cloudy would most likely produce')::UUID,
  md5('reading' || '|' || 'The author''s main purpose in the passage is to')::UUID,
  md5('reading' || '|' || 'According to the passage, what happens to salt when seawater is boiled during distillation?')::UUID,
  md5('reading' || '|' || 'According to the passage, what is brine?')::UUID,
  md5('reading' || '|' || 'What advantage does reverse osmosis have over distillation, according to the passage?')::UUID,
  md5('reading' || '|' || 'The last paragraph suggests that engineers now view a desalination plant as successful only if it')::UUID,
  md5('reading' || '|' || 'According to the passage, what did astronomers of the 1700s already understand about the solar system?')::UUID,
  md5('reading' || '|' || 'According to the passage, why did observers have to be stationed far apart on Earth?')::UUID,
  md5('reading' || '|' || 'The detail that Halley knew he would not live to test his idea mainly emphasizes')::UUID,
  md5('reading' || '|' || 'Which conclusion is best supported by the third paragraph?')::UUID,
  md5('reading' || '|' || 'According to the passage, who invented the name "Silk Road"?')::UUID,
  md5('reading' || '|' || 'Why did goods become more valuable as they moved along the routes?')::UUID,
  md5('reading' || '|' || 'The passage indicates that cities such as Samarkand grew wealthy mainly because of')::UUID,
  md5('reading' || '|' || 'The last sentence of the passage suggests that')::UUID,
  md5('reading' || '|' || 'According to the passage, what happened to the cost of shipping a ton of flour after the canal opened?')::UUID,
  md5('reading' || '|' || 'Before the canal was built, what problem did farmers west of the Appalachians face?')::UUID,
  md5('reading' || '|' || 'The author mentions that the builders "had no engineering school to have attended" mainly to show that')::UUID,
  md5('reading' || '|' || 'Which conclusion about the canal is best supported by the final paragraph?')::UUID,
  md5('reading' || '|' || 'The detail that the women delegates in London were seated behind a curtain mainly helps explain')::UUID,
  md5('reading' || '|' || 'According to the passage, what document was the Declaration of Sentiments modeled on?')::UUID,
  md5('reading' || '|' || 'According to the passage, why was the resolution demanding the vote nearly rejected?')::UUID,
  md5('reading' || '|' || 'The passage''s final paragraph is best described as showing that')::UUID,
  md5('reading' || '|' || 'According to the passage, about how many Black Americans left the South during the Great Migration?')::UUID,
  md5('reading' || '|' || 'According to the passage, how did the First World War contribute to the migration?')::UUID,
  md5('reading' || '|' || 'The author states that no one organized the Great Migration mainly to emphasize that it')::UUID,
  md5('reading' || '|' || 'Which statement best captures the passage''s view of what migrants found in the North?')::UUID,
  md5('reading' || '|' || 'According to the passage, what did Carnegie''s grants pay for?')::UUID,
  md5('reading' || '|' || 'Why did Carnegie require towns to pledge tax money every year?')::UUID,
  md5('reading' || '|' || 'The passage suggests that Carnegie''s experience with a private library opened to working boys')::UUID,
  md5('reading' || '|' || 'Which statement about Carnegie''s library program does the passage best support?')::UUID,
  md5('reading' || '|' || 'According to the passage, what did caravans bring to Timbuktu from the north?')::UUID,
  md5('reading' || '|' || 'Why did Timbuktu become a center of trade, according to the passage?')::UUID,
  md5('reading' || '|' || 'The passage indicates that scholarship in Timbuktu was made possible mainly by')::UUID,
  md5('reading' || '|' || 'The last sentence, describing Timbuktu as "a city later described as having no history," is best understood as')::UUID,
  md5('reading' || '|' || 'According to the passage, what is the vanishing point?')::UUID,
  md5('reading' || '|' || 'The author says the early painters "were not clumsy" mainly to')::UUID,
  md5('reading' || '|' || 'According to the passage, why did the technique spread so quickly?')::UUID,
  md5('reading' || '|' || 'The passage suggests that what medieval painters had, and perspective painters gave up, was')::UUID,
  md5('reading' || '|' || 'According to the passage, how many syllables does a traditional haiku contain?')::UUID,
  md5('reading' || '|' || 'According to the passage, what is the purpose of the seasonal word?')::UUID,
  md5('reading' || '|' || 'The author calls the standard three-line, seventeen-syllable description "almost useless" because it')::UUID,
  md5('reading' || '|' || 'The final paragraph suggests that many English haiku fall short because they')::UUID,
  md5('reading' || '|' || 'According to the passage, where did the groundlings watch a play?')::UUID,
  md5('reading' || '|' || 'According to the passage, why were performances held in the afternoon?')::UUID,
  md5('reading' || '|' || 'The passage suggests that a modern production of a Shakespeare play with elaborate sets would')::UUID,
  md5('reading' || '|' || 'The main idea of the passage is that')::UUID,
  md5('reading' || '|' || 'According to the passage, what was a cabinet of curiosities?')::UUID,
  md5('reading' || '|' || 'According to the passage, how did the organization of collections change?')::UUID,
  md5('reading' || '|' || 'The author says a museum''s arrangement "is easy to overlook" because it')::UUID,
  md5('reading' || '|' || 'Which conclusion about museums is best supported by the passage?')::UUID
);
