-- 021 — Add 75 verbal questions
--
-- Pure insert. Ids are deterministic: md5(section || '|' || prompt)::UUID,
-- so re-running this file is a no-op. Nothing existing is deleted or updated.

WITH q(prompt, options, correct_index, difficulty, explanation) AS (VALUES
  ('MEND most nearly means:', '["Repair", "Break", "Lose", "Hide"]'::JSONB, 0, 1, 'To mend something is to fix what is torn or broken, so repair is the closest match. Break is the opposite action.'),
  ('VACANT most nearly means:', '["Crowded", "Empty", "Noisy", "Heavy"]'::JSONB, 1, 1, 'A vacant seat or building is one with nobody in it — unoccupied, or empty. Crowded is the opposite.'),
  ('RIVAL most nearly means:', '["Helper", "Teacher", "Competitor", "Stranger"]'::JSONB, 2, 1, 'A rival is someone competing against you for the same prize or position, which is exactly what a competitor is.'),
  ('SHOUT most nearly means:', '["Whisper", "Sing", "Listen", "Yell"]'::JSONB, 3, 1, 'To shout is to speak very loudly; yell means the same thing. Whisper is the opposite.'),
  ('WEALTHY most nearly means:', '["Rich", "Kind", "Tall", "Clever"]'::JSONB, 0, 1, 'Wealthy describes someone who has a great deal of money or property — the same idea as rich.'),
  ('ABANDON most nearly means:', '["Rescue", "Desert", "Repair", "Follow"]'::JSONB, 1, 2, 'To abandon something is to leave it behind for good. Desert carries the same meaning of walking away and leaving something unprotected.'),
  ('CONCISE most nearly means:', '["Brief", "Wordy", "Unclear", "Loud"]'::JSONB, 0, 2, 'Concise writing says a lot in few words, so it is brief. Wordy is its opposite.'),
  ('FEEBLE most nearly means:', '["Sturdy", "Weak", "Eager", "Rude"]'::JSONB, 1, 2, 'Feeble describes something lacking strength, such as a feeble grip or a feeble excuse — weak is the match.'),
  ('PROVOKE most nearly means:', '["Soothe", "Ignore", "Irritate", "Forgive"]'::JSONB, 2, 2, 'To provoke someone is to deliberately stir up a reaction, usually anger — that is, to irritate them. Soothe is the opposite.'),
  ('SUMMIT most nearly means:', '["Valley", "Base", "Edge", "Peak"]'::JSONB, 3, 2, 'The summit is the highest point of a mountain — its peak. Base and valley refer to the bottom.'),
  ('LURE most nearly means:', '["Repel", "Tempt", "Scold", "Delay"]'::JSONB, 1, 2, 'To lure is to draw someone in with the promise of something attractive, which is what tempt means. Repel means to drive away.'),
  ('OBSTINATE most nearly means:', '["Cheerful", "Stubborn", "Wealthy", "Careless"]'::JSONB, 1, 3, 'An obstinate person refuses to change course no matter what arguments are offered — the everyday word for that is stubborn.'),
  ('PRUDENT most nearly means:', '["Reckless", "Cautious", "Generous", "Talkative"]'::JSONB, 1, 3, 'Prudent means showing good judgment about risk and consequences, so cautious is the closest match. Reckless is the opposite.'),
  ('ZEALOUS most nearly means:', '["Enthusiastic", "Indifferent", "Dishonest", "Exhausted"]'::JSONB, 0, 3, 'Zealous describes intense, energetic devotion to a cause — enthusiastic. Indifferent means caring not at all.'),
  ('ASTUTE most nearly means:', '["Clumsy", "Shrewd", "Silent", "Wealthy"]'::JSONB, 1, 3, 'Astute means quick to see what is really going on and to act on it — shrewd captures that sharp practical intelligence.'),
  ('SHALLOW is the opposite of:', '["Wide", "Dry", "Deep", "Clear"]'::JSONB, 2, 1, 'Shallow means having little depth, so its opposite is deep. Wide and clear describe other qualities of water, not depth.'),
  ('ACCEPT is the opposite of:', '["Receive", "Reject", "Welcome", "Choose"]'::JSONB, 1, 1, 'To accept is to take what is offered; to reject is to refuse it. Receive and welcome are near-synonyms of accept, not opposites.'),
  ('GATHER is the opposite of:', '["Collect", "Stack", "Scatter", "Count"]'::JSONB, 2, 1, 'To gather is to bring things together into one place; to scatter is to spread them apart. Collect means the same as gather.'),
  ('PRAISE is the opposite of:', '["Criticize", "Admire", "Honor", "Applaud"]'::JSONB, 0, 1, 'Praise expresses approval; criticize expresses disapproval. Admire, honor, and applaud all agree with praise.'),
  ('WEALTH is the opposite of:', '["Poverty", "Health", "Comfort", "Luxury"]'::JSONB, 0, 1, 'Wealth is having a great deal; poverty is having very little. Luxury and comfort go along with wealth rather than against it.'),
  ('SCARCE is the opposite of:', '["Rare", "Plentiful", "Hidden", "Costly"]'::JSONB, 1, 2, 'Scarce means there is not enough to go around; plentiful means there is more than enough. Rare is a synonym of scarce.'),
  ('FORBID is the opposite of:', '["Prevent", "Punish", "Permit", "Ignore"]'::JSONB, 2, 2, 'To forbid is to rule that something may not happen; to permit is to allow it. Prevent is close in meaning to forbid, not opposed to it.'),
  ('HASTEN is the opposite of:', '["Hurry", "Arrive", "Prepare", "Delay"]'::JSONB, 3, 2, 'To hasten is to make something happen sooner; to delay is to push it later. Hurry is a synonym of hasten.'),
  ('ARTIFICIAL is the opposite of:', '["Natural", "Fake", "Modern", "Cheap"]'::JSONB, 0, 2, 'Artificial means made by people rather than occurring on its own, so natural is its opposite. Fake is a synonym.'),
  ('DIMINISH is the opposite of:', '["Shrink", "Increase", "Vanish", "Weaken"]'::JSONB, 1, 2, 'To diminish is to become smaller or less; to increase is to become greater. Shrink and weaken agree with diminish.'),
  ('FERTILE is the opposite of:', '["Productive", "Green", "Damp", "Barren"]'::JSONB, 3, 2, 'Fertile soil produces abundant growth; barren land produces nothing. Productive is a synonym of fertile.'),
  ('ABATE is the opposite of:', '["Subside", "Intensify", "Lessen", "Soften"]'::JSONB, 1, 3, 'To abate is to become less severe, as a storm abates. Its opposite is to intensify. Subside, lessen, and soften all mean roughly the same as abate.'),
  ('AFFABLE is the opposite of:', '["Friendly", "Surly", "Talkative", "Generous"]'::JSONB, 1, 3, 'Affable means pleasant and easy to talk to; surly means rude and bad-tempered. Friendly is a synonym of affable, so it cannot be the answer.'),
  ('TRANSIENT is the opposite of:', '["Fleeting", "Brief", "Permanent", "Hollow"]'::JSONB, 2, 3, 'Transient means lasting only a short time, so permanent — lasting indefinitely — is its opposite. Fleeting and brief are synonyms of transient.'),
  ('LUCID is the opposite of:', '["Clear", "Confusing", "Bright", "Honest"]'::JSONB, 1, 3, 'A lucid explanation is easy to follow, so its opposite is a confusing one. Clear is a synonym of lucid, and is therefore a trap.'),
  ('Hot is to cold as day is to:', '["Morning", "Night", "Sun", "Week"]'::JSONB, 1, 1, 'Hot and cold are opposites. The opposite of day is night. Morning is a part of day, and a week contains days, so neither is an opposite.'),
  ('Pilot is to airplane as driver is to:', '["Road", "Car", "Ticket", "Engine"]'::JSONB, 1, 1, 'A pilot operates an airplane, so the pair is operator to vehicle operated. A driver operates a car. A road is where the car goes, not the thing operated.'),
  ('Duckling is to duck as piglet is to:', '["Farm", "Pig", "Mud", "Calf"]'::JSONB, 1, 1, 'A duckling is the young form of a duck. A piglet is the young form of a pig. A calf is a young cow, not the adult of a piglet.'),
  ('Knife is to cut as broom is to:', '["Sweep", "Wash", "Dig", "Fold"]'::JSONB, 0, 1, 'A knife is the tool used to cut; a broom is the tool used to sweep. Each pair links a tool to its own specific action.'),
  ('Shoe is to foot as hat is to:', '["Hair", "Head", "Coat", "Glove"]'::JSONB, 1, 1, 'A shoe is the garment worn on the foot, and a hat is the garment worn on the head. Each pair links an item of clothing to the body part it covers; a coat and a glove are other garments, not body parts.'),
  ('Clock is to time as ruler is to:', '["Length", "Weight", "Speed", "Temperature"]'::JSONB, 0, 2, 'A clock is the instrument that measures time; a ruler is the instrument that measures length. Each pair is instrument to the quantity it measures.'),
  ('Whisper is to shout as drizzle is to:', '["Cloud", "Downpour", "Mist", "Puddle"]'::JSONB, 1, 2, 'A whisper is a mild version of a shout — same thing, far greater intensity. A drizzle is a mild version of a downpour. Mist is even lighter than drizzle, not more intense.'),
  ('Bee is to hive as bear is to:', '["Forest", "Den", "River", "Tree"]'::JSONB, 1, 2, 'A hive is the specific dwelling a bee builds and lives in; a den is the specific dwelling of a bear. A forest is the broad habitat, not the dwelling.'),
  ('Flock is to sheep as school is to:', '["Fish", "Birds", "Wolves", "Students"]'::JSONB, 0, 2, 'A flock is the collective term for a group of sheep; a school is the collective term for a group of fish. Students attend a school building — a different meaning of the word.'),
  ('Conductor is to orchestra as coach is to:', '["Whistle", "Team", "Stadium", "Referee"]'::JSONB, 1, 2, 'A conductor directs an orchestra; a coach directs a team. A whistle is the coach''s tool and a stadium is the location, so neither matches the leader-to-group relationship.'),
  ('Antidote is to poison as remedy is to:', '["Doctor", "Illness", "Pharmacy", "Recovery"]'::JSONB, 1, 2, 'An antidote counteracts a poison; a remedy counteracts an illness. Recovery is the result of the remedy, not the thing it works against.'),
  ('Botanist is to plants as entomologist is to:', '["Fossils", "Insects", "Stars", "Rocks"]'::JSONB, 1, 3, 'A botanist is the scientist who studies plants; an entomologist is the scientist who studies insects. Fossils belong to a paleontologist and stars to an astronomer.'),
  ('Cacophony is to sound as stench is to:', '["Odor", "Silence", "Taste", "Fragrance"]'::JSONB, 0, 3, 'A cacophony is an unpleasant kind of sound; a stench is an unpleasant kind of odor. Each is a harsh instance of its broader category. A fragrance is a pleasant odor, so it reverses the relationship.'),
  ('Anarchy is to government as silence is to:', '["Sound", "Law", "Music", "Order"]'::JSONB, 0, 3, 'Anarchy is the complete absence of government; silence is the complete absence of sound. Music is only one kind of sound, so it is too narrow.'),
  ('Ravenous is to hungry as exhausted is to:', '["Rested", "Tired", "Bored", "Awake"]'::JSONB, 1, 3, 'Ravenous is an extreme degree of hungry; exhausted is an extreme degree of tired. Rested and awake are opposites of exhausted, not milder forms of it.'),
  ('All triangles have three sides. Figure Y is a triangle. Figure Y has three sides — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 0, 1, 'The first statement applies to every triangle without exception, and Figure Y is stated to be a triangle. The conclusion follows necessarily, so it is true.'),
  ('All members of the chess club play chess. Devon is a member of the chess club. Devon plays chess — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 0, 1, 'Devon belongs to a group in which every member plays chess, so what is true of all members must be true of Devon. True.'),
  ('No penguins can fly. Pip is a penguin. Pip can fly — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 1, 1, 'The first statement rules out flight for every penguin. Since Pip is a penguin, the claim that Pip can fly contradicts it directly, so it is false.'),
  ('Some apples are red. The fruit in the bowl is an apple. The fruit in the bowl is red — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 2, 1, 'Only some apples are red, so being an apple does not settle the color. This particular apple could be red or could be green. Uncertain.'),
  ('All violins have strings. Some instruments in the room have strings. Some instruments in the room are violins — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 2, 2, 'Violins are one kind of stringed instrument, but guitars and harps also have strings. The stringed instruments in the room might all be guitars, so we cannot conclude any are violins. Uncertain.'),
  ('All third-graders at Lincoln School wear uniforms. Nina wears a uniform. Nina is a third-grader at Lincoln School — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 2, 2, 'The rule runs one direction only: third-graders wear uniforms. It does not say that only third-graders do. Nina could be a fifth-grader, or attend another school entirely. Uncertain.'),
  ('No reptile has fur. Some pets have fur. Some pets are not reptiles — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 0, 2, 'The pets that have fur cannot be reptiles, because no reptile has fur. Those pets are therefore non-reptiles, which makes the conclusion true.'),
  ('All buses in the city are electric. Bus 12 runs in the city. Bus 12 is electric — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 0, 2, 'Bus 12 falls inside the group covered by the first statement — buses in the city — and that statement allows no exceptions. True.'),
  ('Some runners are swimmers. No swimmers are cyclists. Some runners are not cyclists — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 0, 2, 'There is at least one runner who is also a swimmer. No swimmer is a cyclist, so that runner is not a cyclist. At least one runner is therefore not a cyclist. True.'),
  ('Every item on the menu contains dairy. Some items on the menu are desserts. Some desserts contain dairy — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 0, 2, 'At least one dessert is on the menu, and everything on the menu contains dairy. That dessert therefore contains dairy, which makes the conclusion true.'),
  ('All poets are writers. No writers are illiterate. Some poets are illiterate — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 1, 3, 'Every poet is a writer, and no writer is illiterate, so no poet can be illiterate. The claim that some are contradicts the chain, so it is false.'),
  ('Every student who passed the exam studied. Marcus studied. Marcus passed the exam — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 2, 3, 'Studying is stated as something all passers did, not as something that guarantees passing. Marcus may have studied and still failed, so the conclusion cannot be established. Uncertain.'),
  ('No member of the orchestra is under sixteen. Some members of the orchestra play the violin. Some violin players are under sixteen — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 2, 3, 'The statements tell us only about violinists inside this orchestra, and those are all sixteen or older. They say nothing about violin players elsewhere, who may well be younger. Uncertain.'),
  ('All amphibians are cold-blooded. No cold-blooded creature keeps a constant body temperature. Some amphibians keep a constant body temperature — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 1, 3, 'Amphibians are all cold-blooded, and cold-blooded creatures never keep a constant body temperature. So no amphibian can, and the conclusion is false.'),
  ('Some treaties are ratified. All ratified treaties are enforceable. Some treaties are enforceable — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 0, 3, 'At least one treaty is ratified, and every ratified treaty is enforceable. That treaty is therefore enforceable, so at least some treaties are. True.'),
  ('Which word does NOT belong with the others: Trumpet, Violin, Cello, Harp?', '["Trumpet", "Violin", "Cello", "Harp"]'::JSONB, 0, 1, 'Violin, cello, and harp all make sound from vibrating strings. A trumpet is a brass instrument played by blowing air, so it lacks that shared property.'),
  ('Which word does NOT belong with the others: Carrot, Cherry, Potato, Onion?', '["Carrot", "Cherry", "Potato", "Onion"]'::JSONB, 1, 1, 'Carrot, potato, and onion are all vegetables that grow underground. A cherry is a fruit that grows on a tree.'),
  ('Which word does NOT belong with the others: Robin, Eagle, Bat, Sparrow?', '["Robin", "Eagle", "Bat", "Sparrow"]'::JSONB, 2, 1, 'Robin, eagle, and sparrow are birds. A bat also flies, but it is a mammal, not a bird — flight is the trap, not the shared category.'),
  ('Which word does NOT belong with the others: Chair, Table, Sofa, Curtain?', '["Chair", "Table", "Sofa", "Curtain"]'::JSONB, 3, 1, 'Chair, table, and sofa are pieces of furniture that stand on the floor. A curtain is a window covering, not furniture.'),
  ('Which word does NOT belong with the others: Copper, Silver, Iron, Slate?', '["Copper", "Silver", "Iron", "Slate"]'::JSONB, 3, 2, 'Copper, silver, and iron are metals. Slate is a rock, so it does not share the defining property of the other three.'),
  ('Which word does NOT belong with the others: Whisper, Listen, Mumble, Shout?', '["Whisper", "Listen", "Mumble", "Shout"]'::JSONB, 1, 2, 'Whisper, mumble, and shout are all ways of producing speech. Listen is receiving speech, the opposite side of the exchange.'),
  ('Which word does NOT belong with the others: Mercury, Venus, Europa, Neptune?', '["Mercury", "Venus", "Europa", "Neptune"]'::JSONB, 2, 2, 'Mercury, Venus, and Neptune are planets that orbit the Sun. Europa is a moon of Jupiter — it orbits a planet, not the Sun.'),
  ('Which word does NOT belong with the others: Meter, Liter, Gram, Thermometer?', '["Meter", "Liter", "Gram", "Thermometer"]'::JSONB, 3, 2, 'Meter, liter, and gram are units of measurement. A thermometer is an instrument that takes a measurement, not a unit.'),
  ('Which word does NOT belong with the others: Sprint, Jog, Dash, Stroll?', '["Sprint", "Jog", "Dash", "Stroll"]'::JSONB, 3, 2, 'Sprint, jog, and dash all describe running at speed. To stroll is to walk slowly, so it lacks the shared element of running.'),
  ('Which word does NOT belong with the others: Fern, Oak, Maple, Pine?', '["Fern", "Oak", "Maple", "Pine"]'::JSONB, 0, 2, 'Oak, maple, and pine are trees with woody trunks. A fern is a low, non-woody plant, so it does not belong.'),
  ('Which word does NOT belong with the others: Reluctant, Hesitant, Eager, Wary?', '["Reluctant", "Hesitant", "Eager", "Wary"]'::JSONB, 2, 3, 'Reluctant, hesitant, and wary all describe holding back from acting. Eager describes rushing toward action — the opposite disposition.'),
  ('Which word does NOT belong with the others: Candor, Sincerity, Frankness, Flattery?', '["Candor", "Sincerity", "Frankness", "Flattery"]'::JSONB, 3, 3, 'Candor, sincerity, and frankness all mean speaking honestly. Flattery is insincere praise, so it fails the shared test of honesty.'),
  ('Which word does NOT belong with the others: Novel, Essay, Sonnet, Editorial?', '["Novel", "Essay", "Sonnet", "Editorial"]'::JSONB, 2, 3, 'A novel, an essay, and an editorial are all written in prose. A sonnet is written in verse, with fixed line and meter requirements.'),
  ('Which word does NOT belong with the others: Mitigate, Alleviate, Aggravate, Ease?', '["Mitigate", "Alleviate", "Aggravate", "Ease"]'::JSONB, 2, 3, 'Mitigate, alleviate, and ease all mean to make something less severe. Aggravate means to make it worse — the reverse direction.'),
  ('Which word does NOT belong with the others: Gullible, Skeptical, Naive, Trusting?', '["Gullible", "Skeptical", "Naive", "Trusting"]'::JSONB, 1, 3, 'Gullible, naive, and trusting all describe someone who believes things readily. Skeptical describes someone who doubts and demands proof.')
)
INSERT INTO questions (id, section, passage, prompt, options, correct_index, difficulty, explanation)
SELECT md5('verbal' || '|' || q.prompt)::UUID, 'verbal'::section_type, NULL,
       q.prompt, q.options, q.correct_index, q.difficulty, q.explanation
FROM q
ON CONFLICT (id) DO NOTHING;

-- ── Verification: expected 75 rows ──────────────────────────────────
SELECT '021 verbal' AS migration, COUNT(*) AS present, 75 AS expected
FROM questions
WHERE id IN (
  md5('verbal' || '|' || 'MEND most nearly means:')::UUID,
  md5('verbal' || '|' || 'VACANT most nearly means:')::UUID,
  md5('verbal' || '|' || 'RIVAL most nearly means:')::UUID,
  md5('verbal' || '|' || 'SHOUT most nearly means:')::UUID,
  md5('verbal' || '|' || 'WEALTHY most nearly means:')::UUID,
  md5('verbal' || '|' || 'ABANDON most nearly means:')::UUID,
  md5('verbal' || '|' || 'CONCISE most nearly means:')::UUID,
  md5('verbal' || '|' || 'FEEBLE most nearly means:')::UUID,
  md5('verbal' || '|' || 'PROVOKE most nearly means:')::UUID,
  md5('verbal' || '|' || 'SUMMIT most nearly means:')::UUID,
  md5('verbal' || '|' || 'LURE most nearly means:')::UUID,
  md5('verbal' || '|' || 'OBSTINATE most nearly means:')::UUID,
  md5('verbal' || '|' || 'PRUDENT most nearly means:')::UUID,
  md5('verbal' || '|' || 'ZEALOUS most nearly means:')::UUID,
  md5('verbal' || '|' || 'ASTUTE most nearly means:')::UUID,
  md5('verbal' || '|' || 'SHALLOW is the opposite of:')::UUID,
  md5('verbal' || '|' || 'ACCEPT is the opposite of:')::UUID,
  md5('verbal' || '|' || 'GATHER is the opposite of:')::UUID,
  md5('verbal' || '|' || 'PRAISE is the opposite of:')::UUID,
  md5('verbal' || '|' || 'WEALTH is the opposite of:')::UUID,
  md5('verbal' || '|' || 'SCARCE is the opposite of:')::UUID,
  md5('verbal' || '|' || 'FORBID is the opposite of:')::UUID,
  md5('verbal' || '|' || 'HASTEN is the opposite of:')::UUID,
  md5('verbal' || '|' || 'ARTIFICIAL is the opposite of:')::UUID,
  md5('verbal' || '|' || 'DIMINISH is the opposite of:')::UUID,
  md5('verbal' || '|' || 'FERTILE is the opposite of:')::UUID,
  md5('verbal' || '|' || 'ABATE is the opposite of:')::UUID,
  md5('verbal' || '|' || 'AFFABLE is the opposite of:')::UUID,
  md5('verbal' || '|' || 'TRANSIENT is the opposite of:')::UUID,
  md5('verbal' || '|' || 'LUCID is the opposite of:')::UUID,
  md5('verbal' || '|' || 'Hot is to cold as day is to:')::UUID,
  md5('verbal' || '|' || 'Pilot is to airplane as driver is to:')::UUID,
  md5('verbal' || '|' || 'Duckling is to duck as piglet is to:')::UUID,
  md5('verbal' || '|' || 'Knife is to cut as broom is to:')::UUID,
  md5('verbal' || '|' || 'Shoe is to foot as hat is to:')::UUID,
  md5('verbal' || '|' || 'Clock is to time as ruler is to:')::UUID,
  md5('verbal' || '|' || 'Whisper is to shout as drizzle is to:')::UUID,
  md5('verbal' || '|' || 'Bee is to hive as bear is to:')::UUID,
  md5('verbal' || '|' || 'Flock is to sheep as school is to:')::UUID,
  md5('verbal' || '|' || 'Conductor is to orchestra as coach is to:')::UUID,
  md5('verbal' || '|' || 'Antidote is to poison as remedy is to:')::UUID,
  md5('verbal' || '|' || 'Botanist is to plants as entomologist is to:')::UUID,
  md5('verbal' || '|' || 'Cacophony is to sound as stench is to:')::UUID,
  md5('verbal' || '|' || 'Anarchy is to government as silence is to:')::UUID,
  md5('verbal' || '|' || 'Ravenous is to hungry as exhausted is to:')::UUID,
  md5('verbal' || '|' || 'All triangles have three sides. Figure Y is a triangle. Figure Y has three sides — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'All members of the chess club play chess. Devon is a member of the chess club. Devon plays chess — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'No penguins can fly. Pip is a penguin. Pip can fly — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'Some apples are red. The fruit in the bowl is an apple. The fruit in the bowl is red — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'All violins have strings. Some instruments in the room have strings. Some instruments in the room are violins — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'All third-graders at Lincoln School wear uniforms. Nina wears a uniform. Nina is a third-grader at Lincoln School — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'No reptile has fur. Some pets have fur. Some pets are not reptiles — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'All buses in the city are electric. Bus 12 runs in the city. Bus 12 is electric — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'Some runners are swimmers. No swimmers are cyclists. Some runners are not cyclists — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'Every item on the menu contains dairy. Some items on the menu are desserts. Some desserts contain dairy — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'All poets are writers. No writers are illiterate. Some poets are illiterate — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'Every student who passed the exam studied. Marcus studied. Marcus passed the exam — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'No member of the orchestra is under sixteen. Some members of the orchestra play the violin. Some violin players are under sixteen — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'All amphibians are cold-blooded. No cold-blooded creature keeps a constant body temperature. Some amphibians keep a constant body temperature — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'Some treaties are ratified. All ratified treaties are enforceable. Some treaties are enforceable — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Trumpet, Violin, Cello, Harp?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Carrot, Cherry, Potato, Onion?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Robin, Eagle, Bat, Sparrow?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Chair, Table, Sofa, Curtain?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Copper, Silver, Iron, Slate?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Whisper, Listen, Mumble, Shout?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Mercury, Venus, Europa, Neptune?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Meter, Liter, Gram, Thermometer?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Sprint, Jog, Dash, Stroll?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Fern, Oak, Maple, Pine?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Reluctant, Hesitant, Eager, Wary?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Candor, Sincerity, Frankness, Flattery?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Novel, Essay, Sonnet, Editorial?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Mitigate, Alleviate, Aggravate, Ease?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Gullible, Skeptical, Naive, Trusting?')::UUID
);
