-- 022 — Add 72 quantitative questions
--
-- Pure insert. Ids are deterministic: md5(section || '|' || prompt)::UUID,
-- so re-running this file is a no-op. Nothing existing is deleted or updated.

WITH q(prompt, options, correct_index, difficulty, explanation) AS (VALUES
  ('Look at this series: 4, 7, 10, 13, ... What number should come next?', '["15", "16", "17", "19"]'::JSONB, 1, 1, 'Each term is 3 more than the one before: 4, 7, 10, 13. So 13 + 3 = 16.'),
  ('Look at this series: 12, 24, 36, 48, ... What number should come next?', '["54", "56", "60", "72"]'::JSONB, 2, 1, 'The terms are the multiples of 12: 12, 24, 36, 48. The next multiple is 12 x 5 = 60.'),
  ('Look at this series: 100, 95, 90, 85, ... What number should come next?', '["75", "80", "82", "84"]'::JSONB, 1, 1, 'Each term is 5 less than the one before: 85 - 5 = 80.'),
  ('Look at this series: 15, 30, 45, 60, ... What number should come next?', '["65", "70", "75", "90"]'::JSONB, 2, 1, 'The terms count by 15: 15, 30, 45, 60. So 60 + 15 = 75.'),
  ('Look at this series: 64, 32, 16, 8, ... What number should come next?', '["0", "2", "4", "6"]'::JSONB, 2, 1, 'Each term is half the one before: 64, 32, 16, 8. So 8 / 2 = 4.'),
  ('Look at this series: 9, 18, 27, 36, ... What number should come next?', '["40", "42", "45", "54"]'::JSONB, 2, 1, 'The terms are the multiples of 9. The next one is 9 x 5 = 45.'),
  ('Look at this series: 1, 2, 4, 5, 7, 8, 10, ... What number should come next?', '["11", "12", "13", "14"]'::JSONB, 0, 2, 'The steps alternate +1, +2, +1, +2, ... After 10 the step is +1, so 10 + 1 = 11.'),
  ('Look at this series: 3, 4, 6, 9, 13, 18, ... What number should come next?', '["22", "23", "24", "26"]'::JSONB, 2, 2, 'The differences grow by one each time: +1, +2, +3, +4, +5. The next difference is +6, so 18 + 6 = 24.'),
  ('Look at this series: 96, 48, 24, 12, ... What number should come next?', '["4", "6", "8", "10"]'::JSONB, 1, 2, 'Each term is half the one before: 96, 48, 24, 12. So 12 / 2 = 6.'),
  ('Look at this series: 5, 11, 23, 47, ... What number should come next?', '["94", "95", "96", "99"]'::JSONB, 1, 2, 'Each term is double the previous term plus 1: 5x2+1=11, 11x2+1=23, 23x2+1=47. So 47x2+1 = 95.'),
  ('Look at this series: 6, 11, 21, 41, ... What number should come next?', '["61", "80", "81", "82"]'::JSONB, 2, 2, 'Each term is double the previous term minus 1: 6x2-1=11, 11x2-1=21, 21x2-1=41. So 41x2-1 = 81.'),
  ('Look at this series: 20, 19, 17, 14, 10, ... What number should come next?', '["3", "4", "5", "6"]'::JSONB, 2, 2, 'The amounts subtracted grow: -1, -2, -3, -4. The next is -5, so 10 - 5 = 5.'),
  ('Look at this series: 1, 2, 6, 15, 31, ... What number should come next?', '["46", "52", "56", "62"]'::JSONB, 2, 3, 'The differences are the perfect squares 1, 4, 9, 16. The next difference is 25, so 31 + 25 = 56.'),
  ('Look at this series: 2, 6, 14, 30, 62, ... What number should come next?', '["94", "118", "124", "126"]'::JSONB, 3, 3, 'Each term is double the previous term plus 2: 2x2+2=6, 6x2+2=14, ... So 62x2+2 = 126.'),
  ('Look at this series: 3, 8, 15, 24, 35, ... What number should come next?', '["44", "46", "48", "50"]'::JSONB, 2, 3, 'The terms are one less than the squares 4, 9, 16, 25, 36. The next square is 49, so the term is 49 - 1 = 48.'),
  ('Look at this series: 128, 64, 96, 48, 72, 36, ... What number should come next?', '["18", "48", "54", "72"]'::JSONB, 2, 3, 'The operations alternate: divide by 2, then multiply by 1.5. After 72 / 2 = 36 comes 36 x 1.5 = 54.'),
  ('Look at this series: 1, 4, 2, 8, 3, 12, 4, ... What number should come next?', '["5", "13", "16", "20"]'::JSONB, 2, 3, 'Two series are interwoven. The 1st, 3rd, 5th, 7th terms are 1, 2, 3, 4; the 2nd, 4th, 6th are 4, 8, 12. The next term belongs to the second series: 16.'),
  ('Look at this series: 2, 3, 6, 18, 108, ... What number should come next?', '["216", "648", "1296", "1944"]'::JSONB, 3, 3, 'Each term is the product of the two terms before it: 2x3=6, 3x6=18, 6x18=108. So 18 x 108 = 1944.'),
  ('Examine the figures described and find the best answer. Figure A is a square with side 5. Figure B is a rectangle 4 by 6.', '["Figure A has the greater area.", "Figure B has the greater perimeter.", "Figure A has the greater perimeter.", "Figure B has the greater area."]'::JSONB, 0, 1, 'A: area 5x5 = 25, perimeter 20. B: area 4x6 = 24, perimeter 2(4+6) = 20. The perimeters tie, but 25 > 24.'),
  ('Examine the figures described and find the best answer. Figure A is a triangle with base 10 and height 6. Figure B is a rectangle 5 by 6.', '["Figure A has the greater area.", "The two areas are equal.", "Figure B has the greater area.", "The area of A is twice the area of B."]'::JSONB, 1, 1, 'A: (1/2) x 10 x 6 = 30. B: 5 x 6 = 30. The areas are equal.'),
  ('Examine the figures described and find the best answer. Figure A is a circle with radius 3. Figure B is a circle with diameter 8.', '["Figure A has the greater area.", "The areas are equal.", "Figure B has the greater area.", "The area of A is twice the area of B."]'::JSONB, 2, 1, 'B has diameter 8, so its radius is 4. Areas are pi x 3^2 = 9pi and pi x 4^2 = 16pi, so B is larger.'),
  ('Examine the figures described and find the best answer. Figure A is a square with perimeter 24. Figure B is a rectangle 4 by 8.', '["A and B have equal perimeters, but B has the greater area.", "A and B have equal perimeters and equal areas.", "A has the greater perimeter.", "A and B have equal perimeters, but A has the greater area."]'::JSONB, 3, 1, 'A has side 24/4 = 6 and area 36. B has perimeter 2(4+8) = 24 and area 32. Same perimeter, but the square encloses more.'),
  ('Examine the figures described and find the best answer. Figure A is a right triangle with legs 3 and 4. Figure B is a square with side 3.', '["The perimeters are equal, and B has the greater area.", "Figure B has the greater perimeter.", "Figure A has the greater perimeter.", "The perimeters are equal, and A has the greater area."]'::JSONB, 0, 2, 'The triangle''s hypotenuse is 5, so its perimeter is 3+4+5 = 12 and its area is (1/2)(3)(4) = 6. The square''s perimeter is 12 and its area is 9.'),
  ('Examine (A), (B), and (C) and find the best answer. Angle A measures 45 degrees. Angle B is the complement of a 55-degree angle. Angle C is the supplement of a 145-degree angle.', '["Angle A equals angle B.", "Angle B equals angle C.", "Angle C is greater than angle A.", "All three angles are equal."]'::JSONB, 1, 2, 'Complementary angles sum to 90, so B = 90 - 55 = 35. Supplementary angles sum to 180, so C = 180 - 145 = 35. B and C are equal, and both are less than A = 45.'),
  ('Examine the figures described and find the best answer. Figure A is a square with side 6. Figure B is a circle with diameter 6. Use pi = 3.14.', '["The areas are equal.", "The area of B is more than twice the area of A.", "Figure A has the greater area.", "Figure B has the greater area."]'::JSONB, 2, 2, 'A: 6 x 6 = 36. B has radius 3, so its area is 3.14 x 9 = 28.26. The square is larger - a circle drawn inside a square always covers less.'),
  ('Examine the figures described and find the best answer. Figure A is a square of side 8 with a square of side 4 cut away from one corner; the part that remains is shaded. Figure B is a rectangle 6 by 8.', '["The shaded part of A is three-fourths of B.", "The shaded part of A is larger than B.", "B is larger than the shaded part of A.", "The shaded part of A equals B."]'::JSONB, 3, 2, 'Shaded area = 64 - 16 = 48. Rectangle B = 6 x 8 = 48. They are equal.'),
  ('Examine the figures described and find the best answer. Figure A is a rectangle 12 by 3. Figure B is a rectangle 9 by 4.', '["The areas are equal, but A has the greater perimeter.", "The areas are equal, but B has the greater perimeter.", "Figure A has the greater area.", "The areas are equal and the perimeters are equal."]'::JSONB, 0, 2, 'Both areas are 36 (12x3 and 9x4). Perimeters: 2(12+3) = 30 and 2(9+4) = 26. The longer, thinner rectangle has more perimeter.'),
  ('Examine the figures described and find the best answer. Figure A is a rectangular box 2 by 3 by 4. Figure B is a cube with edge 3.', '["Figure A has the greater volume.", "Figure B has the greater volume.", "The volumes are equal.", "The volume of A is twice the volume of B."]'::JSONB, 1, 2, 'A: 2 x 3 x 4 = 24. B: 3 x 3 x 3 = 27. The cube holds more.'),
  ('Examine the figures described and find the best answer. Figure A is a triangle with sides 5, 5, and 6, and a height of 4 drawn to the side of length 6. Figure B is a square with side 4.', '["Figure A has the greater perimeter.", "The perimeters are equal, and A has the greater area.", "The perimeters are equal, and B has the greater area.", "Figure B has the greater perimeter."]'::JSONB, 2, 2, 'A: perimeter 5+5+6 = 16, area (1/2)(6)(4) = 12. B: perimeter 4x4 = 16, area 16. Same perimeter, larger area for the square.'),
  ('Examine the figures described and find the best answer. Figure A is a circle with radius 5. Figure B is a circle with radius 10.', '["B''s circumference is four times A''s, and B''s area is twice A''s.", "B''s circumference and area are both four times A''s.", "B''s circumference is twice A''s, and B''s area is twice A''s.", "B''s circumference is twice A''s, and B''s area is four times A''s."]'::JSONB, 3, 2, 'Doubling the radius doubles the circumference (2 pi r) but multiplies the area (pi r^2) by 2^2 = 4.'),
  ('Examine the figures described and find the best answer. A square with side 4 has a quarter circle of radius 4 removed from one corner. The part of the square that remains is shaded. Use pi = 3.14.', '["The shaded area is between 3 and 4.", "The shaded area is between 4 and 5.", "The shaded area is between 8 and 9.", "The shaded area is between 12 and 13."]'::JSONB, 0, 3, 'Square = 16. Quarter circle = (1/4)(3.14)(4^2) = 12.56. Shaded = 16 - 12.56 = 3.44, which lies between 3 and 4.'),
  ('Examine the figures described and find the best answer. Figure A is an equilateral triangle with side 6. Figure B is a square with side 5.', '["A has the greater perimeter and the greater area.", "A has the greater perimeter, but B has the greater area.", "B has the greater perimeter, but A has the greater area.", "B has the greater perimeter and the greater area."]'::JSONB, 3, 3, 'Perimeters: 3 × 6 = 18 for the triangle versus 4 × 5 = 20 for the square, so B is larger. Areas: the triangle''s height is about 5.2, giving an area of about 15.6, versus the square''s 5 × 5 = 25 - so B is larger there too. B wins on both counts.'),
  ('Examine the figures described and find the best answer. Figure A is a rectangle 8 by 6. Compare its diagonal with one fourth of its perimeter.', '["The diagonal is less than one fourth of the perimeter.", "The diagonal equals one fourth of the perimeter.", "The diagonal is greater than one fourth of the perimeter.", "The diagonal equals half of the perimeter."]'::JSONB, 2, 3, 'The diagonal is sqrt(8^2 + 6^2) = sqrt(100) = 10. The perimeter is 28, so one fourth is 7. Since 10 > 7, the diagonal is greater.'),
  ('Examine the figures described and find the best answer. Figure A is a trapezoid with parallel sides 6 and 10 and height 4. Figure B is a parallelogram with base 8 and height 4.', '["Figure A has the greater area.", "Figure B has the greater area.", "The area of A is twice the area of B.", "The areas are equal."]'::JSONB, 3, 3, 'Trapezoid: (1/2)(6+10)(4) = 32. Parallelogram: 8 x 4 = 32. They are equal, because the trapezoid''s average width is also 8.'),
  ('Examine the figures described and find the best answer. A square 6 by 6 is divided into four equal squares of side 3. The two small squares that meet only at the center corner are shaded. Figure B is a rectangle 3 by 6.', '["The shaded region equals B.", "B is larger than the shaded region.", "The shaded region is twice B.", "The shaded region is larger than B."]'::JSONB, 0, 3, 'Each small square is 3 x 3 = 9, so the shaded region is 18 - half of the 36-unit square. Rectangle B is 3 x 6 = 18, so they match.'),
  ('Examine the figures described and find the best answer. Figure A is a cube with edge 4. Figure B is a rectangular box 2 by 4 by 8.', '["The volumes and the surface areas are equal.", "The volumes are equal, but B has the greater surface area.", "Figure A has the greater volume.", "The volumes are equal, but A has the greater surface area."]'::JSONB, 1, 3, 'Volumes: 4x4x4 = 64 and 2x4x8 = 64. Surface areas: 6(16) = 96 for the cube, and 2(8+32+16) = 112 for the box. A cube is the most compact box for a given volume.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 1/2   (b) 0.5   (c) 50%', '["(a) is greater than (b).", "(c) is greater than (a).", "(a), (b), and (c) are all equal.", "(b) is greater than (c)."]'::JSONB, 2, 1, '1/2, 0.5, and 50% are three ways of writing the same value.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 3/5   (b) 0.6   (c) 65%', '["(a) equals (b), and both are greater than (c).", "(a) is greater than (b).", "(c) is less than (b).", "(a) equals (b), and both are less than (c)."]'::JSONB, 3, 1, '3/5 = 0.6 = (b). And 65% = 0.65 is larger than 0.6.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 2 + 3 x 4   (b) (2 + 3) x 4   (c) 2 x 3 + 4', '["(b) is the greatest.", "(c) is the greatest.", "(a) and (c) are equal.", "(a) is the greatest."]'::JSONB, 0, 1, 'Order of operations: (a) = 2 + 12 = 14, (b) = 5 x 4 = 20, (c) = 6 + 4 = 10. So (b) is largest.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 1/4   (b) 0.3   (c) 20%', '["(a) is greater than (b).", "(b) is greater than (a), and (a) is greater than (c).", "(c) is greater than (a).", "(a), (b), and (c) are all equal."]'::JSONB, 1, 1, 'Written as decimals: 0.25, 0.30, and 0.20. So (b) > (a) > (c).'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 10% of 50   (b) 50% of 10   (c) 25% of 20', '["(b) is greater than (c).", "(c) is less than (a).", "(a), (b), and (c) are all equal.", "(a) is greater than (b)."]'::JSONB, 2, 1, '10% of 50 = 5, 50% of 10 = 5, and 25% of 20 = 5. All three equal 5.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 3 squared   (b) 2 cubed   (c) 4 squared divided by 2', '["(b) is greater than (a).", "(c) is greater than (a).", "(a), (b), and (c) are all equal.", "(a) is greater than both (b) and (c), and (b) equals (c)."]'::JSONB, 3, 1, '(a) = 9, (b) = 8, (c) = 16/2 = 8. So (b) and (c) tie at 8 and (a) is largest.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 5/8   (b) 0.6   (c) 63%', '["(c) is greater than (a), and (a) is greater than (b).", "(b) is greater than (a), and (a) is greater than (c).", "(a) equals (c).", "(a) is greater than (c), and (c) is greater than (b)."]'::JSONB, 0, 2, '5/8 = 0.625. Ordering 0.625, 0.600, 0.630 gives (c) > (a) > (b).'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 2/3   (b) 5/7   (c) 7/10', '["(c) is the greatest.", "(b) is the greatest.", "(a) equals (c).", "(a) is the greatest."]'::JSONB, 1, 2, 'As decimals: 2/3 = 0.667, 5/7 = 0.714, 7/10 = 0.700. So (b) is the greatest.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 0.25 x 80   (b) 80 divided by 4   (c) 1/5 of 80', '["All three are equal.", "(c) is the greatest.", "(a) equals (b), and both are greater than (c).", "(a) equals (c), and both are less than (b)."]'::JSONB, 2, 2, '(a) = 20, (b) = 20 (dividing by 4 is the same as taking 25%), (c) = 16.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 3/4 of 60   (b) 60 decreased by 25%   (c) 0.7 x 60', '["All three are equal.", "(a) is greater than (b).", "(c) is the greatest.", "(a) equals (b), and both are greater than (c)."]'::JSONB, 3, 2, '(a) = 45, (b) = 60 - 15 = 45 (taking away 25% leaves 75%, the same as 3/4), (c) = 42.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) the square root of 64   (b) 2 cubed   (c) the square root of 81', '["(a) equals (b), and (c) is greater than both.", "(a) is greater than (c).", "(b) is the greatest.", "All three are equal."]'::JSONB, 0, 2, '(a) = 8, (b) = 8, (c) = 9. So (a) and (b) tie and (c) is larger.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 15% of 200   (b) 20% of 150   (c) 30% of 90', '["(a) is greater than (b).", "(a) equals (b), and both are greater than (c).", "(b) is less than (c).", "(c) is the greatest."]'::JSONB, 1, 2, '(a) = 30, (b) = 30, (c) = 27. So (a) and (b) tie and both beat (c).'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 0.5 squared   (b) the square root of 0.25   (c) 1/2', '["All three are equal.", "(a) is the greatest.", "(b) equals (c), and both are greater than (a).", "(a) equals (b)."]'::JSONB, 2, 2, '(a) = 0.25, (b) = 0.5, (c) = 0.5. Squaring a number between 0 and 1 makes it smaller, so (a) is the smallest.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 0.3 x 0.3   (b) 0.3 + 0.3   (c) 0.3 divided by 0.3', '["(a) equals (c).", "(a) is the greatest.", "(b) is the greatest.", "(c) is greater than (b), and (b) is greater than (a)."]'::JSONB, 3, 3, '(a) = 0.09, (b) = 0.6, (c) = 1. Multiplying by a decimal less than 1 shrinks a number; dividing a number by itself gives 1.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 1/2 + 1/3   (b) 1/2 x 1/3   (c) 1/2 divided by 1/3', '["(c) is greater than (a), and (a) is greater than (b).", "(a) equals (c).", "(a) is the greatest.", "(b) is the greatest."]'::JSONB, 0, 3, '(a) = 5/6, (b) = 1/6, (c) = 3/2. So (c) > (a) > (b).'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 7/12   (b) 0.58   (c) 57.5%', '["(c) is greater than (a).", "(a) is greater than (b), and (b) is greater than (c).", "(b) is the greatest.", "(a) equals (b)."]'::JSONB, 1, 3, '7/12 = 0.58333..., (b) = 0.580, and (c) = 0.575. Ordering them gives (a) > (b) > (c).'),
  ('Examine (a), (b), and (c) and find the best answer. (a) the average of 4 and 10   (b) the average of 5, 7, and 9   (c) the average of 2, 6, 10, and 14', '["All three are equal.", "(a) is greater than (b).", "(a) equals (b), and (c) is greater than both.", "(c) is the smallest."]'::JSONB, 2, 3, '(a) = 14/2 = 7, (b) = 21/3 = 7, (c) = 32/4 = 8.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 2/5 of 45   (b) 45 decreased by 60%   (c) 45 divided by 2.5', '["(c) is greater than (a).", "(a) is the greatest.", "(b) is the smallest.", "(a), (b), and (c) are all equal."]'::JSONB, 3, 3, '(a) = 18, (b) = 45 - 27 = 18, (c) = 45 / 2.5 = 18. All three equal 18.'),
  ('What number is 4 more than 1/3 of 27?', '["9", "12", "13", "15"]'::JSONB, 2, 1, '1/3 of 27 is 9, and 9 + 4 = 13.'),
  ('What number is 6 less than twice 10?', '["4", "14", "16", "26"]'::JSONB, 1, 1, 'Twice 10 is 20, and 20 - 6 = 14.'),
  ('What number is 1/2 of 3/4 of 40?', '["10", "15", "20", "30"]'::JSONB, 1, 1, '3/4 of 40 is 30, and half of 30 is 15.'),
  ('What number is 5 more than 20% of 50?', '["10", "12", "15", "25"]'::JSONB, 2, 1, '20% of 50 is 10, and 10 + 5 = 15.'),
  ('What number is 3 times the sum of 4 and 5?', '["12", "17", "20", "27"]'::JSONB, 3, 1, 'The sum of 4 and 5 is 9, and 3 x 9 = 27.'),
  ('What number is 1/4 of 60 decreased by 5?', '["10", "11", "15", "20"]'::JSONB, 0, 1, '1/4 of 60 is 15, and 15 - 5 = 10.'),
  ('What number is 8 less than the square of 5?', '["12", "15", "17", "33"]'::JSONB, 2, 2, '5 squared is 25, and 25 - 8 = 17.'),
  ('One fifth of what number is 12?', '["17", "36", "60", "72"]'::JSONB, 2, 2, 'If x/5 = 12, then x = 12 x 5 = 60.'),
  ('What number must be added to 1/2 of 18 to give 30?', '["9", "12", "21", "39"]'::JSONB, 2, 2, '1/2 of 18 is 9, and 30 - 9 = 21.'),
  ('What number is 25% of 3/5 of 100?', '["12", "15", "20", "25"]'::JSONB, 1, 2, '3/5 of 100 is 60, and 25% of 60 is 15.'),
  ('The product of 6 and what number is 3 more than 45?', '["7", "8", "9", "12"]'::JSONB, 1, 2, '3 more than 45 is 48, and 48 / 6 = 8.'),
  ('What number is 2/3 of 90 minus 1/4 of 40?', '["40", "45", "50", "60"]'::JSONB, 2, 2, '2/3 of 90 is 60 and 1/4 of 40 is 10, so 60 - 10 = 50.'),
  ('What number is 3 more than 1/6 of 72?', '["9", "15", "18", "24"]'::JSONB, 1, 2, '1/6 of 72 is 12, and 12 + 3 = 15.'),
  ('Half of what number is 4 less than 20?', '["8", "16", "24", "32"]'::JSONB, 3, 2, '4 less than 20 is 16. If half of x is 16, then x = 32.'),
  ('What number is 1/3 of the difference between 50 and 2?', '["12", "16", "18", "24"]'::JSONB, 1, 3, '50 - 2 = 48, and 1/3 of 48 is 16.'),
  ('40% of what number is 1/2 of 36?', '["18", "36", "45", "72"]'::JSONB, 2, 3, '1/2 of 36 is 18. If 0.4x = 18, then x = 18 / 0.4 = 45.'),
  ('The average of 12, 18, and one other number is 15. What is the other number?', '["12", "14", "15", "16"]'::JSONB, 2, 3, 'Three numbers averaging 15 must total 45. Since 12 + 18 = 30, the missing number is 45 - 30 = 15.'),
  ('What number is 2 more than 3/4 of the product of 4 and 8?', '["18", "24", "26", "34"]'::JSONB, 2, 3, '4 x 8 = 32, and 3/4 of 32 is 24, so 24 + 2 = 26.')
)
INSERT INTO questions (id, section, passage, prompt, options, correct_index, difficulty, explanation)
SELECT md5('quantitative' || '|' || q.prompt)::UUID, 'quantitative'::section_type, NULL,
       q.prompt, q.options, q.correct_index, q.difficulty, q.explanation
FROM q
ON CONFLICT (id) DO NOTHING;

-- ── Verification: expected 72 rows ──────────────────────────────────
SELECT '022 quantitative' AS migration, COUNT(*) AS present, 72 AS expected
FROM questions
WHERE id IN (
  md5('quantitative' || '|' || 'Look at this series: 4, 7, 10, 13, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 12, 24, 36, 48, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 100, 95, 90, 85, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 15, 30, 45, 60, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 64, 32, 16, 8, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 9, 18, 27, 36, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 1, 2, 4, 5, 7, 8, 10, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 3, 4, 6, 9, 13, 18, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 96, 48, 24, 12, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 5, 11, 23, 47, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 6, 11, 21, 41, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 20, 19, 17, 14, 10, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 1, 2, 6, 15, 31, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 2, 6, 14, 30, 62, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 3, 8, 15, 24, 35, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 128, 64, 96, 48, 72, 36, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 1, 4, 2, 8, 3, 12, 4, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 2, 3, 6, 18, 108, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a square with side 5. Figure B is a rectangle 4 by 6.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a triangle with base 10 and height 6. Figure B is a rectangle 5 by 6.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a circle with radius 3. Figure B is a circle with diameter 8.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a square with perimeter 24. Figure B is a rectangle 4 by 8.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a right triangle with legs 3 and 4. Figure B is a square with side 3.')::UUID,
  md5('quantitative' || '|' || 'Examine (A), (B), and (C) and find the best answer. Angle A measures 45 degrees. Angle B is the complement of a 55-degree angle. Angle C is the supplement of a 145-degree angle.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a square with side 6. Figure B is a circle with diameter 6. Use pi = 3.14.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a square of side 8 with a square of side 4 cut away from one corner; the part that remains is shaded. Figure B is a rectangle 6 by 8.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a rectangle 12 by 3. Figure B is a rectangle 9 by 4.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a rectangular box 2 by 3 by 4. Figure B is a cube with edge 3.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a triangle with sides 5, 5, and 6, and a height of 4 drawn to the side of length 6. Figure B is a square with side 4.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a circle with radius 5. Figure B is a circle with radius 10.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. A square with side 4 has a quarter circle of radius 4 removed from one corner. The part of the square that remains is shaded. Use pi = 3.14.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is an equilateral triangle with side 6. Figure B is a square with side 5.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a rectangle 8 by 6. Compare its diagonal with one fourth of its perimeter.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a trapezoid with parallel sides 6 and 10 and height 4. Figure B is a parallelogram with base 8 and height 4.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. A square 6 by 6 is divided into four equal squares of side 3. The two small squares that meet only at the center corner are shaded. Figure B is a rectangle 3 by 6.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a cube with edge 4. Figure B is a rectangular box 2 by 4 by 8.')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 1/2   (b) 0.5   (c) 50%')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 3/5   (b) 0.6   (c) 65%')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 2 + 3 x 4   (b) (2 + 3) x 4   (c) 2 x 3 + 4')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 1/4   (b) 0.3   (c) 20%')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 10% of 50   (b) 50% of 10   (c) 25% of 20')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 3 squared   (b) 2 cubed   (c) 4 squared divided by 2')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 5/8   (b) 0.6   (c) 63%')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 2/3   (b) 5/7   (c) 7/10')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 0.25 x 80   (b) 80 divided by 4   (c) 1/5 of 80')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 3/4 of 60   (b) 60 decreased by 25%   (c) 0.7 x 60')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) the square root of 64   (b) 2 cubed   (c) the square root of 81')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 15% of 200   (b) 20% of 150   (c) 30% of 90')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 0.5 squared   (b) the square root of 0.25   (c) 1/2')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 0.3 x 0.3   (b) 0.3 + 0.3   (c) 0.3 divided by 0.3')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 1/2 + 1/3   (b) 1/2 x 1/3   (c) 1/2 divided by 1/3')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 7/12   (b) 0.58   (c) 57.5%')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) the average of 4 and 10   (b) the average of 5, 7, and 9   (c) the average of 2, 6, 10, and 14')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 2/5 of 45   (b) 45 decreased by 60%   (c) 45 divided by 2.5')::UUID,
  md5('quantitative' || '|' || 'What number is 4 more than 1/3 of 27?')::UUID,
  md5('quantitative' || '|' || 'What number is 6 less than twice 10?')::UUID,
  md5('quantitative' || '|' || 'What number is 1/2 of 3/4 of 40?')::UUID,
  md5('quantitative' || '|' || 'What number is 5 more than 20% of 50?')::UUID,
  md5('quantitative' || '|' || 'What number is 3 times the sum of 4 and 5?')::UUID,
  md5('quantitative' || '|' || 'What number is 1/4 of 60 decreased by 5?')::UUID,
  md5('quantitative' || '|' || 'What number is 8 less than the square of 5?')::UUID,
  md5('quantitative' || '|' || 'One fifth of what number is 12?')::UUID,
  md5('quantitative' || '|' || 'What number must be added to 1/2 of 18 to give 30?')::UUID,
  md5('quantitative' || '|' || 'What number is 25% of 3/5 of 100?')::UUID,
  md5('quantitative' || '|' || 'The product of 6 and what number is 3 more than 45?')::UUID,
  md5('quantitative' || '|' || 'What number is 2/3 of 90 minus 1/4 of 40?')::UUID,
  md5('quantitative' || '|' || 'What number is 3 more than 1/6 of 72?')::UUID,
  md5('quantitative' || '|' || 'Half of what number is 4 less than 20?')::UUID,
  md5('quantitative' || '|' || 'What number is 1/3 of the difference between 50 and 2?')::UUID,
  md5('quantitative' || '|' || '40% of what number is 1/2 of 36?')::UUID,
  md5('quantitative' || '|' || 'The average of 12, 18, and one other number is 15. What is the other number?')::UUID,
  md5('quantitative' || '|' || 'What number is 2 more than 3/4 of the product of 4 and 8?')::UUID
);
