-- 023 — Add 57 math questions
--
-- Pure insert. Ids are deterministic: md5(section || '|' || prompt)::UUID,
-- so re-running this file is a no-op. Nothing existing is deleted or updated.

WITH q(prompt, options, correct_index, difficulty, explanation) AS (VALUES
  ('What is 7 × 0.4?', '["2.4", "0.28", "28", "2.8"]'::JSONB, 3, 1, '7 × 4 = 28, and 0.4 has one decimal place, so the product has one decimal place: 2.8.'),
  ('Which of these decimals is the largest?', '["0.7002", "0.7", "0.075", "0.68"]'::JSONB, 0, 2, 'Line up place values: 0.7000, 0.6800, 0.0750, 0.7002. The thousandths place breaks the tie between 0.7 and 0.7002, so 0.7002 is largest.'),
  ('What is 1/3 of 27?', '["12", "3", "9", "81"]'::JSONB, 2, 1, '"Of" means multiply: (1/3) × 27 = 27 ÷ 3 = 9.'),
  ('Write 3/5 as a percent.', '["60%", "30%", "35%", "53%"]'::JSONB, 0, 1, '3 ÷ 5 = 0.6, and 0.6 × 100 = 60%. (Reading the digits off as 35% is the common trap.)'),
  ('What is 6.4 ÷ 0.8?', '["8", "0.8", "80", "0.08"]'::JSONB, 0, 1, 'Multiply both numbers by 10 to clear the decimal: 64 ÷ 8 = 8.'),
  ('What is 2 1/2 + 1 3/4?', '["4 1/4", "3 3/4", "4 1/2", "3 1/4"]'::JSONB, 0, 2, '2 1/2 = 2 2/4. Adding: 2 2/4 + 1 3/4 = 3 5/4 = 4 1/4.'),
  ('The ratio of boys to girls in a class is 4:5. If there are 36 students in all, how many are girls?', '["20", "18", "24", "16"]'::JSONB, 0, 2, 'The ratio has 4 + 5 = 9 parts, so each part is 36 ÷ 9 = 4 students. Girls get 5 parts: 5 × 4 = 20.'),
  ('If 3 notebooks cost $4.50, how much do 7 notebooks cost at the same rate?', '["$8.75", "$9.50", "$12.00", "$10.50"]'::JSONB, 3, 2, 'One notebook costs $4.50 ÷ 3 = $1.50, so 7 cost 7 × $1.50 = $10.50.'),
  ('Evaluate: −6 + 4 × (−3) − (−5)', '["−23", "−13", "−5", "13"]'::JSONB, 1, 2, 'Multiply first: 4 × (−3) = −12. Then −6 + (−12) = −18, and subtracting −5 adds 5: −18 + 5 = −13.'),
  ('What is 0.6 expressed as a fraction in lowest terms?', '["2/3", "3/5", "1/6", "2/5"]'::JSONB, 1, 2, '0.6 = 6/10, and dividing both parts by 2 gives 3/5.'),
  ('Express 0.000045 in scientific notation.', '["4.5 × 10⁻⁴", "4.5 × 10⁻⁵", "4.5 × 10⁵", "4.5 × 10⁻⁶"]'::JSONB, 1, 3, 'Move the decimal point 5 places to the right to get 4.5, so the exponent is −5: 4.5 × 10⁻⁵. Scientific notation also requires a first factor between 1 and 10.'),
  ('Evaluate: (3⁴ × 3²) ÷ 3⁵', '["1", "9", "27", "3"]'::JSONB, 3, 3, 'Add exponents when multiplying and subtract when dividing: 3^(4+2−5) = 3¹ = 3.'),
  ('What is 12.5% of 320?', '["4", "40", "25", "45"]'::JSONB, 1, 2, '12.5% = 1/8, so 320 ÷ 8 = 40.'),
  ('Simplify: 5x + 3x − 2x', '["4x", "6", "10x", "6x"]'::JSONB, 3, 1, 'Combine like terms on the coefficients: 5 + 3 − 2 = 6, so the result is 6x.'),
  ('If y = 3x − 4, what is y when x = 5?', '["19", "15", "11", "7"]'::JSONB, 2, 1, 'Substitute: y = 3(5) − 4 = 15 − 4 = 11.'),
  ('If x + 12 = 5, what is x?', '["7", "17", "−7", "−17"]'::JSONB, 2, 1, 'Subtract 12 from both sides: x = 5 − 12 = −7.'),
  ('Simplify: 3(2x − 4) + 5x', '["6x − 12", "11x + 12", "11x − 4", "11x − 12"]'::JSONB, 3, 2, 'Distribute: 3(2x − 4) = 6x − 12. Adding 5x gives 11x − 12.'),
  ('Solve for x: (x − 3)/5 = 4', '["23", "20", "17", "7"]'::JSONB, 0, 2, 'Multiply both sides by 5: x − 3 = 20. Then add 3: x = 23.'),
  ('Solve for x: −3x + 7 = 22', '["−5", "5", "9", "−9"]'::JSONB, 0, 2, 'Subtract 7: −3x = 15. Divide by −3: x = −5. Dropping the negative sign gives the trap answer 5.'),
  ('What is the value of 2a² − b when a = 3 and b = 5?', '["7", "13", "1", "31"]'::JSONB, 1, 2, 'Square first: a² = 9, so 2(9) = 18. Then 18 − 5 = 13. Squaring 2a instead of a gives the trap answer 31.'),
  ('Solve the inequality: 5 − 2x < 11', '["x < 8", "x < −3", "x > 3", "x > −3"]'::JSONB, 3, 3, 'Subtract 5: −2x < 6. Dividing by a negative flips the inequality sign: x > −3.'),
  ('If 3(x + 2) − 2(x − 1) = 14, what is x?', '["10", "2", "4", "6"]'::JSONB, 3, 3, 'Distribute carefully: 3x + 6 − 2x + 2 = x + 8. So x + 8 = 14 and x = 6. (Forgetting that −2 × −1 = +2 gives x = 10.)'),
  ('The perimeter of a rectangle is 54 cm. Its length is 3 cm more than twice its width. What is the width?', '["6 cm", "8 cm", "19 cm", "11 cm"]'::JSONB, 1, 3, 'Let w be the width, so the length is 2w + 3. Perimeter: 2(w + 2w + 3) = 54, so 3w + 3 = 27, 3w = 24, w = 8 cm. (The length, 19 cm, is the trap answer.)'),
  ('If 1/x + 1/6 = 1/2, what is x?', '["3", "1/3", "4", "6"]'::JSONB, 0, 3, 'Subtract: 1/x = 1/2 − 1/6 = 3/6 − 1/6 = 2/6 = 1/3. If 1/x = 1/3 then x = 3.'),
  ('Factor completely: x² − 9', '["(x + 9)(x − 1)", "(x − 3)(x + 3)", "(x − 9)(x + 1)", "(x − 3)(x − 3)"]'::JSONB, 1, 2, 'This is a difference of two squares: x² − 3² = (x − 3)(x + 3). Checking, the middle terms −3x and +3x cancel.'),
  ('If 2ˣ = 32, what is x?', '["4", "5", "6", "16"]'::JSONB, 1, 2, 'Count the doublings: 2, 4, 8, 16, 32 — that is five factors of 2, so 2⁵ = 32 and x = 5.'),
  ('How many degrees are in a straight angle?', '["180°", "90°", "45°", "360°"]'::JSONB, 0, 1, 'A straight angle forms a straight line, which is half of a full 360° rotation: 180°.'),
  ('What is the perimeter of a rectangle with length 11 and width 4?', '["44", "30", "22", "15"]'::JSONB, 1, 1, 'Perimeter = 2(length + width) = 2(11 + 4) = 30. Multiplying instead (44) gives the area, not the perimeter.'),
  ('Each angle of an equilateral triangle measures how many degrees?', '["45°", "90°", "60°", "30°"]'::JSONB, 2, 1, 'All three angles are equal and a triangle''s angles total 180°, so each is 180 ÷ 3 = 60°.'),
  ('A regular hexagon has a perimeter of 48. What is the length of one side?', '["9", "6", "12", "8"]'::JSONB, 3, 1, 'A regular hexagon has 6 equal sides, so each side is 48 ÷ 6 = 8.'),
  ('A trapezoid has parallel sides of 8 and 12 and a height of 5. What is its area?', '["25", "50", "100", "60"]'::JSONB, 1, 2, 'Area = ((b₁ + b₂)/2) × h = ((8 + 12)/2) × 5 = 10 × 5 = 50. Forgetting to halve the bases gives 100.'),
  ('A parallelogram has a base of 9 and a height of 6. What is its area?', '["30", "54", "27", "15"]'::JSONB, 1, 2, 'Area of a parallelogram = base × height = 9 × 6 = 54. Halving it (27) would be the triangle formula.'),
  ('A circle has a radius of 7. What is its area? (Use π ≈ 22/7)', '["44", "154", "308", "77"]'::JSONB, 1, 2, 'Area = πr² = (22/7) × 7² = (22/7) × 49 = 154. The value 44 is the circumference, not the area.'),
  ('A cube has a volume of 125 cm³. What is the length of one edge?', '["12.5 cm", "25 cm", "5 cm", "15 cm"]'::JSONB, 2, 2, 'Volume of a cube = s³, so s = ∛125 = 5 cm because 5 × 5 × 5 = 125.'),
  ('A cylinder has a diameter of 10 and a height of 7. What is its volume? (Use π ≈ 3.14)', '["219.8", "109.9", "2,198", "549.5"]'::JSONB, 3, 3, 'The radius is half the diameter: r = 5. Volume = πr²h = 3.14 × 25 × 7 = 549.5. Using the diameter as the radius gives 2,198.'),
  ('The area of a square is 50 square units. What is the length of its diagonal?', '["25 units", "10 units", "About 7.1 units", "About 14.1 units"]'::JSONB, 1, 3, 'The side is √50. By the Pythagorean theorem the diagonal is √(50 + 50) = √100 = 10 units. (About 7.1 is the side length itself.)'),
  ('An isosceles triangle has two equal sides of 13 and a base of 10. What is the height drawn to the base?', '["11", "8", "12", "6.5"]'::JSONB, 2, 3, 'The height bisects the base, forming a right triangle with hypotenuse 13 and one leg 5. The height is √(169 − 25) = √144 = 12.'),
  ('What is the total surface area of a rectangular prism with dimensions 3, 4, and 5?', '["47", "120", "94", "60"]'::JSONB, 2, 3, 'Surface area = 2(lw + lh + wh) = 2(3×4 + 3×5 + 4×5) = 2(12 + 15 + 20) = 94. The value 60 is the volume; 47 is the sum of the three faces without doubling.'),
  ('How many centimeters are in 2.5 meters?', '["2,500 cm", "25 cm", "250 cm", "0.025 cm"]'::JSONB, 2, 1, 'There are 100 centimeters in a meter, so 2.5 × 100 = 250 cm.'),
  ('How many ounces are in 3 pounds?', '["30", "48", "16", "36"]'::JSONB, 1, 1, 'One pound is 16 ounces, so 3 × 16 = 48 ounces. Using 12 per pound (as with inches) gives the trap answer 36.'),
  ('A bag contains 3 red marbles and 5 blue marbles. What is the probability of drawing a red marble at random?', '["5/8", "3/5", "3/8", "1/3"]'::JSONB, 2, 1, 'There are 3 + 5 = 8 marbles total, and 3 are red, so the probability is 3/8. Using 3/5 compares red to blue instead of to the total.'),
  ('A recipe calls for 3 quarts of water. How many cups is that? (1 quart = 4 cups)', '["8 cups", "6 cups", "16 cups", "12 cups"]'::JSONB, 3, 1, 'Multiply because cups are the smaller unit: 3 × 4 = 12 cups.'),
  ('A standard six-sided die is rolled once. What is the probability of rolling a number greater than 4?', '["2/3", "1/6", "1/2", "1/3"]'::JSONB, 3, 2, 'Only 5 and 6 are greater than 4, so 2 of 6 outcomes work: 2/6 = 1/3. Counting 4 itself would give 1/2.'),
  ('Two fair coins are flipped. What is the probability that both land heads?', '["1/2", "3/4", "1/4", "1/3"]'::JSONB, 2, 2, 'The four equally likely outcomes are HH, HT, TH, TT, so P(both heads) = 1/4. You can also multiply: 1/2 × 1/2 = 1/4.'),
  ('In a survey of 60 students, 25 chose soccer, 15 chose basketball, and 12 chose swimming. The rest chose tennis. How many chose tennis?', '["10", "8", "5", "12"]'::JSONB, 1, 2, 'Add the listed choices: 25 + 15 + 12 = 52. Then 60 − 52 = 8 students chose tennis.'),
  ('A circle graph summarizes 200 survey responses. The section for Option A represents 45% of the graph. How many people chose Option A?', '["45", "90", "80", "110"]'::JSONB, 1, 2, '45% of 200 = 0.45 × 200 = 90 people. The value 45 is the percent, not the count.'),
  ('A spinner has 8 equal sections numbered 1 through 8. What is the probability of landing on a prime number?', '["1/4", "3/8", "5/8", "1/2"]'::JSONB, 3, 2, 'The primes from 1 to 8 are 2, 3, 5, and 7 — four of them (1 is not prime). So the probability is 4/8 = 1/2.'),
  ('A bag holds 4 red and 6 green marbles. Two are drawn without replacement. What is the probability that both are red?', '["1/6", "2/15", "2/5", "4/25"]'::JSONB, 1, 3, 'P(first red) = 4/10. After removing one red, P(second red) = 3/9. Multiply: (4/10)(3/9) = 12/90 = 2/15. Using 4/10 twice (with replacement) gives 4/25.'),
  ('How many square feet are in 2 square yards?', '["9", "6", "36", "18"]'::JSONB, 3, 3, 'A square yard is 3 ft × 3 ft = 9 square feet, so 2 square yards = 18 square feet. Multiplying by 3 instead of 9 gives the trap answer 6.'),
  ('A car travels 90 kilometers in 1.5 hours. What is its speed in meters per second?', '["About 16.7 m/s", "About 1.5 m/s", "About 60 m/s", "About 25 m/s"]'::JSONB, 0, 3, 'Speed = 90 ÷ 1.5 = 60 km/h. Convert: 60 km = 60,000 m and 1 hour = 3,600 s, so 60,000 ÷ 3,600 ≈ 16.7 m/s.'),
  ('A book club read 8 books in 4 months at a steady rate. At that rate, how many books will it read in 10 months?', '["16", "14", "24", "20"]'::JSONB, 3, 1, 'The rate is 8 ÷ 4 = 2 books per month, so 10 months gives 2 × 10 = 20 books.'),
  ('A movie starts at 6:45 p.m. and runs for 1 hour and 50 minutes. What time does it end?', '["7:35 p.m.", "8:35 p.m.", "8:25 p.m.", "8:45 p.m."]'::JSONB, 1, 1, '6:45 plus 1 hour is 7:45. Adding 50 more minutes: 7:45 + 15 = 8:00, then 35 more minutes gives 8:35 p.m.'),
  ('A phone that normally costs $450 is discounted 30%. A $15 case is then added to the purchase. What is the total cost?', '["$330", "$135", "$345", "$300"]'::JSONB, 0, 3, 'The discount is 0.30 × $450 = $135, so the phone costs $450 − $135 = $315. Adding the case: $315 + $15 = $330. ($135 is the discount itself, not the price.)'),
  ('How much simple interest does $800 earn in 3 years at an annual rate of 5%?', '["$120", "$920", "$40", "$1,200"]'::JSONB, 0, 2, 'Simple interest = principal × rate × time = $800 × 0.05 × 3 = $120. ($40 is only one year''s interest; $920 is the total balance.)'),
  ('A worker earns $16 per hour for the first 40 hours of a week and time-and-a-half for every hour beyond that. If she works 46 hours, what is her total pay?', '["$828", "$736", "$640", "$784"]'::JSONB, 3, 3, 'Regular pay: 40 × $16 = $640. Overtime rate is 1.5 × $16 = $24 for 6 hours = $144. Total: $640 + $144 = $784. ($736 comes from paying all 46 hours at $16.)'),
  ('Two trains leave the same station at the same time traveling in opposite directions, one at 60 mph and the other at 75 mph. How long until they are 405 miles apart?', '["3 hours", "4 hours", "2.7 hours", "3.5 hours"]'::JSONB, 0, 3, 'Moving apart, their speeds add: 60 + 75 = 135 mph. Time = 405 ÷ 135 = 3 hours.'),
  ('A tank is 3/5 full. After 42 gallons are added, it is 4/5 full. What is the tank''s total capacity?', '["105 gallons", "350 gallons", "210 gallons", "168 gallons"]'::JSONB, 2, 3, 'The 42 gallons filled 4/5 − 3/5 = 1/5 of the tank, so the full capacity is 5 × 42 = 210 gallons.')
)
INSERT INTO questions (id, section, passage, prompt, options, correct_index, difficulty, explanation)
SELECT md5('math' || '|' || q.prompt)::UUID, 'math'::section_type, NULL,
       q.prompt, q.options, q.correct_index, q.difficulty, q.explanation
FROM q
ON CONFLICT (id) DO NOTHING;

-- ── Verification: expected 57 rows ──────────────────────────────────
SELECT '023 math' AS migration, COUNT(*) AS present, 57 AS expected
FROM questions
WHERE id IN (
  md5('math' || '|' || 'What is 7 × 0.4?')::UUID,
  md5('math' || '|' || 'Which of these decimals is the largest?')::UUID,
  md5('math' || '|' || 'What is 1/3 of 27?')::UUID,
  md5('math' || '|' || 'Write 3/5 as a percent.')::UUID,
  md5('math' || '|' || 'What is 6.4 ÷ 0.8?')::UUID,
  md5('math' || '|' || 'What is 2 1/2 + 1 3/4?')::UUID,
  md5('math' || '|' || 'The ratio of boys to girls in a class is 4:5. If there are 36 students in all, how many are girls?')::UUID,
  md5('math' || '|' || 'If 3 notebooks cost $4.50, how much do 7 notebooks cost at the same rate?')::UUID,
  md5('math' || '|' || 'Evaluate: −6 + 4 × (−3) − (−5)')::UUID,
  md5('math' || '|' || 'What is 0.6 expressed as a fraction in lowest terms?')::UUID,
  md5('math' || '|' || 'Express 0.000045 in scientific notation.')::UUID,
  md5('math' || '|' || 'Evaluate: (3⁴ × 3²) ÷ 3⁵')::UUID,
  md5('math' || '|' || 'What is 12.5% of 320?')::UUID,
  md5('math' || '|' || 'Simplify: 5x + 3x − 2x')::UUID,
  md5('math' || '|' || 'If y = 3x − 4, what is y when x = 5?')::UUID,
  md5('math' || '|' || 'If x + 12 = 5, what is x?')::UUID,
  md5('math' || '|' || 'Simplify: 3(2x − 4) + 5x')::UUID,
  md5('math' || '|' || 'Solve for x: (x − 3)/5 = 4')::UUID,
  md5('math' || '|' || 'Solve for x: −3x + 7 = 22')::UUID,
  md5('math' || '|' || 'What is the value of 2a² − b when a = 3 and b = 5?')::UUID,
  md5('math' || '|' || 'Solve the inequality: 5 − 2x < 11')::UUID,
  md5('math' || '|' || 'If 3(x + 2) − 2(x − 1) = 14, what is x?')::UUID,
  md5('math' || '|' || 'The perimeter of a rectangle is 54 cm. Its length is 3 cm more than twice its width. What is the width?')::UUID,
  md5('math' || '|' || 'If 1/x + 1/6 = 1/2, what is x?')::UUID,
  md5('math' || '|' || 'Factor completely: x² − 9')::UUID,
  md5('math' || '|' || 'If 2ˣ = 32, what is x?')::UUID,
  md5('math' || '|' || 'How many degrees are in a straight angle?')::UUID,
  md5('math' || '|' || 'What is the perimeter of a rectangle with length 11 and width 4?')::UUID,
  md5('math' || '|' || 'Each angle of an equilateral triangle measures how many degrees?')::UUID,
  md5('math' || '|' || 'A regular hexagon has a perimeter of 48. What is the length of one side?')::UUID,
  md5('math' || '|' || 'A trapezoid has parallel sides of 8 and 12 and a height of 5. What is its area?')::UUID,
  md5('math' || '|' || 'A parallelogram has a base of 9 and a height of 6. What is its area?')::UUID,
  md5('math' || '|' || 'A circle has a radius of 7. What is its area? (Use π ≈ 22/7)')::UUID,
  md5('math' || '|' || 'A cube has a volume of 125 cm³. What is the length of one edge?')::UUID,
  md5('math' || '|' || 'A cylinder has a diameter of 10 and a height of 7. What is its volume? (Use π ≈ 3.14)')::UUID,
  md5('math' || '|' || 'The area of a square is 50 square units. What is the length of its diagonal?')::UUID,
  md5('math' || '|' || 'An isosceles triangle has two equal sides of 13 and a base of 10. What is the height drawn to the base?')::UUID,
  md5('math' || '|' || 'What is the total surface area of a rectangular prism with dimensions 3, 4, and 5?')::UUID,
  md5('math' || '|' || 'How many centimeters are in 2.5 meters?')::UUID,
  md5('math' || '|' || 'How many ounces are in 3 pounds?')::UUID,
  md5('math' || '|' || 'A bag contains 3 red marbles and 5 blue marbles. What is the probability of drawing a red marble at random?')::UUID,
  md5('math' || '|' || 'A recipe calls for 3 quarts of water. How many cups is that? (1 quart = 4 cups)')::UUID,
  md5('math' || '|' || 'A standard six-sided die is rolled once. What is the probability of rolling a number greater than 4?')::UUID,
  md5('math' || '|' || 'Two fair coins are flipped. What is the probability that both land heads?')::UUID,
  md5('math' || '|' || 'In a survey of 60 students, 25 chose soccer, 15 chose basketball, and 12 chose swimming. The rest chose tennis. How many chose tennis?')::UUID,
  md5('math' || '|' || 'A circle graph summarizes 200 survey responses. The section for Option A represents 45% of the graph. How many people chose Option A?')::UUID,
  md5('math' || '|' || 'A spinner has 8 equal sections numbered 1 through 8. What is the probability of landing on a prime number?')::UUID,
  md5('math' || '|' || 'A bag holds 4 red and 6 green marbles. Two are drawn without replacement. What is the probability that both are red?')::UUID,
  md5('math' || '|' || 'How many square feet are in 2 square yards?')::UUID,
  md5('math' || '|' || 'A car travels 90 kilometers in 1.5 hours. What is its speed in meters per second?')::UUID,
  md5('math' || '|' || 'A book club read 8 books in 4 months at a steady rate. At that rate, how many books will it read in 10 months?')::UUID,
  md5('math' || '|' || 'A movie starts at 6:45 p.m. and runs for 1 hour and 50 minutes. What time does it end?')::UUID,
  md5('math' || '|' || 'A phone that normally costs $450 is discounted 30%. A $15 case is then added to the purchase. What is the total cost?')::UUID,
  md5('math' || '|' || 'How much simple interest does $800 earn in 3 years at an annual rate of 5%?')::UUID,
  md5('math' || '|' || 'A worker earns $16 per hour for the first 40 hours of a week and time-and-a-half for every hour beyond that. If she works 46 hours, what is her total pay?')::UUID,
  md5('math' || '|' || 'Two trains leave the same station at the same time traveling in opposite directions, one at 60 mph and the other at 75 mph. How long until they are 405 miles apart?')::UUID,
  md5('math' || '|' || 'A tank is 3/5 full. After 42 gallons are added, it is 4/5 full. What is the tank''s total capacity?')::UUID
);
