-- 033 — Deepen 25 reading passages to full HSPT length
--
-- ⚠️ MUST RUN AFTER 032. Four of these passages carry questions that 032
-- rewords off sentence position ("in the final sentence", "at the end of the
-- passage"). Appending a paragraph before 032 has run leaves those stems
-- asserting something that is no longer true.
--
-- Each passage below is 83-127 words — well under the 200-250 words a real
-- HSPT reading passage runs. Every one is extended by APPENDING paragraphs;
-- the original text survives verbatim as the opening paragraph, so every
-- existing answer key and explanation still quotes text that is present.
--
-- Constraints obeyed:
--   * `passage` is the only column written. No prompt, options, correct_index,
--     explanation, difficulty, section, id or passage_title is touched (030 set
--     the titles and they remain correct), and no attempt or answer-history row
--     is read or written anywhere in this file.
--   * One UPDATE per passage, matched on a fragment of the ORIGINAL text, so
--     every row sharing that passage is rewritten identically and the app keeps
--     grouping them as a single passage.
--   * Every WHERE fragment was verified to match exactly one distinct passage
--     across the whole live corpus, contains no % or _ that LIKE would read as
--     a wildcard, and was checked against the LIVE text (i.e. with migration
--     018's two factual edits already applied).
--   * A NOT LIKE guard on a phrase from the ADDED text makes each statement
--     idempotent — re-running appends nothing.
--
-- SCORING: no student can gain or lose a point. Points come from
-- user_question_history joined to questions on id, valued by difficulty;
-- neither is touched here.

-- ── 1. How the Water Cycle Works ── 102 → 224 words
UPDATE questions SET passage = 'Water is constantly moving through Earth''s systems in a never-ending process called the water cycle. Energy from the sun causes water in oceans, lakes, and rivers to evaporate, turning liquid water into water vapor that rises into the atmosphere. As the vapor rises, it cools and condenses into tiny droplets, forming clouds. When enough droplets combine, precipitation falls as rain or snow. This water then flows into rivers, soaks into the ground, or collects in lakes — and the cycle begins again. The water cycle not only replenishes freshwater supplies but also helps regulate temperature and drive weather patterns around the globe.

The cycle does not move all water at the same speed. A molecule that evaporates from the ocean usually spends only about nine days in the atmosphere before falling again as precipitation. Water that soaks deep underground, by contrast, may sit in an aquifer for thousands of years before it returns to the surface. Ice behaves much the same way: water frozen into a glacier can stay locked in place for centuries. Most of Earth''s water is held in oceans and in ice rather than in rivers and lakes, so only a small share of it is available as fresh liquid water at any given moment. The cycle never stops, but its pace varies enormously from one storage place to the next.'
  WHERE section = 'reading'
    AND passage LIKE '%systems in a never-ending process called the%'
    AND passage NOT LIKE '%speed. A molecule that evaporates%';

-- ── 2. The History of Sign Language ── 105 → 222 words
UPDATE questions SET passage = 'Sign language is a complete, complex language expressed through hand movements, facial expressions, and body posture rather than spoken words. Although deaf communities around the world have always developed informal signing systems, the first formal sign language school was established in Paris in 1760 by Abbé de l''Épée. His school later influenced American Sign Language (ASL) when a French teacher named Laurent Clerc traveled to the United States in 1817 to help found the American School for the Deaf in Hartford, Connecticut. Today, linguists recognize that sign languages are fully independent languages with their own grammar and syntax, not simply coded versions of spoken language.

Because each signing community shapes its own language, sign languages differ from one another about as much as spoken languages do. British Sign Language and American Sign Language are not mutually intelligible, even though both are used in countries where English is spoken; a signer from London and a signer from Chicago often cannot follow each other. Sign languages also use grammatical tools that speech cannot easily copy. A signer can place a person or object at a particular spot in the space in front of the body and then point back to that spot later to refer to it again, and can carry several pieces of information at once through handshape, movement, and facial expression together.'
  WHERE section = 'reading'
    AND passage LIKE '%Sign language is a complete, complex language%'
    AND passage NOT LIKE '%Because each signing community shapes%';

-- ── 3. The Roots of Jazz ── 105 → 220 words
UPDATE questions SET passage = 'Jazz is a uniquely American art form that grew out of the vibrant African American communities of New Orleans in the late 1800s and early 1900s. It blends elements of African rhythmic traditions, blues, gospel, and European harmonic structures into an improvisational style unlike anything before it. Early jazz musicians played in venues called "juke joints" and at community celebrations, often creating music on the spot rather than reading from written scores. Jazz spread rapidly up the Mississippi River to Chicago and then to New York, where it flourished during the Harlem Renaissance. Today, jazz is recognized worldwide as one of America''s greatest cultural contributions.

Jazz never settled into one fixed style. In the 1920s and 1930s, as more players moved north during the Great Migration, bands grew larger and swing filled dance halls with arranged parts written for whole sections of horns. In the 1940s, younger musicians such as Charlie Parker and Dizzy Gillespie pushed back toward small groups, faster tempos, and harmonies that were much harder to dance to — a style that came to be called bebop. Later players stretched the music further still, borrowing from Latin, rock, and classical traditions. Each of these shifts drew complaints from listeners who preferred the older sound, yet that willingness to change is part of what has kept jazz alive.'
  WHERE section = 'reading'
    AND passage LIKE '%Jazz is a uniquely American art form%'
    AND passage NOT LIKE '%more players moved north during%';

-- ── 4. Writing in Ancient Mesopotamia ── 106 → 227 words
UPDATE questions SET passage = 'More than 5,000 years ago, people in ancient Mesopotamia — the region between the Tigris and Euphrates rivers — developed one of the world''s earliest writing systems, known as cuneiform. Early scribes pressed a wedge-shaped reed stylus into soft clay tablets to create marks representing words and numbers. At first, cuneiform was used almost exclusively to keep economic records: tracking grain, livestock, and trade goods. Over centuries, the system expanded to record laws, stories, religious texts, and royal decrees. The famous Epic of Gilgamesh, one of the oldest surviving works of literature, was preserved on cuneiform tablets and tells the story of a legendary Mesopotamian king.

Cuneiform outlasted the people who invented it. Later groups, including the Akkadians and the Hittites, borrowed the wedge-shaped signs to write their own languages, which were unrelated to each other. Clay turned out to be an unusually tough material as well: a fire that would have destroyed papyrus only baked the tablets harder, so enormous numbers of them survived underground to be dug up later. For a long stretch of history, though, no one alive could read them. Scholars in the 1800s finally broke the script by studying an inscription carved high on a cliff in Persia, which repeated the same royal announcement in three languages, one of them already partly understood. Museums still hold tablets that no one has translated.'
  WHERE section = 'reading'
    AND passage LIKE '%More than 5,000 years ago, people in%'
    AND passage NOT LIKE '%Cuneiform outlasted the people who%';

-- ── 5. The Brain During Sleep ── 106 → 218 words
UPDATE questions SET passage = 'Sleep is far more than simply resting. While the body is still, the brain remains remarkably active, performing critical maintenance work. During deep sleep, the brain consolidates memories — transferring information from short-term to long-term storage. It also clears out waste products that build up during waking hours, including proteins linked to neurological diseases. During a phase called REM sleep, the brain processes emotions and may generate dreams. Sleep deprivation disrupts all of these processes, impairing memory, judgment, and emotional regulation. Scientists now understand that adequate sleep — typically eight to ten hours for teenagers — is not optional but essential for brain and body health.

Getting that sleep is harder for teenagers than it sounds. During adolescence the body''s internal clock shifts: the brain starts releasing melatonin, the hormone that signals sleepiness, later in the evening than it did in childhood. A teenager still wide awake late at night is often not being stubborn but following biology. Bright light from screens can push that signal back even further. Because school still begins early, the shortfall builds up night after night across the week, and sleeping late on Saturday does not fully undo it. Some school districts have responded by moving their start times later, and researchers who study those districts report improvements in student attendance and alertness.'
  WHERE section = 'reading'
    AND passage LIKE '%Sleep is far more than simply resting.%'
    AND passage NOT LIKE '%teenagers than it sounds. During%';

-- ── 6. The Olympic Games Through Time ── 107 → 232 words
UPDATE questions SET passage = 'The Olympic Games, now a global sporting celebration held every four years, began in ancient Greece. The first recorded Games took place in 776 BCE in the city of Olympia, in honor of the god Zeus. Initially, the competition included only a single footrace. Over time, events like wrestling, chariot racing, and the discus throw were added. Athletes came from city-states across Greece, and a truce was declared during the Games so that competitors could travel safely. The modern Olympics were revived in Athens in 1896, inspired by the ancient tradition, and have since grown to include hundreds of sports and thousands of athletes from every nation.

The modern revival was largely the work of Pierre de Coubertin, a French educator who believed that international competition could build understanding between nations. The 1896 Athens Games were modest by today''s standards: roughly 240 athletes, all of them men, representing about 14 nations. Women first competed four years later, at the Paris Games of 1900. A separate Winter Olympics was added in 1924, and for decades it was held in the same year as the Summer Games; since 1994 the two have been staggered, so that each still occurs every four years but an Olympics arrives every two. What began as a single race on a field in Greece now asks host cities to plan and build for the better part of a decade.'
  WHERE section = 'reading'
    AND passage LIKE '%The Olympic Games, now a global sporting%'
    AND passage NOT LIKE '%The modern revival was largely%';

-- ── 7. From ARPANET to the Web ── 107 → 223 words
UPDATE questions SET passage = 'The internet we use today grew from a much smaller network created in 1969 called ARPANET, funded by the United States Department of Defense. ARPANET connected computers at a handful of universities and research labs, allowing scientists to share data across long distances for the first time. Over the following decades, the network expanded and the rules governing how computers communicate — called protocols — were standardized. In 1991, scientist Tim Berners-Lee invented the World Wide Web, a system of linked pages that made the internet far easier for ordinary people to navigate. Today, billions of people use the internet daily for communication, commerce, education, and entertainment.

That growth depended on something easy to overlook: no one owns the rules. The protocols are published openly, and in 1993 the European physics laboratory where Berners-Lee worked placed the software for the World Wide Web in the public domain, free for anyone to use. Any company could then write its own browser or run its own server, so long as it followed the shared standards. Access, however, has never been equal. The International Telecommunication Union estimates that about a third of the world''s people have still never been online, most of them in lower-income countries where service costs too much or networks do not reach. The network that connects billions has not yet connected everyone.'
  WHERE section = 'reading'
    AND passage LIKE '%The internet we use today grew from%'
    AND passage NOT LIKE '%That growth depended on something%';

-- ── 8. How Vaccines Work ── 108 → 232 words
UPDATE questions SET passage = 'Vaccines work by training the immune system to recognize and defeat specific pathogens before a real infection occurs. When a vaccine is administered, it introduces a harmless version of a pathogen — such as a weakened or inactivated virus, or just a piece of its protein — into the body. The immune system detects this foreign material and produces antibodies, proteins designed to neutralize that specific threat. If the person later encounters the real pathogen, the immune system "remembers" it and responds rapidly, often stopping the disease before symptoms develop. This principle, called immunological memory, is what makes vaccination one of the most powerful tools in public health.

Vaccination also protects people who are not vaccinated. When enough of a community is immune, a pathogen struggles to find new hosts and outbreaks fizzle out, which shields infants too young for their shots and patients whose illnesses or medical treatments make vaccination unsafe for them. The threshold varies by disease: measles spreads so easily that roughly 95 percent of a population must be immune to keep it from circulating. That is why coverage across a whole community matters, not only what any one family decides. The clearest evidence of what widespread vaccination can accomplish is smallpox, a disease that killed millions for centuries; after a worldwide campaign, the World Health Organization declared it eradicated in 1980, and no natural case has occurred since.'
  WHERE section = 'reading'
    AND passage LIKE '%Vaccines work by training the immune system%'
    AND passage NOT LIKE '%Vaccination also protects people who%';

-- ── 9. Bell and the Telephone ── 108 → 223 words
UPDATE questions SET passage = 'The invention of the telephone in 1876 transformed human communication forever. Alexander Graham Bell, a Scottish-born inventor working in Boston, is credited with creating the first practical telephone and receiving the first patent for the device. Bell''s inspiration came partly from his work with deaf students and his interest in understanding how sound travels. His first successful telephone call was made to his assistant, Thomas Watson, with the now-famous words: "Mr. Watson — come here — I want to see you." Although other inventors were working on similar devices at the same time, Bell filed his patent just hours before a competing inventor, securing his place in history.

The patent Bell received, number 174,465, has been called one of the most valuable ever granted, and it was fought over for years. Rival claimants insisted that they had reached the idea first, and Bell''s company was pulled into hundreds of lawsuits defending its rights. It won every one of them. In 1888 the Supreme Court upheld Bell''s patents, settling the question of ownership in his favor. That protection did not last forever. The patent expired in 1893, and independent companies rushed into a business Bell''s firm had held almost alone. The courtroom, as much as the workbench, decided who profited from the telephone, and it shows what a single filing date can be worth.'
  WHERE section = 'reading'
    AND passage LIKE '%The invention of the telephone in 1876%'
    AND passage NOT LIKE '%The patent Bell received, number%';

-- ── 10. How Antibiotics Fight Bacteria ── 108 → 230 words
UPDATE questions SET passage = 'Antibiotics are medicines that fight bacterial infections by targeting features of bacteria that human cells do not have. Some antibiotics work by disrupting the construction of a bacterium''s cell wall — without a protective wall, the bacterium bursts and dies. Others interfere with the bacteria''s ability to copy their genetic material or produce essential proteins, effectively stopping reproduction. Antibiotics do not work against viruses, which is why doctors do not prescribe them for colds or the flu. Overusing antibiotics has led to a growing problem called antibiotic resistance, in which bacteria evolve to survive the drugs that once killed them — a serious threat to public health worldwide.

Resistance is not a surprise; it is evolution running on a very fast clock. Bacteria can divide every twenty minutes or so, and in a population of billions a few cells almost always carry a mutation that blunts a drug''s effect. When antibiotics are used carelessly, the vulnerable bacteria die and those few survivors inherit the field, passing the trait to their descendants. It is the bacteria that change, not the patient. Alexander Fleming, who discovered penicillin in 1928, warned of exactly this in his 1945 Nobel lecture, cautioning that doses too small to kill microbes would instead teach them to survive. Within a few years of penicillin''s wide use, hospitals were already meeting staph infections the drug could no longer touch.'
  WHERE section = 'reading'
    AND passage LIKE '%Antibiotics are medicines that fight bacterial infections%'
    AND passage NOT LIKE '%surprise; it is evolution running%';

-- ── 11. The Urban Heat Island ── 109 → 226 words
UPDATE questions SET passage = 'Cities are often several degrees warmer than the rural areas surrounding them — a phenomenon scientists call the urban heat island effect. This happens because buildings, roads, and parking lots absorb and store heat from the sun during the day and release it slowly at night, whereas natural surfaces like grass and soil reflect more heat and cool more quickly. Dark-colored materials such as asphalt absorb especially large amounts of solar energy. Additionally, vehicles, air conditioners, and industrial equipment generate heat directly. The urban heat island effect can raise energy costs, worsen air quality, and increase the risk of heat-related illness, particularly for vulnerable populations during summer heat waves.

The effect is not spread evenly within a city. Researchers who measure temperatures block by block on the same summer afternoon find that neighborhoods shaded by mature trees stay noticeably cooler than nearby blocks where pavement and rooftops dominate. Because tree cover tends to follow old patterns of investment, the hottest blocks are often the ones whose residents have the fewest resources for coping with heat, including older adults and people with chronic illnesses. Some cities have responded by coating roofs with reflective paint, planting street trees, and adding small shaded parks. These measures do work, but they work slowly: a newly planted tree may need fifteen years of growth before its canopy shades much of anything.'
  WHERE section = 'reading'
    AND passage LIKE '%Cities are often several degrees warmer than%'
    AND passage NOT LIKE '%evenly within a city. Researchers%';

-- ── 12. Supply, Demand, and Prices ── 114 → 231 words
UPDATE questions SET passage = 'The law of supply and demand is one of the most fundamental principles in economics. When a product is in high demand but supply is limited, sellers can charge higher prices because buyers are competing for a scarce resource. When supply is plentiful but demand is low, prices tend to fall as sellers compete to attract buyers. The point where the quantity sellers want to sell equals the quantity buyers want to buy is called the equilibrium price. In the real world, prices shift constantly as supply and demand change — a drought that reduces the wheat harvest, for example, raises bread prices, while a new technology that makes production cheaper can lower them.

The rule has limits, however, because buyers do not react to a price change the same way for every product. When the price of a necessity such as household electricity or a prescription medicine rises, most families keep buying nearly as much as before, since there is no easy substitute; economists call this kind of demand inelastic. For an optional purchase such as a restaurant dinner or a concert ticket, the same price increase can send sales sharply lower. Expectations matter as well. If buyers believe a price is about to climb, many will rush to buy immediately, and that rush raises demand today and pushes the price up before the shortage they feared has actually arrived.'
  WHERE section = 'reading'
    AND passage LIKE '%The law of supply and demand is%'
    AND passage NOT LIKE '%rule has limits, however, because%';

-- ── 13. Life on Coral Reefs ── 114 → 231 words
UPDATE questions SET passage = 'Coral reefs are often called the "rainforests of the sea" because they support an extraordinary diversity of life despite covering less than one percent of the ocean floor. Reef-building corals are tiny animals that live in partnership with algae, which provide the corals with energy through photosynthesis. The hard calcium carbonate skeletons that corals build over thousands of years create a complex habitat where thousands of fish and invertebrate species find food and shelter. Reefs also protect coastlines from storm waves and support fishing industries worth billions of dollars worldwide. Rising ocean temperatures caused by climate change cause "coral bleaching," in which stressed corals expel their algae and may die, threatening the entire ecosystem.

Bleaching is not always the end of the story. If the water cools again within a few weeks, surviving corals can take in new algae and slowly resume growing. What has changed is how often the heat arrives. Marine heat waves that once struck a given reef decades apart now return within a few years, and many reef-building corals add only about a centimeter of skeleton in a year, so a damaged reef needs a long stretch of calm, cool water before it can rebuild what it lost. Researchers have responded by growing coral fragments in underwater nurseries and by breeding corals from unusually heat-tolerant parents, though these projects so far cover only small sections of reef.'
  WHERE section = 'reading'
    AND passage LIKE '%Coral reefs are often called the "rainforests%'
    AND passage NOT LIKE '%few weeks, surviving corals can%';

-- ── 14. How the Eye Sees Color ── 115 → 236 words
UPDATE questions SET passage = 'The human eye can distinguish millions of colors, but the actual process of color vision begins with specialized cells called cones, located in the retina at the back of the eye. There are three types of cones, each most sensitive to a different wavelength of light: one type responds mainly to red light, one to green, and one to blue. When light enters the eye, the cones detect these wavelengths and send electrical signals to the brain, which combines the signals to produce the full range of colors we perceive. People who are colorblind are typically missing one type of cone or have cones that do not function normally, causing them to confuse certain colors.

Cones, however, need a fair amount of light to do their work. In dim conditions the eye relies mostly on rods, a second kind of cell in the retina that is far more sensitive to faint light but cannot distinguish wavelengths at all. That is why a room lit only by moonlight appears gray: the objects in it still reflect exactly the same wavelengths they did at noon, but the cells reporting to the brain no longer separate one wavelength from another. The three-cone arrangement is also not the only one possible. Many birds carry a fourth type of cone that responds to ultraviolet light, so markings on feathers and flowers that are invisible to us stand out plainly to them.'
  WHERE section = 'reading'
    AND passage LIKE '%The human eye can distinguish millions of%'
    AND passage NOT LIKE '%conditions the eye relies mostly%';

-- ── 15. Why Birds Migrate ── 115 → 231 words
UPDATE questions SET passage = 'Every autumn, millions of birds across the world undertake remarkable journeys, traveling hundreds or thousands of miles to reach warmer climates where food remains available. Unlike most behaviors, bird migration appears to be triggered not by cold temperatures directly, but by changes in day length — called photoperiod — which signals the approaching season. Birds navigate using a combination of the sun''s position, star patterns at night, Earth''s magnetic field, and familiar landmarks. Many species return to the same nesting grounds year after year with extraordinary precision. Scientists are still studying exactly how birds integrate all of these navigational cues, but it is clear that migration is a finely tuned biological response to environmental change.

Tracking individual birds has become far easier as tags have shrunk. Lightweight geolocators and light-sensing geolocators now weigh less than a gram, and they have revealed journeys that earlier researchers could only guess at. Bar-tailed godwits, shorebirds that nest in Alaska, fly to New Zealand across open ocean without landing once — more than seven thousand miles in a little over a week, with no chance to feed or rest along the way. Before leaving, a godwit nearly doubles its weight in stored fat, and its digestive organs shrink to save weight for the crossing. A flight like that cannot be improvised. The preparation has to begin weeks ahead, while conditions at home are still comfortable.'
  WHERE section = 'reading'
    AND passage LIKE '%Every autumn, millions of birds across the%'
    AND passage NOT LIKE '%Tracking individual birds has become%';

-- ── 16. How the Brain Reads Color ── 116 → 238 words
UPDATE questions SET passage = 'Color is not just a feature of the physical world — it is a creation of the mind. When light strikes an object, the object absorbs some wavelengths and reflects others. The reflected wavelengths reach our eyes and are interpreted by the brain as color. Because the brain also uses context to make sense of color, two identical colors can appear different depending on what surrounds them. This is why a gray square looks darker when placed on a white background than when placed on a black one. Marketers use this knowledge to influence behavior: studies show that red can increase excitement and urgency, blue is associated with trust and calm, and yellow draws attention quickly.

The brain''s reliance on context also explains why colors stay recognizable when the light changes. A sheet of paper looks white at noon and still looks white under a yellowish lamp at night, even though the light bouncing off it is very different in each case. The brain compares the paper with everything around it and corrects for the lighting, a habit so automatic that people rarely notice it. That same habit limits what a single color can do. Researchers who test color effects in a laboratory often find weaker results in real stores, where price tags, packaging, lighting, and shelf position all compete for a shopper''s attention. Color shapes a first impression, but it seldom decides a purchase on its own.'
  WHERE section = 'reading'
    AND passage LIKE '%Color is not just a feature of%'
    AND passage NOT LIKE '%reliance on context also explains%';

-- ── 17. Wayfinding Across the Pacific ── 118 → 236 words
UPDATE questions SET passage = 'Long before the invention of the compass or GPS, indigenous navigators of the Pacific Islands crossed thousands of miles of open ocean using only natural cues. By reading the stars — particularly the position and movement of key constellations — they could determine latitude and direction. They also studied ocean swells, which move in predictable patterns from distant wind sources, and used the feel of wave motion beneath their canoes to stay on course. The color of the water, cloud formations, and even the behavior of birds indicated the presence of nearby islands. This sophisticated system of wayfinding, passed down through oral tradition and practice, enabled Polynesian peoples to settle islands across a vast region of the Pacific.

By the twentieth century much of this knowledge had faded, and some outsiders argued that the islands must have been reached by accident, by canoes blown off course. In 1976 a group in Hawaii set out to test that claim. They built Hokule''a, a double-hulled voyaging canoe, and sailed it roughly 2,500 miles to Tahiti carrying no compass, no charts, and no modern instruments. The navigator was Mau Piailug, a master wayfinder from the island of Satawal and one of the few men still trained in the old methods. The voyage took about a month and arrived where it was aimed. Piailug later taught Hawaiian students, and the tradition he carried is practiced again across the Pacific today.'
  WHERE section = 'reading'
    AND passage LIKE '%Long before the invention of the compass%'
    AND passage NOT LIKE '%twentieth century much of this%';

-- ── 18. Tectonic Plates and Earthquakes ── 119 → 240 words
UPDATE questions SET passage = 'Earth''s outer layer is not a single solid shell but a patchwork of giant rocky slabs called tectonic plates. These plates fit together like pieces of a puzzle and move slowly — just centimeters per year — driven by heat rising from Earth''s interior. Where plates meet, tremendous forces build up over time. When the stress becomes too great, the plates suddenly slip or grind past one another, releasing energy in waves that shake the ground — an earthquake. Volcanoes also tend to form near plate boundaries, since magma can force its way to the surface along cracks between plates. Most of the world''s earthquakes and volcanoes occur along the "Ring of Fire," a zone encircling the Pacific Ocean.

Knowing why earthquakes happen has not made it possible to say when one will happen. Scientists can map faults, measure how fast the ground on each side is straining, and estimate the chance of a large quake in the next few decades, but they cannot name a day. With warning so limited, most protection comes from preparing in advance. Engineers design buildings that bend and sway instead of snapping, anchor them firmly to their foundations, and put flexible joints in gas and water lines. Communities practice drills so people know to drop and take cover. Where such steps have been taken, death tolls have fallen sharply; where older buildings are common, a quake of the same size can be far deadlier.'
  WHERE section = 'reading'
    AND passage LIKE '%outer layer is not a single solid%'
    AND passage NOT LIKE '%Knowing why earthquakes happen has%';

-- ── 19. How Memories Are Formed ── 119 → 239 words
UPDATE questions SET passage = 'Memory is not stored in a single location in the brain, but it begins in a region called the hippocampus. When we experience something new, the hippocampus helps encode the information by strengthening connections between neurons — the brain''s nerve cells. Initially, memories are fragile and can be disrupted. Over time, through a process called consolidation, memories are gradually transferred to the cerebral cortex, the brain''s outer layer, for long-term storage. Sleep plays a critical role in this process: during sleep, the brain replays recent experiences and strengthens the neural pathways that hold them. Strong emotional experiences tend to form more vivid and lasting memories because the amygdala — the brain''s emotional center — helps flag them as important.

Remembering, however, is not like opening a file. Each time a memory is recalled, the brain rebuilds it from pieces, and the rebuilt version can be shaped by what a person has learned or imagined since. In experiments, people who are asked leading questions after watching a filmed accident often report details that were never there, and they report them with confidence. Confidence and accuracy, it turns out, are only loosely related. This same flexibility has a useful side. Students who quiz themselves on material remember it better later than students who simply reread it, because pulling a memory out strengthens the path back to it. Rereading feels easier, which is one reason it remains the more popular study method.'
  WHERE section = 'reading'
    AND passage LIKE '%Memory is not stored in a single%'
    AND passage NOT LIKE '%Remembering, however, is not like%';

-- ── 20. How Sound Travels ── 121 → 240 words
UPDATE questions SET passage = 'Sound is a form of energy that travels as waves — but unlike light, it cannot travel through empty space. When an object vibrates, it pushes against nearby air molecules, creating areas of compression and expansion that ripple outward from the source. These pressure waves travel through the air — or through solids and liquids — until they reach the ear, where they cause the eardrum to vibrate. The brain interprets these vibrations as sound. The speed of sound depends on the medium it travels through: it moves faster through water than air, and faster through steel than water. The pitch of a sound is determined by the frequency of the waves — more waves per second produce a higher pitch.

Because sound bounces off surfaces and moves at a known speed, an echo can be used to measure distance. A ship''s sonar sends a pulse toward the seafloor and times how long the return takes; since sound travels about 1,500 meters per second in seawater, a four-second round trip means the bottom is roughly 3,000 meters down. Animals do the same with far more precision. A bat calls out in pulses too high for human ears and reads the returning echoes to find a moth in the dark, correcting its aim as the echoes change. Dolphins hunt this way in cloudy water. Nothing unusual is happening in these cases, only the ordinary behavior of pressure waves put to work.'
  WHERE section = 'reading'
    AND passage LIKE '%Sound is a form of energy that%'
    AND passage NOT LIKE '%Because sound bounces off surfaces%';

-- ── 21. The Life Cycle of Stars ── 127 → 235 words
UPDATE questions SET passage = 'Stars are not permanent fixtures in the sky — they are born, live for millions or billions of years, and eventually die. A star begins as a cloud of gas and dust called a nebula. Gravity pulls this material together, and when the core grows hot enough, nuclear fusion ignites and a star is born. For most of its life, a star burns hydrogen fuel. When the hydrogen runs out, the star expands into a red giant. Small stars like our sun will eventually shed their outer layers and leave behind a dense core called a white dwarf. Massive stars, however, end dramatically: they collapse and explode in a violent supernova, sometimes leaving behind an incredibly dense remnant called a neutron star or even a black hole.

These endings matter beyond astronomy. Hydrogen and helium have existed since the early universe, but nearly every heavier element was assembled inside stars. Fusion in stellar cores builds carbon, oxygen, and iron, and a supernova hurls that material outward at enormous speed, mixing it into the thin gas and dust between the stars. The calcium in a person''s bones and the oxygen in each breath were made this way, long before Earth existed. Such explosions are rare but unforgettable: in 1054, astronomers in China recorded a sudden light in the sky, visible in daylight for more than three weeks. The debris cloud it left is still expanding today.'
  WHERE section = 'reading'
    AND passage LIKE '%Stars are not permanent fixtures in the%'
    AND passage NOT LIKE '%These endings matter beyond astronomy.%';

-- ── 22. Cognitive Dissonance Explained ── 83 → 204 words
UPDATE questions SET passage = 'The term ''cognitive dissonance'' was introduced by psychologist Leon Festinger in 1957 to describe the discomfort people feel when they hold two conflicting beliefs simultaneously. Festinger proposed that this discomfort motivates individuals to reduce the inconsistency — either by changing one of their beliefs, acquiring new information that resolves the conflict, or minimizing the importance of one of the conflicting ideas. Advertisers and political campaigns have long understood this principle, designing messages that subtly shift audiences toward resolving dissonance in a preferred direction.

Festinger''s own experiments showed how strange this drive to resolve conflict can look. In one famous study, volunteers spent an hour on a dull, repetitive task and were then asked to tell the next participant that the work had been interesting. Some were paid twenty dollars for saying so; others were paid one. Those paid twenty dollars later admitted the task had been boring, while those paid one dollar reported that they had genuinely enjoyed it. The large payment gave an obvious outside reason for the lie, so no inconsistency arose. The small payment gave none, and the easiest way for those volunteers to square their words with their opinion was to decide that the task really had been worth doing.'
  WHERE section = 'reading'
    AND passage LIKE '%was introduced by psychologist Leon Festinger in%'
    AND passage NOT LIKE '%own experiments showed how strange%';

-- ── 23. Bees and Pollination ── 106 → 218 words
UPDATE questions SET passage = 'Bees are among the most important animals on Earth, not because of their honey but because of their role as pollinators. As bees travel from flower to flower collecting nectar, they transfer pollen, enabling plants to reproduce. This process, called pollination, is essential for the production of fruits, vegetables, nuts, and seeds that countless species — including humans — depend on for food. Scientists estimate that roughly one-third of the food humans eat relies on pollination. Habitat loss, pesticide use, and disease have caused bee populations to decline sharply in recent decades, alarming ecologists who warn that the loss of bees could trigger widespread food shortages.

Most people picture a honeybee hive, but honeybees are only one of roughly twenty thousand bee species, and the great majority live alone rather than in colonies, nesting in hollow stems or in tunnels dug in bare ground. Many of these wild bees are better pollinators of particular crops than honeybees are, because they visit flowers faster or carry pollen loosely on their bodies, where it rubs off easily. Farmers, however, cannot order wild bees by the truckload. Honeybee hives can be moved, and each February beekeepers haul hives from across the United States to California''s almond orchards, which bloom all at once and depend on visiting bees to set a crop.'
  WHERE section = 'reading'
    AND passage LIKE '%Bees are among the most important animals%'
    AND passage NOT LIKE '%Most people picture a honeybee%';

-- ── 24. How Bats Use Echolocation ── 116 → 235 words
UPDATE questions SET passage = 'Bats are nocturnal animals that navigate and hunt in total darkness using a biological sonar system called echolocation. A bat emits high-pitched sound pulses — far beyond the range of human hearing — that travel outward and bounce off objects in the environment. The returning echoes reach the bat''s large, highly sensitive ears, providing detailed information about the size, distance, shape, and even texture of nearby objects. This system is so precise that a bat can detect and catch a moth in complete darkness while avoiding obstacles thinner than a wire. Scientists have studied echolocation extensively, and insights from this research have contributed to the development of sonar and radar technology used by ships and aircraft.

Producing the sound is the easy part; hearing the answer is not. A bat''s outgoing pulse is loud enough to damage its own hearing, so tiny muscles in the middle ear tighten an instant before each call and release in time to catch the returning echo, a cycle repeated many times a second. As a bat closes on prey, it calls faster and faster, until the separate pulses run together into what researchers call a terminal buzz and the picture of the target refreshes almost continuously. Many moths have an answer of their own: some hear the approaching calls and fold their wings to drop out of the air, so the hunt is a contest rather than a certainty.'
  WHERE section = 'reading'
    AND passage LIKE '%Bats are nocturnal animals that navigate and%'
    AND passage NOT LIKE '%tighten an instant before each%';

-- ── 25. Democracy in Ancient Athens ── 111 → 227 words
UPDATE questions SET passage = 'Democracy — the system of government in which citizens hold political power — traces its origins to ancient Athens, Greece, in the late 6th century BCE (around 508 BCE). Athenian statesman Cleisthenes introduced reforms that gave citizens a direct voice in governing the city-state, replacing the rule of aristocrats with a system called direct democracy. In this system, eligible citizens gathered in an assembly and voted on laws and policies themselves, rather than electing representatives. However, participation was limited: women, enslaved people, and foreigners were excluded. Despite these flaws, ancient Athens established the foundational idea that ordinary people, not only kings or nobles, had the right to shape their own government.

What made the system unusual was not only who voted but how offices were filled. Citizens assembled in the open air on a hillside to debate and decide, and any of them was entitled to stand up and speak. Most public positions were not won by election, which Athenians associated with wealth and reputation, but assigned by lot, so that ordinary farmers and craftsmen took turns running the city''s daily business. A council chosen the same way prepared the assembly''s agenda. Citizens could also vote to banish a man from the city for ten years without accusing him of any crime, a procedure meant to check anyone who seemed to be gathering too much personal power.'
  WHERE section = 'reading'
    AND passage LIKE '%Democracy — the system of government in%'
    AND passage NOT LIKE '%how offices were filled. Citizens%';

-- ── Verification: expect 25 passages now carrying the added text ────────────
SELECT '033 deepened passages' AS check,
       COUNT(DISTINCT passage)::TEXT AS distinct_passages,
       '25' AS expected
  FROM questions
 WHERE section = 'reading'
   AND passage IN (
     'Water is constantly moving through Earth''s systems in a never-ending process called the water cycle. Energy from the sun causes water in oceans, lakes, and rivers to evaporate, turning liquid water into water vapor that rises into the atmosphere. As the vapor rises, it cools and condenses into tiny droplets, forming clouds. When enough droplets combine, precipitation falls as rain or snow. This water then flows into rivers, soaks into the ground, or collects in lakes — and the cycle begins again. The water cycle not only replenishes freshwater supplies but also helps regulate temperature and drive weather patterns around the globe.

The cycle does not move all water at the same speed. A molecule that evaporates from the ocean usually spends only about nine days in the atmosphere before falling again as precipitation. Water that soaks deep underground, by contrast, may sit in an aquifer for thousands of years before it returns to the surface. Ice behaves much the same way: water frozen into a glacier can stay locked in place for centuries. Most of Earth''s water is held in oceans and in ice rather than in rivers and lakes, so only a small share of it is available as fresh liquid water at any given moment. The cycle never stops, but its pace varies enormously from one storage place to the next.',
     'Sign language is a complete, complex language expressed through hand movements, facial expressions, and body posture rather than spoken words. Although deaf communities around the world have always developed informal signing systems, the first formal sign language school was established in Paris in 1760 by Abbé de l''Épée. His school later influenced American Sign Language (ASL) when a French teacher named Laurent Clerc traveled to the United States in 1817 to help found the American School for the Deaf in Hartford, Connecticut. Today, linguists recognize that sign languages are fully independent languages with their own grammar and syntax, not simply coded versions of spoken language.

Because each signing community shapes its own language, sign languages differ from one another about as much as spoken languages do. British Sign Language and American Sign Language are not mutually intelligible, even though both are used in countries where English is spoken; a signer from London and a signer from Chicago often cannot follow each other. Sign languages also use grammatical tools that speech cannot easily copy. A signer can place a person or object at a particular spot in the space in front of the body and then point back to that spot later to refer to it again, and can carry several pieces of information at once through handshape, movement, and facial expression together.',
     'Jazz is a uniquely American art form that grew out of the vibrant African American communities of New Orleans in the late 1800s and early 1900s. It blends elements of African rhythmic traditions, blues, gospel, and European harmonic structures into an improvisational style unlike anything before it. Early jazz musicians played in venues called "juke joints" and at community celebrations, often creating music on the spot rather than reading from written scores. Jazz spread rapidly up the Mississippi River to Chicago and then to New York, where it flourished during the Harlem Renaissance. Today, jazz is recognized worldwide as one of America''s greatest cultural contributions.

Jazz never settled into one fixed style. In the 1920s and 1930s, as more players moved north during the Great Migration, bands grew larger and swing filled dance halls with arranged parts written for whole sections of horns. In the 1940s, younger musicians such as Charlie Parker and Dizzy Gillespie pushed back toward small groups, faster tempos, and harmonies that were much harder to dance to — a style that came to be called bebop. Later players stretched the music further still, borrowing from Latin, rock, and classical traditions. Each of these shifts drew complaints from listeners who preferred the older sound, yet that willingness to change is part of what has kept jazz alive.',
     'More than 5,000 years ago, people in ancient Mesopotamia — the region between the Tigris and Euphrates rivers — developed one of the world''s earliest writing systems, known as cuneiform. Early scribes pressed a wedge-shaped reed stylus into soft clay tablets to create marks representing words and numbers. At first, cuneiform was used almost exclusively to keep economic records: tracking grain, livestock, and trade goods. Over centuries, the system expanded to record laws, stories, religious texts, and royal decrees. The famous Epic of Gilgamesh, one of the oldest surviving works of literature, was preserved on cuneiform tablets and tells the story of a legendary Mesopotamian king.

Cuneiform outlasted the people who invented it. Later groups, including the Akkadians and the Hittites, borrowed the wedge-shaped signs to write their own languages, which were unrelated to each other. Clay turned out to be an unusually tough material as well: a fire that would have destroyed papyrus only baked the tablets harder, so enormous numbers of them survived underground to be dug up later. For a long stretch of history, though, no one alive could read them. Scholars in the 1800s finally broke the script by studying an inscription carved high on a cliff in Persia, which repeated the same royal announcement in three languages, one of them already partly understood. Museums still hold tablets that no one has translated.',
     'Sleep is far more than simply resting. While the body is still, the brain remains remarkably active, performing critical maintenance work. During deep sleep, the brain consolidates memories — transferring information from short-term to long-term storage. It also clears out waste products that build up during waking hours, including proteins linked to neurological diseases. During a phase called REM sleep, the brain processes emotions and may generate dreams. Sleep deprivation disrupts all of these processes, impairing memory, judgment, and emotional regulation. Scientists now understand that adequate sleep — typically eight to ten hours for teenagers — is not optional but essential for brain and body health.

Getting that sleep is harder for teenagers than it sounds. During adolescence the body''s internal clock shifts: the brain starts releasing melatonin, the hormone that signals sleepiness, later in the evening than it did in childhood. A teenager still wide awake late at night is often not being stubborn but following biology. Bright light from screens can push that signal back even further. Because school still begins early, the shortfall builds up night after night across the week, and sleeping late on Saturday does not fully undo it. Some school districts have responded by moving their start times later, and researchers who study those districts report improvements in student attendance and alertness.',
     'The Olympic Games, now a global sporting celebration held every four years, began in ancient Greece. The first recorded Games took place in 776 BCE in the city of Olympia, in honor of the god Zeus. Initially, the competition included only a single footrace. Over time, events like wrestling, chariot racing, and the discus throw were added. Athletes came from city-states across Greece, and a truce was declared during the Games so that competitors could travel safely. The modern Olympics were revived in Athens in 1896, inspired by the ancient tradition, and have since grown to include hundreds of sports and thousands of athletes from every nation.

The modern revival was largely the work of Pierre de Coubertin, a French educator who believed that international competition could build understanding between nations. The 1896 Athens Games were modest by today''s standards: roughly 240 athletes, all of them men, representing about 14 nations. Women first competed four years later, at the Paris Games of 1900. A separate Winter Olympics was added in 1924, and for decades it was held in the same year as the Summer Games; since 1994 the two have been staggered, so that each still occurs every four years but an Olympics arrives every two. What began as a single race on a field in Greece now asks host cities to plan and build for the better part of a decade.',
     'The internet we use today grew from a much smaller network created in 1969 called ARPANET, funded by the United States Department of Defense. ARPANET connected computers at a handful of universities and research labs, allowing scientists to share data across long distances for the first time. Over the following decades, the network expanded and the rules governing how computers communicate — called protocols — were standardized. In 1991, scientist Tim Berners-Lee invented the World Wide Web, a system of linked pages that made the internet far easier for ordinary people to navigate. Today, billions of people use the internet daily for communication, commerce, education, and entertainment.

That growth depended on something easy to overlook: no one owns the rules. The protocols are published openly, and in 1993 the European physics laboratory where Berners-Lee worked placed the software for the World Wide Web in the public domain, free for anyone to use. Any company could then write its own browser or run its own server, so long as it followed the shared standards. Access, however, has never been equal. The International Telecommunication Union estimates that about a third of the world''s people have still never been online, most of them in lower-income countries where service costs too much or networks do not reach. The network that connects billions has not yet connected everyone.',
     'Vaccines work by training the immune system to recognize and defeat specific pathogens before a real infection occurs. When a vaccine is administered, it introduces a harmless version of a pathogen — such as a weakened or inactivated virus, or just a piece of its protein — into the body. The immune system detects this foreign material and produces antibodies, proteins designed to neutralize that specific threat. If the person later encounters the real pathogen, the immune system "remembers" it and responds rapidly, often stopping the disease before symptoms develop. This principle, called immunological memory, is what makes vaccination one of the most powerful tools in public health.

Vaccination also protects people who are not vaccinated. When enough of a community is immune, a pathogen struggles to find new hosts and outbreaks fizzle out, which shields infants too young for their shots and patients whose illnesses or medical treatments make vaccination unsafe for them. The threshold varies by disease: measles spreads so easily that roughly 95 percent of a population must be immune to keep it from circulating. That is why coverage across a whole community matters, not only what any one family decides. The clearest evidence of what widespread vaccination can accomplish is smallpox, a disease that killed millions for centuries; after a worldwide campaign, the World Health Organization declared it eradicated in 1980, and no natural case has occurred since.',
     'The invention of the telephone in 1876 transformed human communication forever. Alexander Graham Bell, a Scottish-born inventor working in Boston, is credited with creating the first practical telephone and receiving the first patent for the device. Bell''s inspiration came partly from his work with deaf students and his interest in understanding how sound travels. His first successful telephone call was made to his assistant, Thomas Watson, with the now-famous words: "Mr. Watson — come here — I want to see you." Although other inventors were working on similar devices at the same time, Bell filed his patent just hours before a competing inventor, securing his place in history.

The patent Bell received, number 174,465, has been called one of the most valuable ever granted, and it was fought over for years. Rival claimants insisted that they had reached the idea first, and Bell''s company was pulled into hundreds of lawsuits defending its rights. It won every one of them. In 1888 the Supreme Court upheld Bell''s patents, settling the question of ownership in his favor. That protection did not last forever. The patent expired in 1893, and independent companies rushed into a business Bell''s firm had held almost alone. The courtroom, as much as the workbench, decided who profited from the telephone, and it shows what a single filing date can be worth.',
     'Antibiotics are medicines that fight bacterial infections by targeting features of bacteria that human cells do not have. Some antibiotics work by disrupting the construction of a bacterium''s cell wall — without a protective wall, the bacterium bursts and dies. Others interfere with the bacteria''s ability to copy their genetic material or produce essential proteins, effectively stopping reproduction. Antibiotics do not work against viruses, which is why doctors do not prescribe them for colds or the flu. Overusing antibiotics has led to a growing problem called antibiotic resistance, in which bacteria evolve to survive the drugs that once killed them — a serious threat to public health worldwide.

Resistance is not a surprise; it is evolution running on a very fast clock. Bacteria can divide every twenty minutes or so, and in a population of billions a few cells almost always carry a mutation that blunts a drug''s effect. When antibiotics are used carelessly, the vulnerable bacteria die and those few survivors inherit the field, passing the trait to their descendants. It is the bacteria that change, not the patient. Alexander Fleming, who discovered penicillin in 1928, warned of exactly this in his 1945 Nobel lecture, cautioning that doses too small to kill microbes would instead teach them to survive. Within a few years of penicillin''s wide use, hospitals were already meeting staph infections the drug could no longer touch.',
     'Cities are often several degrees warmer than the rural areas surrounding them — a phenomenon scientists call the urban heat island effect. This happens because buildings, roads, and parking lots absorb and store heat from the sun during the day and release it slowly at night, whereas natural surfaces like grass and soil reflect more heat and cool more quickly. Dark-colored materials such as asphalt absorb especially large amounts of solar energy. Additionally, vehicles, air conditioners, and industrial equipment generate heat directly. The urban heat island effect can raise energy costs, worsen air quality, and increase the risk of heat-related illness, particularly for vulnerable populations during summer heat waves.

The effect is not spread evenly within a city. Researchers who measure temperatures block by block on the same summer afternoon find that neighborhoods shaded by mature trees stay noticeably cooler than nearby blocks where pavement and rooftops dominate. Because tree cover tends to follow old patterns of investment, the hottest blocks are often the ones whose residents have the fewest resources for coping with heat, including older adults and people with chronic illnesses. Some cities have responded by coating roofs with reflective paint, planting street trees, and adding small shaded parks. These measures do work, but they work slowly: a newly planted tree may need fifteen years of growth before its canopy shades much of anything.',
     'The law of supply and demand is one of the most fundamental principles in economics. When a product is in high demand but supply is limited, sellers can charge higher prices because buyers are competing for a scarce resource. When supply is plentiful but demand is low, prices tend to fall as sellers compete to attract buyers. The point where the quantity sellers want to sell equals the quantity buyers want to buy is called the equilibrium price. In the real world, prices shift constantly as supply and demand change — a drought that reduces the wheat harvest, for example, raises bread prices, while a new technology that makes production cheaper can lower them.

The rule has limits, however, because buyers do not react to a price change the same way for every product. When the price of a necessity such as household electricity or a prescription medicine rises, most families keep buying nearly as much as before, since there is no easy substitute; economists call this kind of demand inelastic. For an optional purchase such as a restaurant dinner or a concert ticket, the same price increase can send sales sharply lower. Expectations matter as well. If buyers believe a price is about to climb, many will rush to buy immediately, and that rush raises demand today and pushes the price up before the shortage they feared has actually arrived.',
     'Coral reefs are often called the "rainforests of the sea" because they support an extraordinary diversity of life despite covering less than one percent of the ocean floor. Reef-building corals are tiny animals that live in partnership with algae, which provide the corals with energy through photosynthesis. The hard calcium carbonate skeletons that corals build over thousands of years create a complex habitat where thousands of fish and invertebrate species find food and shelter. Reefs also protect coastlines from storm waves and support fishing industries worth billions of dollars worldwide. Rising ocean temperatures caused by climate change cause "coral bleaching," in which stressed corals expel their algae and may die, threatening the entire ecosystem.

Bleaching is not always the end of the story. If the water cools again within a few weeks, surviving corals can take in new algae and slowly resume growing. What has changed is how often the heat arrives. Marine heat waves that once struck a given reef decades apart now return within a few years, and many reef-building corals add only about a centimeter of skeleton in a year, so a damaged reef needs a long stretch of calm, cool water before it can rebuild what it lost. Researchers have responded by growing coral fragments in underwater nurseries and by breeding corals from unusually heat-tolerant parents, though these projects so far cover only small sections of reef.',
     'The human eye can distinguish millions of colors, but the actual process of color vision begins with specialized cells called cones, located in the retina at the back of the eye. There are three types of cones, each most sensitive to a different wavelength of light: one type responds mainly to red light, one to green, and one to blue. When light enters the eye, the cones detect these wavelengths and send electrical signals to the brain, which combines the signals to produce the full range of colors we perceive. People who are colorblind are typically missing one type of cone or have cones that do not function normally, causing them to confuse certain colors.

Cones, however, need a fair amount of light to do their work. In dim conditions the eye relies mostly on rods, a second kind of cell in the retina that is far more sensitive to faint light but cannot distinguish wavelengths at all. That is why a room lit only by moonlight appears gray: the objects in it still reflect exactly the same wavelengths they did at noon, but the cells reporting to the brain no longer separate one wavelength from another. The three-cone arrangement is also not the only one possible. Many birds carry a fourth type of cone that responds to ultraviolet light, so markings on feathers and flowers that are invisible to us stand out plainly to them.',
     'Every autumn, millions of birds across the world undertake remarkable journeys, traveling hundreds or thousands of miles to reach warmer climates where food remains available. Unlike most behaviors, bird migration appears to be triggered not by cold temperatures directly, but by changes in day length — called photoperiod — which signals the approaching season. Birds navigate using a combination of the sun''s position, star patterns at night, Earth''s magnetic field, and familiar landmarks. Many species return to the same nesting grounds year after year with extraordinary precision. Scientists are still studying exactly how birds integrate all of these navigational cues, but it is clear that migration is a finely tuned biological response to environmental change.

Tracking individual birds has become far easier as tags have shrunk. Lightweight geolocators and light-sensing geolocators now weigh less than a gram, and they have revealed journeys that earlier researchers could only guess at. Bar-tailed godwits, shorebirds that nest in Alaska, fly to New Zealand across open ocean without landing once — more than seven thousand miles in a little over a week, with no chance to feed or rest along the way. Before leaving, a godwit nearly doubles its weight in stored fat, and its digestive organs shrink to save weight for the crossing. A flight like that cannot be improvised. The preparation has to begin weeks ahead, while conditions at home are still comfortable.',
     'Color is not just a feature of the physical world — it is a creation of the mind. When light strikes an object, the object absorbs some wavelengths and reflects others. The reflected wavelengths reach our eyes and are interpreted by the brain as color. Because the brain also uses context to make sense of color, two identical colors can appear different depending on what surrounds them. This is why a gray square looks darker when placed on a white background than when placed on a black one. Marketers use this knowledge to influence behavior: studies show that red can increase excitement and urgency, blue is associated with trust and calm, and yellow draws attention quickly.

The brain''s reliance on context also explains why colors stay recognizable when the light changes. A sheet of paper looks white at noon and still looks white under a yellowish lamp at night, even though the light bouncing off it is very different in each case. The brain compares the paper with everything around it and corrects for the lighting, a habit so automatic that people rarely notice it. That same habit limits what a single color can do. Researchers who test color effects in a laboratory often find weaker results in real stores, where price tags, packaging, lighting, and shelf position all compete for a shopper''s attention. Color shapes a first impression, but it seldom decides a purchase on its own.',
     'Long before the invention of the compass or GPS, indigenous navigators of the Pacific Islands crossed thousands of miles of open ocean using only natural cues. By reading the stars — particularly the position and movement of key constellations — they could determine latitude and direction. They also studied ocean swells, which move in predictable patterns from distant wind sources, and used the feel of wave motion beneath their canoes to stay on course. The color of the water, cloud formations, and even the behavior of birds indicated the presence of nearby islands. This sophisticated system of wayfinding, passed down through oral tradition and practice, enabled Polynesian peoples to settle islands across a vast region of the Pacific.

By the twentieth century much of this knowledge had faded, and some outsiders argued that the islands must have been reached by accident, by canoes blown off course. In 1976 a group in Hawaii set out to test that claim. They built Hokule''a, a double-hulled voyaging canoe, and sailed it roughly 2,500 miles to Tahiti carrying no compass, no charts, and no modern instruments. The navigator was Mau Piailug, a master wayfinder from the island of Satawal and one of the few men still trained in the old methods. The voyage took about a month and arrived where it was aimed. Piailug later taught Hawaiian students, and the tradition he carried is practiced again across the Pacific today.',
     'Earth''s outer layer is not a single solid shell but a patchwork of giant rocky slabs called tectonic plates. These plates fit together like pieces of a puzzle and move slowly — just centimeters per year — driven by heat rising from Earth''s interior. Where plates meet, tremendous forces build up over time. When the stress becomes too great, the plates suddenly slip or grind past one another, releasing energy in waves that shake the ground — an earthquake. Volcanoes also tend to form near plate boundaries, since magma can force its way to the surface along cracks between plates. Most of the world''s earthquakes and volcanoes occur along the "Ring of Fire," a zone encircling the Pacific Ocean.

Knowing why earthquakes happen has not made it possible to say when one will happen. Scientists can map faults, measure how fast the ground on each side is straining, and estimate the chance of a large quake in the next few decades, but they cannot name a day. With warning so limited, most protection comes from preparing in advance. Engineers design buildings that bend and sway instead of snapping, anchor them firmly to their foundations, and put flexible joints in gas and water lines. Communities practice drills so people know to drop and take cover. Where such steps have been taken, death tolls have fallen sharply; where older buildings are common, a quake of the same size can be far deadlier.',
     'Memory is not stored in a single location in the brain, but it begins in a region called the hippocampus. When we experience something new, the hippocampus helps encode the information by strengthening connections between neurons — the brain''s nerve cells. Initially, memories are fragile and can be disrupted. Over time, through a process called consolidation, memories are gradually transferred to the cerebral cortex, the brain''s outer layer, for long-term storage. Sleep plays a critical role in this process: during sleep, the brain replays recent experiences and strengthens the neural pathways that hold them. Strong emotional experiences tend to form more vivid and lasting memories because the amygdala — the brain''s emotional center — helps flag them as important.

Remembering, however, is not like opening a file. Each time a memory is recalled, the brain rebuilds it from pieces, and the rebuilt version can be shaped by what a person has learned or imagined since. In experiments, people who are asked leading questions after watching a filmed accident often report details that were never there, and they report them with confidence. Confidence and accuracy, it turns out, are only loosely related. This same flexibility has a useful side. Students who quiz themselves on material remember it better later than students who simply reread it, because pulling a memory out strengthens the path back to it. Rereading feels easier, which is one reason it remains the more popular study method.',
     'Sound is a form of energy that travels as waves — but unlike light, it cannot travel through empty space. When an object vibrates, it pushes against nearby air molecules, creating areas of compression and expansion that ripple outward from the source. These pressure waves travel through the air — or through solids and liquids — until they reach the ear, where they cause the eardrum to vibrate. The brain interprets these vibrations as sound. The speed of sound depends on the medium it travels through: it moves faster through water than air, and faster through steel than water. The pitch of a sound is determined by the frequency of the waves — more waves per second produce a higher pitch.

Because sound bounces off surfaces and moves at a known speed, an echo can be used to measure distance. A ship''s sonar sends a pulse toward the seafloor and times how long the return takes; since sound travels about 1,500 meters per second in seawater, a four-second round trip means the bottom is roughly 3,000 meters down. Animals do the same with far more precision. A bat calls out in pulses too high for human ears and reads the returning echoes to find a moth in the dark, correcting its aim as the echoes change. Dolphins hunt this way in cloudy water. Nothing unusual is happening in these cases, only the ordinary behavior of pressure waves put to work.',
     'Stars are not permanent fixtures in the sky — they are born, live for millions or billions of years, and eventually die. A star begins as a cloud of gas and dust called a nebula. Gravity pulls this material together, and when the core grows hot enough, nuclear fusion ignites and a star is born. For most of its life, a star burns hydrogen fuel. When the hydrogen runs out, the star expands into a red giant. Small stars like our sun will eventually shed their outer layers and leave behind a dense core called a white dwarf. Massive stars, however, end dramatically: they collapse and explode in a violent supernova, sometimes leaving behind an incredibly dense remnant called a neutron star or even a black hole.

These endings matter beyond astronomy. Hydrogen and helium have existed since the early universe, but nearly every heavier element was assembled inside stars. Fusion in stellar cores builds carbon, oxygen, and iron, and a supernova hurls that material outward at enormous speed, mixing it into the thin gas and dust between the stars. The calcium in a person''s bones and the oxygen in each breath were made this way, long before Earth existed. Such explosions are rare but unforgettable: in 1054, astronomers in China recorded a sudden light in the sky, visible in daylight for more than three weeks. The debris cloud it left is still expanding today.',
     'The term ''cognitive dissonance'' was introduced by psychologist Leon Festinger in 1957 to describe the discomfort people feel when they hold two conflicting beliefs simultaneously. Festinger proposed that this discomfort motivates individuals to reduce the inconsistency — either by changing one of their beliefs, acquiring new information that resolves the conflict, or minimizing the importance of one of the conflicting ideas. Advertisers and political campaigns have long understood this principle, designing messages that subtly shift audiences toward resolving dissonance in a preferred direction.

Festinger''s own experiments showed how strange this drive to resolve conflict can look. In one famous study, volunteers spent an hour on a dull, repetitive task and were then asked to tell the next participant that the work had been interesting. Some were paid twenty dollars for saying so; others were paid one. Those paid twenty dollars later admitted the task had been boring, while those paid one dollar reported that they had genuinely enjoyed it. The large payment gave an obvious outside reason for the lie, so no inconsistency arose. The small payment gave none, and the easiest way for those volunteers to square their words with their opinion was to decide that the task really had been worth doing.',
     'Bees are among the most important animals on Earth, not because of their honey but because of their role as pollinators. As bees travel from flower to flower collecting nectar, they transfer pollen, enabling plants to reproduce. This process, called pollination, is essential for the production of fruits, vegetables, nuts, and seeds that countless species — including humans — depend on for food. Scientists estimate that roughly one-third of the food humans eat relies on pollination. Habitat loss, pesticide use, and disease have caused bee populations to decline sharply in recent decades, alarming ecologists who warn that the loss of bees could trigger widespread food shortages.

Most people picture a honeybee hive, but honeybees are only one of roughly twenty thousand bee species, and the great majority live alone rather than in colonies, nesting in hollow stems or in tunnels dug in bare ground. Many of these wild bees are better pollinators of particular crops than honeybees are, because they visit flowers faster or carry pollen loosely on their bodies, where it rubs off easily. Farmers, however, cannot order wild bees by the truckload. Honeybee hives can be moved, and each February beekeepers haul hives from across the United States to California''s almond orchards, which bloom all at once and depend on visiting bees to set a crop.',
     'Bats are nocturnal animals that navigate and hunt in total darkness using a biological sonar system called echolocation. A bat emits high-pitched sound pulses — far beyond the range of human hearing — that travel outward and bounce off objects in the environment. The returning echoes reach the bat''s large, highly sensitive ears, providing detailed information about the size, distance, shape, and even texture of nearby objects. This system is so precise that a bat can detect and catch a moth in complete darkness while avoiding obstacles thinner than a wire. Scientists have studied echolocation extensively, and insights from this research have contributed to the development of sonar and radar technology used by ships and aircraft.

Producing the sound is the easy part; hearing the answer is not. A bat''s outgoing pulse is loud enough to damage its own hearing, so tiny muscles in the middle ear tighten an instant before each call and release in time to catch the returning echo, a cycle repeated many times a second. As a bat closes on prey, it calls faster and faster, until the separate pulses run together into what researchers call a terminal buzz and the picture of the target refreshes almost continuously. Many moths have an answer of their own: some hear the approaching calls and fold their wings to drop out of the air, so the hunt is a contest rather than a certainty.',
     'Democracy — the system of government in which citizens hold political power — traces its origins to ancient Athens, Greece, in the late 6th century BCE (around 508 BCE). Athenian statesman Cleisthenes introduced reforms that gave citizens a direct voice in governing the city-state, replacing the rule of aristocrats with a system called direct democracy. In this system, eligible citizens gathered in an assembly and voted on laws and policies themselves, rather than electing representatives. However, participation was limited: women, enslaved people, and foreigners were excluded. Despite these flaws, ancient Athens established the foundational idea that ordinary people, not only kings or nobles, had the right to shape their own government.

What made the system unusual was not only who voted but how offices were filled. Citizens assembled in the open air on a hillside to debate and decide, and any of them was entitled to stand up and speak. Most public positions were not won by election, which Athenians associated with wealth and reputation, but assigned by lot, so that ordinary farmers and craftsmen took turns running the city''s daily business. A council chosen the same way prepared the assembly''s agenda. Citizens could also vote to banish a man from the city for ten years without accusing him of any crime, a procedure meant to check anyone who seemed to be gathering too much personal power.'
   );
