-- 034 — Add 50 reading questions for the deepened passages
--
-- ⚠️ MUST RUN AFTER 033. Each question carries the FULL deepened passage text
-- written by 033. Reading questions are grouped by exact passage text, so
-- running this before 033 would split each passage in two.
--
-- Two questions per passage for the 25 passages 033 deepens, written against
-- the added material. Pure insert. Ids are deterministic:
-- md5(section || '|' || prompt)::UUID, so re-running is a no-op. Nothing
-- existing is deleted or updated, and user_question_history is never touched.
--
-- Four of the reviewed questions shared the stem "How does the second paragraph
-- relate to the first?" on four different passages. Ids are md5 of the prompt,
-- so three of them would have been dropped as duplicates; each is restated in
-- wording that asks exactly the same thing, leaving every answer key unchanged.
--
-- passage_title is set EXPLICITLY on every new row, to the exact title migration
-- 030 already put on that passage's other rows, so the quiz header can never
-- render blank or fall back to a derived fragment for these questions.

WITH p(pkey, body, title) AS (VALUES
  ('p01', 'Water is constantly moving through Earth''s systems in a never-ending process called the water cycle. Energy from the sun causes water in oceans, lakes, and rivers to evaporate, turning liquid water into water vapor that rises into the atmosphere. As the vapor rises, it cools and condenses into tiny droplets, forming clouds. When enough droplets combine, precipitation falls as rain or snow. This water then flows into rivers, soaks into the ground, or collects in lakes — and the cycle begins again. The water cycle not only replenishes freshwater supplies but also helps regulate temperature and drive weather patterns around the globe.

The cycle does not move all water at the same speed. A molecule that evaporates from the ocean usually spends only about nine days in the atmosphere before falling again as precipitation. Water that soaks deep underground, by contrast, may sit in an aquifer for thousands of years before it returns to the surface. Ice behaves much the same way: water frozen into a glacier can stay locked in place for centuries. Most of Earth''s water is held in oceans and in ice rather than in rivers and lakes, so only a small share of it is available as fresh liquid water at any given moment. The cycle never stops, but its pace varies enormously from one storage place to the next.', 'How the Water Cycle Works'),
  ('p02', 'Sign language is a complete, complex language expressed through hand movements, facial expressions, and body posture rather than spoken words. Although deaf communities around the world have always developed informal signing systems, the first formal sign language school was established in Paris in 1760 by Abbé de l''Épée. His school later influenced American Sign Language (ASL) when a French teacher named Laurent Clerc traveled to the United States in 1817 to help found the American School for the Deaf in Hartford, Connecticut. Today, linguists recognize that sign languages are fully independent languages with their own grammar and syntax, not simply coded versions of spoken language.

Because each signing community shapes its own language, sign languages differ from one another about as much as spoken languages do. British Sign Language and American Sign Language are not mutually intelligible, even though both are used in countries where English is spoken; a signer from London and a signer from Chicago often cannot follow each other. Sign languages also use grammatical tools that speech cannot easily copy. A signer can place a person or object at a particular spot in the space in front of the body and then point back to that spot later to refer to it again, and can carry several pieces of information at once through handshape, movement, and facial expression together.', 'The History of Sign Language'),
  ('p03', 'Jazz is a uniquely American art form that grew out of the vibrant African American communities of New Orleans in the late 1800s and early 1900s. It blends elements of African rhythmic traditions, blues, gospel, and European harmonic structures into an improvisational style unlike anything before it. Early jazz musicians played in venues called "juke joints" and at community celebrations, often creating music on the spot rather than reading from written scores. Jazz spread rapidly up the Mississippi River to Chicago and then to New York, where it flourished during the Harlem Renaissance. Today, jazz is recognized worldwide as one of America''s greatest cultural contributions.

Jazz never settled into one fixed style. In the 1920s and 1930s, as more players moved north during the Great Migration, bands grew larger and swing filled dance halls with arranged parts written for whole sections of horns. In the 1940s, younger musicians such as Charlie Parker and Dizzy Gillespie pushed back toward small groups, faster tempos, and harmonies that were much harder to dance to — a style that came to be called bebop. Later players stretched the music further still, borrowing from Latin, rock, and classical traditions. Each of these shifts drew complaints from listeners who preferred the older sound, yet that willingness to change is part of what has kept jazz alive.', 'The Roots of Jazz'),
  ('p04', 'More than 5,000 years ago, people in ancient Mesopotamia — the region between the Tigris and Euphrates rivers — developed one of the world''s earliest writing systems, known as cuneiform. Early scribes pressed a wedge-shaped reed stylus into soft clay tablets to create marks representing words and numbers. At first, cuneiform was used almost exclusively to keep economic records: tracking grain, livestock, and trade goods. Over centuries, the system expanded to record laws, stories, religious texts, and royal decrees. The famous Epic of Gilgamesh, one of the oldest surviving works of literature, was preserved on cuneiform tablets and tells the story of a legendary Mesopotamian king.

Cuneiform outlasted the people who invented it. Later groups, including the Akkadians and the Hittites, borrowed the wedge-shaped signs to write their own languages, which were unrelated to each other. Clay turned out to be an unusually tough material as well: a fire that would have destroyed papyrus only baked the tablets harder, so enormous numbers of them survived underground to be dug up later. For a long stretch of history, though, no one alive could read them. Scholars in the 1800s finally broke the script by studying an inscription carved high on a cliff in Persia, which repeated the same royal announcement in three languages, one of them already partly understood. Museums still hold tablets that no one has translated.', 'Writing in Ancient Mesopotamia'),
  ('p05', 'Sleep is far more than simply resting. While the body is still, the brain remains remarkably active, performing critical maintenance work. During deep sleep, the brain consolidates memories — transferring information from short-term to long-term storage. It also clears out waste products that build up during waking hours, including proteins linked to neurological diseases. During a phase called REM sleep, the brain processes emotions and may generate dreams. Sleep deprivation disrupts all of these processes, impairing memory, judgment, and emotional regulation. Scientists now understand that adequate sleep — typically eight to ten hours for teenagers — is not optional but essential for brain and body health.

Getting that sleep is harder for teenagers than it sounds. During adolescence the body''s internal clock shifts: the brain starts releasing melatonin, the hormone that signals sleepiness, later in the evening than it did in childhood. A teenager still wide awake late at night is often not being stubborn but following biology. Bright light from screens can push that signal back even further. Because school still begins early, the shortfall builds up night after night across the week, and sleeping late on Saturday does not fully undo it. Some school districts have responded by moving their start times later, and researchers who study those districts report improvements in student attendance and alertness.', 'The Brain During Sleep'),
  ('p06', 'The Olympic Games, now a global sporting celebration held every four years, began in ancient Greece. The first recorded Games took place in 776 BCE in the city of Olympia, in honor of the god Zeus. Initially, the competition included only a single footrace. Over time, events like wrestling, chariot racing, and the discus throw were added. Athletes came from city-states across Greece, and a truce was declared during the Games so that competitors could travel safely. The modern Olympics were revived in Athens in 1896, inspired by the ancient tradition, and have since grown to include hundreds of sports and thousands of athletes from every nation.

The modern revival was largely the work of Pierre de Coubertin, a French educator who believed that international competition could build understanding between nations. The 1896 Athens Games were modest by today''s standards: roughly 240 athletes, all of them men, representing about 14 nations. Women first competed four years later, at the Paris Games of 1900. A separate Winter Olympics was added in 1924, and for decades it was held in the same year as the Summer Games; since 1994 the two have been staggered, so that each still occurs every four years but an Olympics arrives every two. What began as a single race on a field in Greece now asks host cities to plan and build for the better part of a decade.', 'The Olympic Games Through Time'),
  ('p07', 'The internet we use today grew from a much smaller network created in 1969 called ARPANET, funded by the United States Department of Defense. ARPANET connected computers at a handful of universities and research labs, allowing scientists to share data across long distances for the first time. Over the following decades, the network expanded and the rules governing how computers communicate — called protocols — were standardized. In 1991, scientist Tim Berners-Lee invented the World Wide Web, a system of linked pages that made the internet far easier for ordinary people to navigate. Today, billions of people use the internet daily for communication, commerce, education, and entertainment.

That growth depended on something easy to overlook: no one owns the rules. The protocols are published openly, and in 1993 the European physics laboratory where Berners-Lee worked placed the software for the World Wide Web in the public domain, free for anyone to use. Any company could then write its own browser or run its own server, so long as it followed the shared standards. Access, however, has never been equal. The International Telecommunication Union estimates that about a third of the world''s people have still never been online, most of them in lower-income countries where service costs too much or networks do not reach. The network that connects billions has not yet connected everyone.', 'From ARPANET to the Web'),
  ('p08', 'Vaccines work by training the immune system to recognize and defeat specific pathogens before a real infection occurs. When a vaccine is administered, it introduces a harmless version of a pathogen — such as a weakened or inactivated virus, or just a piece of its protein — into the body. The immune system detects this foreign material and produces antibodies, proteins designed to neutralize that specific threat. If the person later encounters the real pathogen, the immune system "remembers" it and responds rapidly, often stopping the disease before symptoms develop. This principle, called immunological memory, is what makes vaccination one of the most powerful tools in public health.

Vaccination also protects people who are not vaccinated. When enough of a community is immune, a pathogen struggles to find new hosts and outbreaks fizzle out, which shields infants too young for their shots and patients whose illnesses or medical treatments make vaccination unsafe for them. The threshold varies by disease: measles spreads so easily that roughly 95 percent of a population must be immune to keep it from circulating. That is why coverage across a whole community matters, not only what any one family decides. The clearest evidence of what widespread vaccination can accomplish is smallpox, a disease that killed millions for centuries; after a worldwide campaign, the World Health Organization declared it eradicated in 1980, and no natural case has occurred since.', 'How Vaccines Work'),
  ('p09', 'The invention of the telephone in 1876 transformed human communication forever. Alexander Graham Bell, a Scottish-born inventor working in Boston, is credited with creating the first practical telephone and receiving the first patent for the device. Bell''s inspiration came partly from his work with deaf students and his interest in understanding how sound travels. His first successful telephone call was made to his assistant, Thomas Watson, with the now-famous words: "Mr. Watson — come here — I want to see you." Although other inventors were working on similar devices at the same time, Bell filed his patent just hours before a competing inventor, securing his place in history.

The patent Bell received, number 174,465, has been called one of the most valuable ever granted, and it was fought over for years. Rival claimants insisted that they had reached the idea first, and Bell''s company was pulled into hundreds of lawsuits defending its rights. It won every one of them. In 1888 the Supreme Court upheld Bell''s patents, settling the question of ownership in his favor. That protection did not last forever. The patent expired in 1893, and independent companies rushed into a business Bell''s firm had held almost alone. The courtroom, as much as the workbench, decided who profited from the telephone, and it shows what a single filing date can be worth.', 'Bell and the Telephone'),
  ('p10', 'Antibiotics are medicines that fight bacterial infections by targeting features of bacteria that human cells do not have. Some antibiotics work by disrupting the construction of a bacterium''s cell wall — without a protective wall, the bacterium bursts and dies. Others interfere with the bacteria''s ability to copy their genetic material or produce essential proteins, effectively stopping reproduction. Antibiotics do not work against viruses, which is why doctors do not prescribe them for colds or the flu. Overusing antibiotics has led to a growing problem called antibiotic resistance, in which bacteria evolve to survive the drugs that once killed them — a serious threat to public health worldwide.

Resistance is not a surprise; it is evolution running on a very fast clock. Bacteria can divide every twenty minutes or so, and in a population of billions a few cells almost always carry a mutation that blunts a drug''s effect. When antibiotics are used carelessly, the vulnerable bacteria die and those few survivors inherit the field, passing the trait to their descendants. It is the bacteria that change, not the patient. Alexander Fleming, who discovered penicillin in 1928, warned of exactly this in his 1945 Nobel lecture, cautioning that doses too small to kill microbes would instead teach them to survive. Within a few years of penicillin''s wide use, hospitals were already meeting staph infections the drug could no longer touch.', 'How Antibiotics Fight Bacteria'),
  ('p11', 'Cities are often several degrees warmer than the rural areas surrounding them — a phenomenon scientists call the urban heat island effect. This happens because buildings, roads, and parking lots absorb and store heat from the sun during the day and release it slowly at night, whereas natural surfaces like grass and soil reflect more heat and cool more quickly. Dark-colored materials such as asphalt absorb especially large amounts of solar energy. Additionally, vehicles, air conditioners, and industrial equipment generate heat directly. The urban heat island effect can raise energy costs, worsen air quality, and increase the risk of heat-related illness, particularly for vulnerable populations during summer heat waves.

The effect is not spread evenly within a city. Researchers who measure temperatures block by block on the same summer afternoon find that neighborhoods shaded by mature trees stay noticeably cooler than nearby blocks where pavement and rooftops dominate. Because tree cover tends to follow old patterns of investment, the hottest blocks are often the ones whose residents have the fewest resources for coping with heat, including older adults and people with chronic illnesses. Some cities have responded by coating roofs with reflective paint, planting street trees, and adding small shaded parks. These measures do work, but they work slowly: a newly planted tree may need fifteen years of growth before its canopy shades much of anything.', 'The Urban Heat Island'),
  ('p12', 'The law of supply and demand is one of the most fundamental principles in economics. When a product is in high demand but supply is limited, sellers can charge higher prices because buyers are competing for a scarce resource. When supply is plentiful but demand is low, prices tend to fall as sellers compete to attract buyers. The point where the quantity sellers want to sell equals the quantity buyers want to buy is called the equilibrium price. In the real world, prices shift constantly as supply and demand change — a drought that reduces the wheat harvest, for example, raises bread prices, while a new technology that makes production cheaper can lower them.

The rule has limits, however, because buyers do not react to a price change the same way for every product. When the price of a necessity such as household electricity or a prescription medicine rises, most families keep buying nearly as much as before, since there is no easy substitute; economists call this kind of demand inelastic. For an optional purchase such as a restaurant dinner or a concert ticket, the same price increase can send sales sharply lower. Expectations matter as well. If buyers believe a price is about to climb, many will rush to buy immediately, and that rush raises demand today and pushes the price up before the shortage they feared has actually arrived.', 'Supply, Demand, and Prices'),
  ('p13', 'Coral reefs are often called the "rainforests of the sea" because they support an extraordinary diversity of life despite covering less than one percent of the ocean floor. Reef-building corals are tiny animals that live in partnership with algae, which provide the corals with energy through photosynthesis. The hard calcium carbonate skeletons that corals build over thousands of years create a complex habitat where thousands of fish and invertebrate species find food and shelter. Reefs also protect coastlines from storm waves and support fishing industries worth billions of dollars worldwide. Rising ocean temperatures caused by climate change cause "coral bleaching," in which stressed corals expel their algae and may die, threatening the entire ecosystem.

Bleaching is not always the end of the story. If the water cools again within a few weeks, surviving corals can take in new algae and slowly resume growing. What has changed is how often the heat arrives. Marine heat waves that once struck a given reef decades apart now return within a few years, and many reef-building corals add only about a centimeter of skeleton in a year, so a damaged reef needs a long stretch of calm, cool water before it can rebuild what it lost. Researchers have responded by growing coral fragments in underwater nurseries and by breeding corals from unusually heat-tolerant parents, though these projects so far cover only small sections of reef.', 'Life on Coral Reefs'),
  ('p14', 'The human eye can distinguish millions of colors, but the actual process of color vision begins with specialized cells called cones, located in the retina at the back of the eye. There are three types of cones, each most sensitive to a different wavelength of light: one type responds mainly to red light, one to green, and one to blue. When light enters the eye, the cones detect these wavelengths and send electrical signals to the brain, which combines the signals to produce the full range of colors we perceive. People who are colorblind are typically missing one type of cone or have cones that do not function normally, causing them to confuse certain colors.

Cones, however, need a fair amount of light to do their work. In dim conditions the eye relies mostly on rods, a second kind of cell in the retina that is far more sensitive to faint light but cannot distinguish wavelengths at all. That is why a room lit only by moonlight appears gray: the objects in it still reflect exactly the same wavelengths they did at noon, but the cells reporting to the brain no longer separate one wavelength from another. The three-cone arrangement is also not the only one possible. Many birds carry a fourth type of cone that responds to ultraviolet light, so markings on feathers and flowers that are invisible to us stand out plainly to them.', 'How the Eye Sees Color'),
  ('p15', 'Every autumn, millions of birds across the world undertake remarkable journeys, traveling hundreds or thousands of miles to reach warmer climates where food remains available. Unlike most behaviors, bird migration appears to be triggered not by cold temperatures directly, but by changes in day length — called photoperiod — which signals the approaching season. Birds navigate using a combination of the sun''s position, star patterns at night, Earth''s magnetic field, and familiar landmarks. Many species return to the same nesting grounds year after year with extraordinary precision. Scientists are still studying exactly how birds integrate all of these navigational cues, but it is clear that migration is a finely tuned biological response to environmental change.

Tracking individual birds has become far easier as tags have shrunk. Lightweight geolocators and light-sensing geolocators now weigh less than a gram, and they have revealed journeys that earlier researchers could only guess at. Bar-tailed godwits, shorebirds that nest in Alaska, fly to New Zealand across open ocean without landing once — more than seven thousand miles in a little over a week, with no chance to feed or rest along the way. Before leaving, a godwit nearly doubles its weight in stored fat, and its digestive organs shrink to save weight for the crossing. A flight like that cannot be improvised. The preparation has to begin weeks ahead, while conditions at home are still comfortable.', 'Why Birds Migrate'),
  ('p16', 'Color is not just a feature of the physical world — it is a creation of the mind. When light strikes an object, the object absorbs some wavelengths and reflects others. The reflected wavelengths reach our eyes and are interpreted by the brain as color. Because the brain also uses context to make sense of color, two identical colors can appear different depending on what surrounds them. This is why a gray square looks darker when placed on a white background than when placed on a black one. Marketers use this knowledge to influence behavior: studies show that red can increase excitement and urgency, blue is associated with trust and calm, and yellow draws attention quickly.

The brain''s reliance on context also explains why colors stay recognizable when the light changes. A sheet of paper looks white at noon and still looks white under a yellowish lamp at night, even though the light bouncing off it is very different in each case. The brain compares the paper with everything around it and corrects for the lighting, a habit so automatic that people rarely notice it. That same habit limits what a single color can do. Researchers who test color effects in a laboratory often find weaker results in real stores, where price tags, packaging, lighting, and shelf position all compete for a shopper''s attention. Color shapes a first impression, but it seldom decides a purchase on its own.', 'How the Brain Reads Color'),
  ('p17', 'Long before the invention of the compass or GPS, indigenous navigators of the Pacific Islands crossed thousands of miles of open ocean using only natural cues. By reading the stars — particularly the position and movement of key constellations — they could determine latitude and direction. They also studied ocean swells, which move in predictable patterns from distant wind sources, and used the feel of wave motion beneath their canoes to stay on course. The color of the water, cloud formations, and even the behavior of birds indicated the presence of nearby islands. This sophisticated system of wayfinding, passed down through oral tradition and practice, enabled Polynesian peoples to settle islands across a vast region of the Pacific.

By the twentieth century much of this knowledge had faded, and some outsiders argued that the islands must have been reached by accident, by canoes blown off course. In 1976 a group in Hawaii set out to test that claim. They built Hokule''a, a double-hulled voyaging canoe, and sailed it roughly 2,500 miles to Tahiti carrying no compass, no charts, and no modern instruments. The navigator was Mau Piailug, a master wayfinder from the island of Satawal and one of the few men still trained in the old methods. The voyage took about a month and arrived where it was aimed. Piailug later taught Hawaiian students, and the tradition he carried is practiced again across the Pacific today.', 'Wayfinding Across the Pacific'),
  ('p18', 'Earth''s outer layer is not a single solid shell but a patchwork of giant rocky slabs called tectonic plates. These plates fit together like pieces of a puzzle and move slowly — just centimeters per year — driven by heat rising from Earth''s interior. Where plates meet, tremendous forces build up over time. When the stress becomes too great, the plates suddenly slip or grind past one another, releasing energy in waves that shake the ground — an earthquake. Volcanoes also tend to form near plate boundaries, since magma can force its way to the surface along cracks between plates. Most of the world''s earthquakes and volcanoes occur along the "Ring of Fire," a zone encircling the Pacific Ocean.

Knowing why earthquakes happen has not made it possible to say when one will happen. Scientists can map faults, measure how fast the ground on each side is straining, and estimate the chance of a large quake in the next few decades, but they cannot name a day. With warning so limited, most protection comes from preparing in advance. Engineers design buildings that bend and sway instead of snapping, anchor them firmly to their foundations, and put flexible joints in gas and water lines. Communities practice drills so people know to drop and take cover. Where such steps have been taken, death tolls have fallen sharply; where older buildings are common, a quake of the same size can be far deadlier.', 'Tectonic Plates and Earthquakes'),
  ('p19', 'Memory is not stored in a single location in the brain, but it begins in a region called the hippocampus. When we experience something new, the hippocampus helps encode the information by strengthening connections between neurons — the brain''s nerve cells. Initially, memories are fragile and can be disrupted. Over time, through a process called consolidation, memories are gradually transferred to the cerebral cortex, the brain''s outer layer, for long-term storage. Sleep plays a critical role in this process: during sleep, the brain replays recent experiences and strengthens the neural pathways that hold them. Strong emotional experiences tend to form more vivid and lasting memories because the amygdala — the brain''s emotional center — helps flag them as important.

Remembering, however, is not like opening a file. Each time a memory is recalled, the brain rebuilds it from pieces, and the rebuilt version can be shaped by what a person has learned or imagined since. In experiments, people who are asked leading questions after watching a filmed accident often report details that were never there, and they report them with confidence. Confidence and accuracy, it turns out, are only loosely related. This same flexibility has a useful side. Students who quiz themselves on material remember it better later than students who simply reread it, because pulling a memory out strengthens the path back to it. Rereading feels easier, which is one reason it remains the more popular study method.', 'How Memories Are Formed'),
  ('p20', 'Sound is a form of energy that travels as waves — but unlike light, it cannot travel through empty space. When an object vibrates, it pushes against nearby air molecules, creating areas of compression and expansion that ripple outward from the source. These pressure waves travel through the air — or through solids and liquids — until they reach the ear, where they cause the eardrum to vibrate. The brain interprets these vibrations as sound. The speed of sound depends on the medium it travels through: it moves faster through water than air, and faster through steel than water. The pitch of a sound is determined by the frequency of the waves — more waves per second produce a higher pitch.

Because sound bounces off surfaces and moves at a known speed, an echo can be used to measure distance. A ship''s sonar sends a pulse toward the seafloor and times how long the return takes; since sound travels about 1,500 meters per second in seawater, a four-second round trip means the bottom is roughly 3,000 meters down. Animals do the same with far more precision. A bat calls out in pulses too high for human ears and reads the returning echoes to find a moth in the dark, correcting its aim as the echoes change. Dolphins hunt this way in cloudy water. Nothing unusual is happening in these cases, only the ordinary behavior of pressure waves put to work.', 'How Sound Travels'),
  ('p21', 'Stars are not permanent fixtures in the sky — they are born, live for millions or billions of years, and eventually die. A star begins as a cloud of gas and dust called a nebula. Gravity pulls this material together, and when the core grows hot enough, nuclear fusion ignites and a star is born. For most of its life, a star burns hydrogen fuel. When the hydrogen runs out, the star expands into a red giant. Small stars like our sun will eventually shed their outer layers and leave behind a dense core called a white dwarf. Massive stars, however, end dramatically: they collapse and explode in a violent supernova, sometimes leaving behind an incredibly dense remnant called a neutron star or even a black hole.

These endings matter beyond astronomy. Hydrogen and helium have existed since the early universe, but nearly every heavier element was assembled inside stars. Fusion in stellar cores builds carbon, oxygen, and iron, and a supernova hurls that material outward at enormous speed, mixing it into the thin gas and dust between the stars. The calcium in a person''s bones and the oxygen in each breath were made this way, long before Earth existed. Such explosions are rare but unforgettable: in 1054, astronomers in China recorded a sudden light in the sky, visible in daylight for more than three weeks. The debris cloud it left is still expanding today.', 'The Life Cycle of Stars'),
  ('p22', 'The term ''cognitive dissonance'' was introduced by psychologist Leon Festinger in 1957 to describe the discomfort people feel when they hold two conflicting beliefs simultaneously. Festinger proposed that this discomfort motivates individuals to reduce the inconsistency — either by changing one of their beliefs, acquiring new information that resolves the conflict, or minimizing the importance of one of the conflicting ideas. Advertisers and political campaigns have long understood this principle, designing messages that subtly shift audiences toward resolving dissonance in a preferred direction.

Festinger''s own experiments showed how strange this drive to resolve conflict can look. In one famous study, volunteers spent an hour on a dull, repetitive task and were then asked to tell the next participant that the work had been interesting. Some were paid twenty dollars for saying so; others were paid one. Those paid twenty dollars later admitted the task had been boring, while those paid one dollar reported that they had genuinely enjoyed it. The large payment gave an obvious outside reason for the lie, so no inconsistency arose. The small payment gave none, and the easiest way for those volunteers to square their words with their opinion was to decide that the task really had been worth doing.', 'Cognitive Dissonance Explained'),
  ('p23', 'Bees are among the most important animals on Earth, not because of their honey but because of their role as pollinators. As bees travel from flower to flower collecting nectar, they transfer pollen, enabling plants to reproduce. This process, called pollination, is essential for the production of fruits, vegetables, nuts, and seeds that countless species — including humans — depend on for food. Scientists estimate that roughly one-third of the food humans eat relies on pollination. Habitat loss, pesticide use, and disease have caused bee populations to decline sharply in recent decades, alarming ecologists who warn that the loss of bees could trigger widespread food shortages.

Most people picture a honeybee hive, but honeybees are only one of roughly twenty thousand bee species, and the great majority live alone rather than in colonies, nesting in hollow stems or in tunnels dug in bare ground. Many of these wild bees are better pollinators of particular crops than honeybees are, because they visit flowers faster or carry pollen loosely on their bodies, where it rubs off easily. Farmers, however, cannot order wild bees by the truckload. Honeybee hives can be moved, and each February beekeepers haul hives from across the United States to California''s almond orchards, which bloom all at once and depend on visiting bees to set a crop.', 'Bees and Pollination'),
  ('p24', 'Bats are nocturnal animals that navigate and hunt in total darkness using a biological sonar system called echolocation. A bat emits high-pitched sound pulses — far beyond the range of human hearing — that travel outward and bounce off objects in the environment. The returning echoes reach the bat''s large, highly sensitive ears, providing detailed information about the size, distance, shape, and even texture of nearby objects. This system is so precise that a bat can detect and catch a moth in complete darkness while avoiding obstacles thinner than a wire. Scientists have studied echolocation extensively, and insights from this research have contributed to the development of sonar and radar technology used by ships and aircraft.

Producing the sound is the easy part; hearing the answer is not. A bat''s outgoing pulse is loud enough to damage its own hearing, so tiny muscles in the middle ear tighten an instant before each call and release in time to catch the returning echo, a cycle repeated many times a second. As a bat closes on prey, it calls faster and faster, until the separate pulses run together into what researchers call a terminal buzz and the picture of the target refreshes almost continuously. Many moths have an answer of their own: some hear the approaching calls and fold their wings to drop out of the air, so the hunt is a contest rather than a certainty.', 'How Bats Use Echolocation'),
  ('p25', 'Democracy — the system of government in which citizens hold political power — traces its origins to ancient Athens, Greece, in the late 6th century BCE (around 508 BCE). Athenian statesman Cleisthenes introduced reforms that gave citizens a direct voice in governing the city-state, replacing the rule of aristocrats with a system called direct democracy. In this system, eligible citizens gathered in an assembly and voted on laws and policies themselves, rather than electing representatives. However, participation was limited: women, enslaved people, and foreigners were excluded. Despite these flaws, ancient Athens established the foundational idea that ordinary people, not only kings or nobles, had the right to shape their own government.

What made the system unusual was not only who voted but how offices were filled. Citizens assembled in the open air on a hillside to debate and decide, and any of them was entitled to stand up and speak. Most public positions were not won by election, which Athenians associated with wealth and reputation, but assigned by lot, so that ordinary farmers and craftsmen took turns running the city''s daily business. A council chosen the same way prepared the assembly''s agenda. Citizens could also vote to banish a man from the city for ten years without accusing him of any crime, a procedure meant to check anyone who seemed to be gathering too much personal power.', 'Democracy in Ancient Athens')
),
q(pkey, prompt, options, correct_index, difficulty, explanation) AS (VALUES
  ('p01', 'Based on the passage, why would water pumped out of a deep aquifer be harder to replace than water taken from a river?', '["Aquifer water evaporates before it can be used", "Rivers receive more precipitation than aquifers do", "Underground water rejoins the cycle far more slowly", "Groundwater is not part of the water cycle at all"]'::JSONB, 2, 3, 'The passage says water in an aquifer may remain there for thousands of years, while water in the atmosphere returns as precipitation in about nine days. Combining those facts, aquifer water is not refilled on any timescale useful to people, while river water is resupplied quickly by ongoing rain and snow.'),
  ('p01', 'Why does the author contrast nine days in the atmosphere with thousands of years underground?', '["To show that the same cycle runs at very different speeds in different places", "To argue that groundwater is cleaner than water in rivers", "To prove that the atmosphere holds most of Earth''s water", "To explain the steps by which glaciers are formed"]'::JSONB, 0, 2, 'The two figures are set side by side as extremes, and the paragraph closes by stating that the cycle''s pace varies from one storage place to the next. The contrast is the evidence the author uses to make that general point concrete.'),
  ('p02', 'What does the comparison of British and American Sign Language suggest?', '["A sign language is a signed version of the spoken language around it", "British Sign Language developed earlier than American Sign Language", "Signers from different countries can never communicate with one another", "A shared spoken language does not mean two countries share a sign language"]'::JSONB, 3, 2, 'Britain and the United States both speak English, yet signers from the two countries often cannot follow each other. That gap only makes sense if a sign language grows out of its own community rather than out of the surrounding speech, which also rules out the first option.'),
  ('p02', 'Why does the author describe a signer placing something at a spot in space and later pointing back to it?', '["To show that signing is slower than speaking", "To give a concrete example of grammar that speech cannot easily reproduce", "To explain how beginners are taught their first signs", "To suggest that sign languages rely mostly on gesture"]'::JSONB, 1, 3, 'The example comes directly after the claim that sign languages use grammatical tools speech cannot copy, and it supplies the evidence for that claim. It supports the passage''s larger argument that these are independent languages, not versions of speech.'),
  ('p03', 'Based on the second paragraph, what did bebop musicians value more than the swing bands before them?', '["Musical experimentation, even at the cost of danceability", "Larger ensembles with fully written parts", "Returning jazz to the sound of its New Orleans beginnings", "Reaching the widest possible audience"]'::JSONB, 0, 3, 'Bebop is described as smaller, faster, and much harder to dance to, which is the opposite of what filled the swing dance halls. Choosing that difficulty while giving up the dance floor shows the players cared more about pushing the music forward than about pleasing a crowd.'),
  ('p03', 'Why does the author mention that each new style drew complaints from listeners?', '["To argue that early jazz was the finest form of the music", "To show that most audiences eventually abandoned jazz", "To acknowledge resistance while making the case that change sustained jazz", "To explain why jazz musicians stopped improvising"]'::JSONB, 2, 2, 'The complaints are raised and then answered in the same sentence by the word "yet." The author admits each change upset some listeners in order to strengthen the point that follows: a music willing to keep changing is a music that survives.'),
  ('p04', 'Why was an inscription written in three languages so useful to the scholars described in the second paragraph?', '["It was the only cuneiform text that had survived a fire", "A language they could already partly read gave them a key to the unknown signs", "It proved that cuneiform was used for royal announcements", "It showed that the Akkadians and Hittites spoke related languages"]'::JSONB, 1, 3, 'The passage says the ability to read cuneiform had been lost, and that one of the three languages was already partly understood. Put together, the known version told scholars what the message said, so they could work out which unfamiliar signs carried which meanings.'),
  ('p04', 'How does the second paragraph relate to the first?', '["It disputes the claim that cuneiform began as a record-keeping system", "It shifts the focus to the geography of the Tigris and Euphrates", "It repeats the first paragraph''s points using different examples", "It follows what became of cuneiform after the society that created it"]'::JSONB, 3, 2, 'The first paragraph explains how cuneiform was invented and how its uses widened. The second picks up afterward: other peoples adopted the script, the tablets survived in the ground, and modern scholars had to rediscover how to read them.'),
  ('p05', 'Based on the second paragraph, why is telling a teenager to simply go to bed earlier likely to have limited effect?', '["Teenagers require less sleep than younger children do", "Homework keeps most teenagers busy until very late", "Their bodies do not send the sleepiness signal until later at night", "Sleep lost during the week can be recovered on the weekend"]'::JSONB, 2, 2, 'The paragraph says melatonin, which produces the feeling of sleepiness, is released later during adolescence. Lying down earlier does not move that release, so the teenager is likely to be awake in bed — the obstacle is biological rather than a matter of effort.'),
  ('p05', 'Why does the author bring up school districts that moved their start times later?', '["To show a practical response to the mismatch between teenage biology and school schedules", "To criticize teachers for scheduling classes badly", "To indicate that most schools have already fixed the problem", "To suggest that teenagers are sleeping more than they need to"]'::JSONB, 0, 3, 'The paragraph first sets up a conflict: teenage bodies want a later night, but school begins early. The districts are introduced afterward as an example of acting on that conflict, and the reported gains suggest the problem can be addressed by changing the schedule rather than the students.'),
  ('p06', 'Taking both paragraphs together, what pattern do the ancient and modern Olympics share?', '["Each version kept the same set of events it began with", "Each version grew only when a government agreed to pay", "Both began small and grew to include more events and people", "Both were at their most fiercely competitive at the start"]'::JSONB, 2, 3, 'The first paragraph says the ancient Games opened with a single footrace and later added wrestling, chariot racing, and the discus. The second says the modern Games opened with about 240 men from 14 nations and later added women, winter sports, and thousands of competitors. Neither paragraph states the pattern outright; you have to line the two accounts up to see that both started narrow and widened.'),
  ('p06', 'Why does the author give the number of athletes and nations at the 1896 Athens Games?', '["To provide a measuring stick that shows how much the Games later grew", "To prove that Athens was a poor choice of host city", "To explain why women were not allowed to compete in 1896", "To argue that the earliest modern Games were the most authentic"]'::JSONB, 0, 2, 'The passage already says the Games now include thousands of athletes from every nation. A small, specific figure from 1896 turns that vague claim into a comparison a reader can feel. The author is supplying a baseline, not judging the host city or the rules of the day.'),
  ('p07', 'What does the second paragraph suggest would most likely have happened if one company had owned the internet''s protocols?', '["The internet would have reached poor countries sooner", "Fewer outsiders could have built on the network freely", "The World Wide Web would have been invented earlier", "Governments would have refused to fund ARPANET"]'::JSONB, 1, 3, 'The paragraph says growth depended on rules no one owns, and that any company could write a browser or run a server so long as it followed the shared standards. Reverse that condition and permission becomes something a single owner grants or withholds, which would have narrowed who could build. The passage never says this directly; it is what the stated condition implies.'),
  ('p07', 'Why does the author include the estimate that about a third of the world''s people have never been online?', '["To show that the internet is losing users in wealthy nations", "To argue that inventing the World Wide Web was a mistake", "To explain how the early protocols were standardized", "To qualify the picture of an internet that everyone uses"]'::JSONB, 3, 2, 'The first paragraph closes on billions of daily users, which can leave the impression of universal access. The figure arrives right after the statement that access has never been equal, so it works as a correction to that impression rather than as criticism of the Web itself.'),
  ('p08', 'Based on the passage, why can a fall in a community''s vaccination rate endanger someone who cannot be vaccinated at all?', '["That person depends on the pathogen running out of hosts among the immune", "Unvaccinated people give off antibodies that cancel others'' immunity", "Vaccines lose their strength when fewer people receive them", "The pathogen mutates each time it meets a vaccinated person"]'::JSONB, 0, 3, 'The passage says outbreaks fizzle out when enough of a community is immune because the pathogen struggles to find new hosts, and that this is what shields people who cannot be vaccinated. Their safety therefore rests entirely on other people''s immunity, so lowering coverage removes the only barrier they have. Nothing in the passage supports vaccines weakening or antibodies passing between people.'),
  ('p08', 'Why does the author bring up smallpox at the end of the passage?', '["To warn that some diseases cannot be stopped by vaccines", "To explain how immunological memory was first discovered", "To offer concrete proof of what wide vaccination can achieve", "To compare the smallpox vaccine with the measles vaccine"]'::JSONB, 2, 2, 'Everything before it explains how vaccination is supposed to work. Smallpox is the one case where that process ran to completion worldwide, so it serves as evidence that the mechanism described actually delivers results, not as a caution or a comparison.'),
  ('p09', 'What does the second paragraph suggest about why so many rivals kept suing Bell''s company?', '["They believed the courts were biased against all inventors", "They wanted Bell forced to publish how the telephone worked", "They hoped judges would move the patent''s expiration date up", "Control of the patent was worth an enormous amount of money"]'::JSONB, 3, 3, 'The paragraph calls the patent one of the most valuable ever granted and notes that independent companies rushed in the moment it expired in 1894. Put those two facts together and the motive behind hundreds of lawsuits becomes financial: whoever held the patent held the business. The motive is never stated, and nothing suggests biased courts or a demand for disclosure.'),
  ('p09', 'How does the second paragraph of this passage relate to the first paragraph?', '["It contradicts the first by showing Bell did not invent the telephone", "It follows the patent forward to show what Bell''s filing was worth", "It changes topic to the daily lives of telephone customers", "It repeats the first paragraph''s account of Bell''s first call"]'::JSONB, 1, 2, 'The first paragraph ends with Bell winning the patent by hours. The second picks up that same patent and traces its later history through the lawsuits, the Supreme Court ruling, and its expiration, showing the reader why those few hours mattered so much. It extends the first paragraph rather than contradicting or repeating it.'),
  ('p10', 'How does the speed at which bacteria divide help explain how quickly resistance appears?', '["Faster division makes each cell harder for a drug to enter", "Rapid division uses up the antibiotic before it can act", "Many generations pass quickly, so a rare survivor''s trait spreads fast", "Dividing bacteria cannot be counted, so doctors misjudge the dose"]'::JSONB, 2, 3, 'The passage supplies two pieces separately: bacteria divide about every twenty minutes, and the few survivors of a drug pass the trait to their descendants. Combining them explains the speed, since a twenty-minute generation lets an advantage that starts in a handful of cells take over a population in days. The other choices describe effects the passage never claims.'),
  ('p10', 'Why does the author mention Fleming''s 1945 Nobel lecture?', '["To show the danger was recognized from the drug''s earliest days", "To credit Fleming with curing the first resistant infection", "To explain how penicillin is manufactured from mold", "To suggest that Fleming opposed the use of antibiotics"]'::JSONB, 0, 2, 'Placing the warning from the drug''s own discoverer just before the note that resistant infections appeared within a few years makes the point that resistance was predicted, not stumbled upon. Fleming is used as a witness to the risk, not as an opponent of the medicine he discovered.'),
  ('p11', 'Two neighborhoods in the same city record different temperatures on the same summer afternoon. Based on the passage, the difference is most likely explained by', '["how far each neighborhood sits from the countryside", "how recently each neighborhood was built", "how much of each neighborhood is shaded rather than paved", "how many people live in each neighborhood"]'::JSONB, 2, 3, 'The passage says dark, paved surfaces store heat while natural surfaces cool faster, and that tree-shaded blocks measure cooler than paved ones. Combining these, the surface cover of a block — not its population or its distance from farmland — is what drives the temperature gap. Every neighborhood in one city gets the same hours of daylight, so option B cannot explain a same-day difference.'),
  ('p11', 'Why does the author describe temperature measurements taken block by block within a single city?', '["To show that the effect varies inside a city, not only between city and country", "To prove that rural land is actually hotter than the city center in summer", "To explain how scientists first learned that asphalt absorbs solar energy", "To argue that cities should stop building new roads and parking lots entirely"]'::JSONB, 0, 2, 'The first paragraph frames the heat island as a city-versus-countryside contrast. The block-by-block measurements complicate that picture by showing the effect also varies street to street, which sets up the point that the hottest blocks and the most heat-vulnerable residents often overlap.'),
  ('p12', 'Based on the passage, which seller could raise prices with the smallest drop in the amount customers buy?', '["A restaurant that serves dinner to families on weekends", "A theater selling tickets to an upcoming concert", "A candy company competing with many similar brands", "The only company supplying water to a town"]'::JSONB, 3, 2, 'A seller whose buyers have nowhere else to go can raise its price without losing much business. The passage makes that point about goods with no easy substitute; a town''s sole water supplier is such a seller, while diners, concert-goers and candy buyers can all choose something else.'),
  ('p12', 'How does the second paragraph relate to the paragraph before it?', '["It replaces the first paragraph''s explanation with a newer economic theory", "It adds limits to the rule by showing buyers react differently to different goods", "It repeats the first paragraph''s examples using products from other countries", "It traces the history of how economists first discovered the law of demand"]'::JSONB, 1, 3, 'The first paragraph states supply and demand as a general rule. The second does not overturn that rule — prices still respond to demand — but qualifies it by showing how strongly buyers respond depends on the product and on what buyers expect. That is a refinement, not a replacement.'),
  ('p13', 'The passage suggests that the greatest danger of marine heat waves becoming more frequent is that', '["reefs are struck again before they have had time to rebuild", "corals permanently lose the ability to take in any algae", "the fish that shelter on reefs begin to feed on coral instead", "coral nurseries can no longer grow fragments in ocean water"]'::JSONB, 0, 3, 'Two facts must be combined: recovery requires a long stretch of cool water because corals rebuild only about a centimeter a year, and heat waves that were once decades apart now return within a few years. Frequency is therefore the problem — the interval between shocks has become shorter than the time recovery takes.'),
  ('p13', 'Why does the author mention underwater nurseries and heat-tolerant breeding?', '["To argue that reefs are no longer at risk from warming water", "To prove that the problem of coral bleaching has been solved", "To show that scientists are responding, but only at small scale", "To explain how corals and algae first began living together"]'::JSONB, 2, 2, 'The author reports these efforts and then immediately notes they cover only small sections of reef. The point is balance: people are acting, but the response is not yet large enough to match the threat described earlier, so the passage neither despairs nor claims the danger is over.'),
  ('p14', 'A person looks for a red jacket in a room lit only by moonlight and cannot tell its color. Based on the passage, this is because', '["the jacket stops reflecting red light once the room is dark", "the jacket still reflects red light, but the eye cannot report it", "the cones in the eye work better in darkness than in daylight", "the rods will identify the color once the eyes fully adjust"]'::JSONB, 1, 2, 'The passage says objects in a dim room reflect the same wavelengths they did at noon, and that dim-light vision depends on rods, which cannot distinguish wavelengths. The light leaving the jacket is unchanged; what fails is the eye''s ability to sort wavelengths, so option D is wrong no matter how long the eyes adjust.'),
  ('p14', 'Why does the author include the information about birds and ultraviolet light?', '["To argue that bird vision is more accurate than human vision", "To explain how rods and cones first developed in animals", "To suggest humans may someday grow a fourth type of cone", "To show that what an eye sees depends on the cones it has"]'::JSONB, 3, 3, 'The bird example extends the passage''s central claim. If three cone types produce the colors humans see, then a fourth cone type must produce something more — which shows color is not a fixed property of the world but a product of the detectors an animal happens to carry.'),
  ('p15', 'Why would day length be a more useful migration signal than temperature for a bird like the godwit?', '["Temperature is physically harder for a small bird to sense", "Day length also tells the bird which direction it should fly", "Day length changes on a fixed schedule, allowing preparation in advance", "Warm weather makes it impossible for a bird to store body fat"]'::JSONB, 2, 3, 'The godwit must nearly double its weight and reshape its organs weeks before departure, while the weather at home is still pleasant. A cue that arrives only when it turns cold would come too late; day length shifts the same way every year, so it warns the bird early enough to prepare.'),
  ('p15', 'Why does the author describe the bar-tailed godwit''s flight in the second paragraph?', '["To give a concrete example of how demanding migration can be", "To argue that godwits navigate more skillfully than any other bird", "To explain why certain bird species do not migrate at all", "To show that satellite tags have replaced every older research method"]'::JSONB, 0, 2, 'The first paragraph makes general claims about journeys of thousands of miles. The godwit gives those claims a specific, measurable form — a named species, a distance, a span of days — which makes the demands of migration concrete rather than abstract.'),
  ('p16', 'The gray square example and the white paper example together suggest that the brain judges a color mainly by', '["measuring light more precisely than instruments can", "comparing it with whatever surrounds it", "the emotion the color produces in the viewer", "ignoring the lighting an object sits in"]'::JSONB, 1, 3, 'Neither example can be answered alone. The gray square changes appearance when its background changes, and the paper keeps its appearance when the lighting changes. Both results only make sense if the brain is judging the color against its surroundings rather than reading the light by itself.'),
  ('p16', 'Why does the author contrast color studies done in a laboratory with results in real stores?', '["To prove that color has no effect on shoppers", "To explain how stores choose their lighting", "To argue that laboratory research should be abandoned", "To show that color''s influence has limits"]'::JSONB, 3, 2, 'The passage still treats color effects as real, so the contrast is not a denial of them. It is a qualification: in a store, color competes with price, packaging, and placement, so the author uses the comparison to keep the reader from overestimating what color alone can do.'),
  ('p17', 'What does the outcome of the 1976 voyage suggest about the claim that the islands were settled by accident?', '["It was confirmed, since the canoe drifted from its route", "It cannot be judged from a single voyage", "It looks weaker, because a distant target was reached on purpose", "It applies only to voyages shorter than 2,500 miles"]'::JSONB, 2, 3, 'The accident explanation assumes no one could steer that far deliberately. A canoe with no instruments that aimed at Tahiti and arrived there shows the crossing was within reach of skilled navigation, which undercuts the assumption the claim rests on.'),
  ('p17', 'What is the relationship between the second paragraph and the first?', '["It puts the first paragraph''s skills to a modern test", "It corrects errors in the first paragraph''s account of the cues", "It compares Pacific and European navigation methods", "It explains how those navigation methods were invented"]'::JSONB, 0, 2, 'The first paragraph describes the wayfinding system; the second shows that system being used in 1976 to cross an ocean. The author moves from explaining the practice to demonstrating that it works, rather than revising or comparing anything.'),
  ('p18', 'The passage suggests that how many people die in an earthquake depends most on', '["how far the shaking begins from a plate boundary", "how ready the area''s buildings and people are", "how many centimeters the plates move each year", "how quickly scientists issue a warning"]'::JSONB, 1, 3, 'The passage says warning is not possible and then notes that two quakes of the same size can have very different death tolls depending on the buildings involved. Putting those together, the difference has to come from preparation, not from prediction or from the size of the quake.'),
  ('p18', 'Why does the author mention flexible joints in gas and water lines?', '["To explain how gas and water reach homes", "To suggest that pipelines cause most earthquake damage", "To argue that safer buildings cost too much", "To give a concrete example of designing for shaking"]'::JSONB, 3, 2, 'The detail appears in a list of preparations engineers make. It is not about plumbing or cost; it is a specific, easily pictured instance of the general point that structures can be built to survive movement instead of resisting it rigidly.'),
  ('p19', 'Based on the passage, a memory that a person has recalled many times is likely to be', '["certain to be more accurate than a rarely recalled one", "permanently fixed once it has been recalled", "easier to retrieve but open to change", "stored outside the cerebral cortex"]'::JSONB, 2, 3, 'Two statements have to be combined: recalling a memory strengthens the path back to it, and each recall rebuilds the memory in a form that later information can alter. Practice therefore improves access without guaranteeing that the content stays the same.'),
  ('p19', 'The author includes the filmed-accident experiment mainly to', '["show that recall can absorb information added later", "prove that eyewitness reports should never be believed in court", "explain how the amygdala responds to danger", "describe how films are used to train police"]'::JSONB, 0, 2, 'The experiment is offered as evidence for the claim just before it, that recall rebuilds a memory rather than replaying it. The leading questions supply new material, and it turns up in the recalled version, which is exactly the point the author needs to support.'),
  ('p20', 'Sonar would be far less useful for measuring depth if', '["the water above the seafloor were unusually clear", "the speed of sound in seawater varied unpredictably", "the pulse were too high for people to hear", "the seafloor were made of rock rather than sand"]'::JSONB, 1, 3, 'The method converts a measured time into a distance, which only works because the speed is known in advance. If that speed changed unpredictably, the same travel time could mean many different depths, and the timing would no longer tell the crew anything reliable.'),
  ('p20', 'The author describes the bat and the dolphin after the sonar example in order to', '["suggest that sonar was copied directly from bats", "argue that animals hear better than any machine", "show the same principle at work in living creatures", "explain why certain animals hunt after dark"]'::JSONB, 2, 2, 'The paragraph ends by insisting that nothing unusual is happening in any of these cases. Placing animals beside the machine lets the author show that one physical rule about echoes covers both, which is a stronger point than praising either one.'),
  ('p21', 'The passage suggests that if massive stars never exploded,', '["the universe would contain no hydrogen or helium", "black holes would be far more common than they are", "heavier elements would remain locked inside stars", "stars would live much longer than they now do"]'::JSONB, 2, 3, 'Fusion builds carbon, oxygen, and iron inside a star, and the explosion is what scatters them into the surrounding gas and dust. Remove the explosion and the elements would still be made, but they would have no way out, so they could never end up in bones or in the air.'),
  ('p21', 'Why does the author mention the calcium in bones and the oxygen in a breath?', '["To connect the life cycle of stars to the reader''s own body", "To warn that a distant supernova could injure people", "To explain how the human body produces its energy", "To show that astronomers also study medicine"]'::JSONB, 0, 2, 'Up to that point the passage describes events at enormous distances. Naming two substances the reader carries around converts an abstract claim about element formation into something personal, which is why it follows immediately after the sentence about supernova debris.'),
  ('p22', 'The results of the payment experiment suggest that a person is most likely to change what they believe when they:', '["are offered a large enough reward to act against that belief", "cannot point to an outside reason for how they behaved", "are corrected by an expert they already trust", "have never thought carefully about the belief before"]'::JSONB, 1, 3, 'The volunteers paid twenty dollars could explain their words by pointing to the money, so their opinion of the task did not have to move. The volunteers paid one dollar had no such excuse, and the passage says the easiest remaining way to remove the inconsistency was to revise the opinion itself. Combining the two results gives the general rule: belief shifts when no outside justification is available.'),
  ('p22', 'The author contrasts the twenty-dollar group with the one-dollar group mainly to:', '["show why one group felt an inconsistency and the other did not", "criticize the ethics of Festinger''s experiment on volunteers", "argue that people work more honestly when they are paid less", "explain what made the hour-long task so dull and repetitive"]'::JSONB, 0, 2, 'The two payments are set side by side because the size of the payment is what decides whether a conflict exists. The larger sum supplies a ready explanation for the lie; the smaller one does not. The contrast is there to demonstrate Festinger''s mechanism, not to judge the experiment or the pay.'),
  ('p23', 'The passage suggests that growers rely on honeybees rather than wild bees mainly because honeybees:', '["are more efficient pollinators than any wild bee species", "can be carried to a crop at the moment it flowers", "are the only insects that visit orchard blossoms", "are less affected by pesticides and habitat loss"]'::JSONB, 1, 3, 'The passage says many wild bees are actually the better pollinators, yet farmers cannot order them by the truckload, while honeybee hives are hauled across the country to arrive for the almond bloom. Putting those two statements together, the advantage that matters is transportability, not pollinating skill.'),
  ('p23', 'The author points out that many wild bees outperform honeybees in order to:', '["suggest that beekeeping does more harm than good", "explain how honeybees turn flower nectar into honey", "show that pollination rests on more than the familiar hive", "argue that almond growers are wasting their money"]'::JSONB, 2, 2, 'The detail corrects the common assumption that a hive is the whole picture: thousands of solitary species do this work too, and some do it better. The author is widening the reader''s sense of what pollination depends on, not attacking beekeepers or almond growers.'),
  ('p24', 'Based on the passage, the muscles in a bat''s middle ear are working hardest when the bat is:', '["seconds away from seizing a moth", "hanging quietly in its roost by day", "gliding across open ground with nothing nearby", "listening for calls made by other bats"]'::JSONB, 0, 3, 'The muscles must tighten and release once for every call the bat makes, and the passage says the calling rate climbs to a terminal buzz as the bat closes on prey. Combining those facts, the moment just before capture is when the cycle repeats fastest, so the ear muscles are most active then.'),
  ('p24', 'The author describes moths that fold their wings and drop chiefly to:', '["prove that echolocation seldom works as intended", "suggest that moths hear better than bats do", "explain why bats choose to hunt after dark", "show that a bat''s prey are not defenseless"]'::JSONB, 3, 2, 'The detail is offered as the moths'' ''answer of their own,'' and the paragraph ends by calling the hunt a contest rather than a certainty. The point is that prey can respond to echolocation, which qualifies the picture of an unbeatable hunter without denying how precise the system is.'),
  ('p25', 'The Athenians'' preference for the lot over elections suggests that they:', '["doubted that ordinary citizens could govern at all", "lacked any reliable method of counting votes", "expected elections to favor the already powerful", "wanted trained specialists in every public post"]'::JSONB, 2, 3, 'The passage says Athenians associated election with wealth and reputation, and that the lot let ordinary farmers and craftsmen take a turn. If elections were thought to reward the wealthy and well known, drawing lots is the remedy — a way of keeping office from settling on the same prominent men.'),
  ('p25', 'The author includes the practice of banishment mainly to:', '["argue that Athenian justice was arbitrary and cruel", "explain how Athens punished citizens who broke laws", "show that the assembly could rarely reach agreement", "show how the city guarded against one man''s power"]'::JSONB, 3, 2, 'The passage states that no crime had to be charged and that the point was to check anyone gathering too much personal power. The detail therefore illustrates a safeguard built into the system, which is why it sits alongside the lot and the open assembly rather than in a discussion of crime.')
)
INSERT INTO questions (id, section, passage, passage_title, prompt, options, correct_index, difficulty, explanation)
SELECT md5('reading' || '|' || q.prompt)::UUID, 'reading'::section_type, p.body, p.title,
       q.prompt, q.options, q.correct_index, q.difficulty, q.explanation
FROM q JOIN p ON p.pkey = q.pkey
ON CONFLICT (id) DO NOTHING;

-- ── Group the new rows onto the existing passage_id ─────────────────────────
-- Same block migrations 014 and 020 use: a passage that already has an id keeps
-- it, so the new questions join the passage they belong to.
DO $$
DECLARE rec RECORD; new_id UUID;
BEGIN
  FOR rec IN SELECT DISTINCT passage FROM questions WHERE passage IS NOT NULL AND passage_id IS NULL LOOP
    SELECT passage_id INTO new_id FROM questions WHERE passage = rec.passage AND passage_id IS NOT NULL LIMIT 1;
    IF new_id IS NULL THEN new_id := gen_random_uuid(); END IF;
    UPDATE questions SET passage_id = new_id WHERE passage = rec.passage AND passage_id IS NULL;
  END LOOP;
END $$;

-- ── Verification: expect 50 rows ─────────────────────────────────────
SELECT '034 reading' AS migration, COUNT(*)::TEXT AS present, '50' AS expected
FROM questions
WHERE id IN (
  md5('reading' || '|' || 'Based on the passage, why would water pumped out of a deep aquifer be harder to replace than water taken from a river?')::UUID,
  md5('reading' || '|' || 'Why does the author contrast nine days in the atmosphere with thousands of years underground?')::UUID,
  md5('reading' || '|' || 'What does the comparison of British and American Sign Language suggest?')::UUID,
  md5('reading' || '|' || 'Why does the author describe a signer placing something at a spot in space and later pointing back to it?')::UUID,
  md5('reading' || '|' || 'Based on the second paragraph, what did bebop musicians value more than the swing bands before them?')::UUID,
  md5('reading' || '|' || 'Why does the author mention that each new style drew complaints from listeners?')::UUID,
  md5('reading' || '|' || 'Why was an inscription written in three languages so useful to the scholars described in the second paragraph?')::UUID,
  md5('reading' || '|' || 'How does the second paragraph relate to the first?')::UUID,
  md5('reading' || '|' || 'Based on the second paragraph, why is telling a teenager to simply go to bed earlier likely to have limited effect?')::UUID,
  md5('reading' || '|' || 'Why does the author bring up school districts that moved their start times later?')::UUID,
  md5('reading' || '|' || 'Taking both paragraphs together, what pattern do the ancient and modern Olympics share?')::UUID,
  md5('reading' || '|' || 'Why does the author give the number of athletes and nations at the 1896 Athens Games?')::UUID,
  md5('reading' || '|' || 'What does the second paragraph suggest would most likely have happened if one company had owned the internet''s protocols?')::UUID,
  md5('reading' || '|' || 'Why does the author include the estimate that about a third of the world''s people have never been online?')::UUID,
  md5('reading' || '|' || 'Based on the passage, why can a fall in a community''s vaccination rate endanger someone who cannot be vaccinated at all?')::UUID,
  md5('reading' || '|' || 'Why does the author bring up smallpox at the end of the passage?')::UUID,
  md5('reading' || '|' || 'What does the second paragraph suggest about why so many rivals kept suing Bell''s company?')::UUID,
  md5('reading' || '|' || 'How does the second paragraph of this passage relate to the first paragraph?')::UUID,
  md5('reading' || '|' || 'How does the speed at which bacteria divide help explain how quickly resistance appears?')::UUID,
  md5('reading' || '|' || 'Why does the author mention Fleming''s 1945 Nobel lecture?')::UUID,
  md5('reading' || '|' || 'Two neighborhoods in the same city record different temperatures on the same summer afternoon. Based on the passage, the difference is most likely explained by')::UUID,
  md5('reading' || '|' || 'Why does the author describe temperature measurements taken block by block within a single city?')::UUID,
  md5('reading' || '|' || 'Based on the passage, which seller could raise prices with the smallest drop in the amount customers buy?')::UUID,
  md5('reading' || '|' || 'How does the second paragraph relate to the paragraph before it?')::UUID,
  md5('reading' || '|' || 'The passage suggests that the greatest danger of marine heat waves becoming more frequent is that')::UUID,
  md5('reading' || '|' || 'Why does the author mention underwater nurseries and heat-tolerant breeding?')::UUID,
  md5('reading' || '|' || 'A person looks for a red jacket in a room lit only by moonlight and cannot tell its color. Based on the passage, this is because')::UUID,
  md5('reading' || '|' || 'Why does the author include the information about birds and ultraviolet light?')::UUID,
  md5('reading' || '|' || 'Why would day length be a more useful migration signal than temperature for a bird like the godwit?')::UUID,
  md5('reading' || '|' || 'Why does the author describe the bar-tailed godwit''s flight in the second paragraph?')::UUID,
  md5('reading' || '|' || 'The gray square example and the white paper example together suggest that the brain judges a color mainly by')::UUID,
  md5('reading' || '|' || 'Why does the author contrast color studies done in a laboratory with results in real stores?')::UUID,
  md5('reading' || '|' || 'What does the outcome of the 1976 voyage suggest about the claim that the islands were settled by accident?')::UUID,
  md5('reading' || '|' || 'What is the relationship between the second paragraph and the first?')::UUID,
  md5('reading' || '|' || 'The passage suggests that how many people die in an earthquake depends most on')::UUID,
  md5('reading' || '|' || 'Why does the author mention flexible joints in gas and water lines?')::UUID,
  md5('reading' || '|' || 'Based on the passage, a memory that a person has recalled many times is likely to be')::UUID,
  md5('reading' || '|' || 'The author includes the filmed-accident experiment mainly to')::UUID,
  md5('reading' || '|' || 'Sonar would be far less useful for measuring depth if')::UUID,
  md5('reading' || '|' || 'The author describes the bat and the dolphin after the sonar example in order to')::UUID,
  md5('reading' || '|' || 'The passage suggests that if massive stars never exploded,')::UUID,
  md5('reading' || '|' || 'Why does the author mention the calcium in bones and the oxygen in a breath?')::UUID,
  md5('reading' || '|' || 'The results of the payment experiment suggest that a person is most likely to change what they believe when they:')::UUID,
  md5('reading' || '|' || 'The author contrasts the twenty-dollar group with the one-dollar group mainly to:')::UUID,
  md5('reading' || '|' || 'The passage suggests that growers rely on honeybees rather than wild bees mainly because honeybees:')::UUID,
  md5('reading' || '|' || 'The author points out that many wild bees outperform honeybees in order to:')::UUID,
  md5('reading' || '|' || 'Based on the passage, the muscles in a bat''s middle ear are working hardest when the bat is:')::UUID,
  md5('reading' || '|' || 'The author describes moths that fold their wings and drop chiefly to:')::UUID,
  md5('reading' || '|' || 'The Athenians'' preference for the lot over elections suggests that they:')::UUID,
  md5('reading' || '|' || 'The author includes the practice of banishment mainly to:')::UUID
);
