-- 035 — Add 50 verbal questions
--
-- Pure insert, no passage. Ids are deterministic:
-- md5(section || '|' || prompt)::UUID with ON CONFLICT DO NOTHING, so
-- re-running this file is a no-op. Nothing existing is deleted or updated,
-- and user_question_history is never touched.

WITH q(prompt, options, correct_index, difficulty, explanation) AS (VALUES
  ('TIDY most nearly means:', '["Messy", "Neat", "Large", "Empty"]'::JSONB, 1, 1, 'Tidy describes something arranged in order and free of clutter, which is what neat means. Messy is its opposite.'),
  ('HALT most nearly means:', '["Begin", "Stop", "Hurry", "Turn"]'::JSONB, 1, 1, 'To halt is to bring motion to an end, so stop is the closest match. Begin is the opposite.'),
  ('AID most nearly means:', '["Harm", "Ask", "Leave", "Help"]'::JSONB, 3, 1, 'Aid means to give assistance to someone, which is exactly what help means. Harm is the opposite.'),
  ('ODD most nearly means:', '["Strange", "Ordinary", "Round", "Fair"]'::JSONB, 0, 1, 'Odd describes something unusual or out of the ordinary, so strange is the match. Ordinary is its opposite.'),
  ('VITAL most nearly means:', '["Optional", "Occasional", "Essential", "Gentle"]'::JSONB, 2, 2, 'Vital describes something absolutely necessary for life or success, so essential fits. Optional means the reverse — it can be skipped.'),
  ('MOCK most nearly means:', '["Praise", "Repeat", "Compliment", "Ridicule"]'::JSONB, 3, 2, 'To mock is to make fun of someone in a scornful way, which is what ridicule means. Praise and compliment go the other direction.'),
  ('BLUNDER most nearly means:', '["Victory", "Mistake", "Journey", "Promise"]'::JSONB, 1, 2, 'A blunder is a clumsy or careless error, so mistake is the closest word.'),
  ('TENACIOUS most nearly means:', '["Frightened", "Wealthy", "Persistent", "Careless"]'::JSONB, 2, 3, 'Tenacious describes someone who holds on and refuses to give up, which is what persistent means.'),
  ('AMPLE most nearly means:', '["Narrow", "Temporary", "Bitter", "Plentiful"]'::JSONB, 3, 3, 'Ample means more than enough of something, so plentiful is the match. Narrow suggests too little.'),
  ('WARY most nearly means:', '["Cautious", "Weary", "Cheerful", "Hasty"]'::JSONB, 0, 3, 'Wary means watchful of danger, so cautious is correct. Weary looks similar but means tired — a spelling trap.'),
  ('EMPTY is the opposite of:', '["Full", "Open", "Light", "Small"]'::JSONB, 0, 1, 'Empty means containing nothing; full means containing all it can hold, so full is the opposite.'),
  ('WEAK is the opposite of:', '["Soft", "Slender", "Thin", "Strong"]'::JSONB, 3, 1, 'Weak means lacking power or force, so its opposite is strong. Thin and slender describe size, not strength.'),
  ('BEGIN is the opposite of:', '["Start", "End", "Try", "Open"]'::JSONB, 1, 1, 'Begin means to start something, so its opposite is end. Start is a synonym, not an antonym.'),
  ('CHEAP is the opposite of:', '["Costly", "Common", "Broken", "Simple"]'::JSONB, 0, 1, 'Cheap means low in price, so its opposite is costly, meaning high in price.'),
  ('FRAGILE is the opposite of:', '["Delicate", "Sturdy", "Small", "Clear"]'::JSONB, 1, 2, 'Fragile means easily broken, so sturdy — strongly built — is the opposite. Delicate is a synonym.'),
  ('ABSENT is the opposite of:', '["Missing", "Late", "Quiet", "Present"]'::JSONB, 3, 2, 'Absent means not there; present means there. Missing is a synonym of absent, and late still means eventually present.'),
  ('RETREAT is the opposite of:', '["Withdraw", "Escape", "Advance", "Hide"]'::JSONB, 2, 2, 'To retreat is to move backward away from something, so advance — moving forward — is the opposite. Withdraw is a synonym.'),
  ('OBSCURE is the opposite of:', '["Vague", "Distant", "Clear", "Hidden"]'::JSONB, 2, 3, 'Obscure means hard to see or hard to understand, so clear is its opposite. Vague and hidden are synonyms of obscure.'),
  ('RESOLUTE is the opposite of:', '["Determined", "Wavering", "Honest", "Patient"]'::JSONB, 1, 3, 'Resolute means firmly decided, so wavering — going back and forth — is the opposite. Determined is a synonym.'),
  ('NOVICE is the opposite of:', '["Beginner", "Student", "Helper", "Expert"]'::JSONB, 3, 3, 'A novice is new at something; an expert has mastered it. Beginner is a synonym of novice.'),
  ('Hammer is to nail as screwdriver is to:', '["Wood", "Screw", "Toolbox", "Handle"]'::JSONB, 1, 1, 'A hammer is the tool made to drive a nail; a screwdriver is the tool made to drive a screw. Wood is the material, not the fastener.'),
  ('Baker is to bread as farmer is to:', '["Tractor", "Barn", "Crops", "Field"]'::JSONB, 2, 1, 'A baker produces bread; a farmer produces crops. A tractor is a tool and a barn or field is a place, not a product.'),
  ('Big is to small as heavy is to:', '["Weight", "Large", "Solid", "Light"]'::JSONB, 3, 1, 'Big and small are opposites, so the second pair must be opposites too: heavy and light.'),
  ('Thermometer is to temperature as scale is to:', '["Weight", "Height", "Time", "Speed"]'::JSONB, 0, 2, 'A thermometer is the instrument that measures temperature; a scale is the instrument that measures weight.'),
  ('Pebble is to boulder as puddle is to:', '["Rain", "Lake", "Mud", "Cloud"]'::JSONB, 1, 2, 'A pebble is a very small version of a boulder; a puddle is a very small version of a lake. The relationship is size within the same category.'),
  ('Deafening is to loud as scorching is to:', '["Cold", "Dry", "Hot", "Bright"]'::JSONB, 2, 2, 'Deafening is an extreme degree of loud; scorching is an extreme degree of hot. The relationship is intensity.'),
  ('Miser is to money as glutton is to:', '["Hunger", "Weight", "Manners", "Food"]'::JSONB, 3, 3, 'A miser is defined by an excessive relationship to money; a glutton is defined by an excessive relationship to food.'),
  ('Skeptic is to doubt as optimist is to:', '["Fear", "Hope", "Anger", "Sorrow"]'::JSONB, 1, 3, 'A skeptic is characterized by doubt; an optimist is characterized by hope. Each word names the attitude that defines the person.'),
  ('Apprentice is to master as sapling is to:', '["Seed", "Leaf", "Tree", "Forest"]'::JSONB, 2, 3, 'An apprentice is the immature stage that grows into a master; a sapling is the immature stage that grows into a tree. A seed comes earlier, not later.'),
  ('Confident is to arrogant as thrifty is to:', '["Bashful", "Trustworthy", "Stingy", "Wealthy"]'::JSONB, 2, 3, 'Arrogant is confidence carried to an unpleasant excess; stingy is thriftiness carried to an unpleasant excess.'),
  ('All whales are mammals. Shamu is a whale. Shamu is a mammal — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 0, 1, 'Every whale belongs to the group of mammals, and Shamu is a whale, so Shamu must be a mammal.'),
  ('No bicycles have engines. This vehicle has an engine. This vehicle is a bicycle — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 1, 1, 'Since no bicycle has an engine, anything with an engine cannot be a bicycle, so the statement is false.'),
  ('Some birds are blue. Pico is a bird. Pico is blue — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 2, 1, 'Only some birds are blue, so knowing Pico is a bird does not tell us which group he falls into. It is uncertain.'),
  ('Some jars in the pantry are empty. All jars in the pantry are glass. Some glass jars are empty — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 0, 2, 'The empty jars are pantry jars, and every pantry jar is glass, so those empty jars are glass jars. True.'),
  ('No mushrooms are plants. Some fungi are mushrooms. All fungi are plants — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 1, 2, 'The fungi that are mushrooms cannot be plants, so at least some fungi are not plants — which makes ''all fungi are plants'' false.'),
  ('All lifeguards can swim. Some campers can swim. Some campers are lifeguards — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 2, 2, 'Being able to swim does not make someone a lifeguard; the swimming campers might all be ordinary campers. The conclusion is uncertain.'),
  ('Some volunteers are nurses. All nurses are trained in first aid. Some volunteers are trained in first aid — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 0, 3, 'The volunteers who are nurses must be trained in first aid, since every nurse is. That guarantees at least some trained volunteers.'),
  ('All winners of the science fair built a model. No one who built a model used a kit. Some winners used a kit — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 1, 3, 'Winners all built models, and model builders never used kits, so no winner used a kit. The statement is false.'),
  ('Every guitarist in the band reads music. Some members of the band do not read music. Some members of the band are not guitarists — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 0, 3, 'Any member who cannot read music cannot be a guitarist, since all guitarists read music. So those members are non-guitarists.'),
  ('Some athletes are vegetarians. Some vegetarians are chefs. Some athletes are chefs — true, false, or uncertain?', '["True", "False", "Uncertain", "Neither"]'::JSONB, 2, 3, 'The vegetarians who are athletes and the vegetarians who are chefs may be entirely different people, so no overlap is guaranteed.'),
  ('Which word does NOT belong with the others: Rain, Cloud, Snow, Sleet?', '["Rain", "Cloud", "Snow", "Sleet"]'::JSONB, 1, 1, 'Rain, snow, and sleet are all forms of precipitation that fall to the ground. A cloud stays in the sky and does not fall.'),
  ('Which word does NOT belong with the others: Cube, Circle, Square, Triangle?', '["Cube", "Circle", "Square", "Triangle"]'::JSONB, 0, 1, 'Circle, square, and triangle are flat two-dimensional shapes. A cube is a three-dimensional solid.'),
  ('Which word does NOT belong with the others: Nurse, Doctor, Clinic, Dentist?', '["Nurse", "Doctor", "Clinic", "Dentist"]'::JSONB, 2, 1, 'Nurse, doctor, and dentist are people who work in health care. A clinic is a place, not a person.'),
  ('Which word does NOT belong with the others: Salmon, Trout, Mackerel, Dolphin?', '["Salmon", "Trout", "Mackerel", "Dolphin"]'::JSONB, 3, 2, 'Salmon, trout, and mackerel are fish. A dolphin lives in water too, but it is a mammal that breathes air.'),
  ('Which word does NOT belong with the others: Mile, Ounce, Pound, Ton?', '["Mile", "Ounce", "Pound", "Ton"]'::JSONB, 0, 2, 'Ounce, pound, and ton are all units of weight. A mile measures distance.'),
  ('Which word does NOT belong with the others: Praise, Insult, Compliment, Flatter?', '["Praise", "Insult", "Compliment", "Flatter"]'::JSONB, 1, 2, 'Praise, compliment, and flatter all mean to say approving things about someone. To insult is to say the opposite.'),
  ('Which word does NOT belong with the others: Sonnet, Haiku, Ballad, Novel?', '["Sonnet", "Haiku", "Ballad", "Novel"]'::JSONB, 3, 3, 'A sonnet, a haiku, and a ballad are all forms of poetry. A novel is a long work of prose.'),
  ('Which word does NOT belong with the others: Thrifty, Wasteful, Economical, Frugal?', '["Thrifty", "Wasteful", "Economical", "Frugal"]'::JSONB, 1, 3, 'Thrifty, economical, and frugal all describe someone careful with money or resources. Wasteful is the opposite.'),
  ('Which word does NOT belong with the others: Ocean, Peninsula, Island, Isthmus?', '["Ocean", "Peninsula", "Island", "Isthmus"]'::JSONB, 0, 3, 'A peninsula, an island, and an isthmus are landforms surrounded or nearly surrounded by water. The ocean is the body of water itself.'),
  ('Which word does NOT belong with the others: Biography, Diary, Fable, Memoir?', '["Biography", "Diary", "Fable", "Memoir"]'::JSONB, 2, 3, 'A biography, a diary, and a memoir all record real events in a real person''s life. A fable is an invented story.')
)
INSERT INTO questions (id, section, passage, prompt, options, correct_index, difficulty, explanation)
SELECT md5('verbal' || '|' || q.prompt)::UUID, 'verbal'::section_type, NULL,
       q.prompt, q.options, q.correct_index, q.difficulty, q.explanation
FROM q
ON CONFLICT (id) DO NOTHING;

-- ── Verification: expect 50 rows ─────────────────────────────────────
SELECT '035 verbal' AS migration, COUNT(*)::TEXT AS present, '50' AS expected
FROM questions
WHERE id IN (
  md5('verbal' || '|' || 'TIDY most nearly means:')::UUID,
  md5('verbal' || '|' || 'HALT most nearly means:')::UUID,
  md5('verbal' || '|' || 'AID most nearly means:')::UUID,
  md5('verbal' || '|' || 'ODD most nearly means:')::UUID,
  md5('verbal' || '|' || 'VITAL most nearly means:')::UUID,
  md5('verbal' || '|' || 'MOCK most nearly means:')::UUID,
  md5('verbal' || '|' || 'BLUNDER most nearly means:')::UUID,
  md5('verbal' || '|' || 'TENACIOUS most nearly means:')::UUID,
  md5('verbal' || '|' || 'AMPLE most nearly means:')::UUID,
  md5('verbal' || '|' || 'WARY most nearly means:')::UUID,
  md5('verbal' || '|' || 'EMPTY is the opposite of:')::UUID,
  md5('verbal' || '|' || 'WEAK is the opposite of:')::UUID,
  md5('verbal' || '|' || 'BEGIN is the opposite of:')::UUID,
  md5('verbal' || '|' || 'CHEAP is the opposite of:')::UUID,
  md5('verbal' || '|' || 'FRAGILE is the opposite of:')::UUID,
  md5('verbal' || '|' || 'ABSENT is the opposite of:')::UUID,
  md5('verbal' || '|' || 'RETREAT is the opposite of:')::UUID,
  md5('verbal' || '|' || 'OBSCURE is the opposite of:')::UUID,
  md5('verbal' || '|' || 'RESOLUTE is the opposite of:')::UUID,
  md5('verbal' || '|' || 'NOVICE is the opposite of:')::UUID,
  md5('verbal' || '|' || 'Hammer is to nail as screwdriver is to:')::UUID,
  md5('verbal' || '|' || 'Baker is to bread as farmer is to:')::UUID,
  md5('verbal' || '|' || 'Big is to small as heavy is to:')::UUID,
  md5('verbal' || '|' || 'Thermometer is to temperature as scale is to:')::UUID,
  md5('verbal' || '|' || 'Pebble is to boulder as puddle is to:')::UUID,
  md5('verbal' || '|' || 'Deafening is to loud as scorching is to:')::UUID,
  md5('verbal' || '|' || 'Miser is to money as glutton is to:')::UUID,
  md5('verbal' || '|' || 'Skeptic is to doubt as optimist is to:')::UUID,
  md5('verbal' || '|' || 'Apprentice is to master as sapling is to:')::UUID,
  md5('verbal' || '|' || 'Confident is to arrogant as thrifty is to:')::UUID,
  md5('verbal' || '|' || 'All whales are mammals. Shamu is a whale. Shamu is a mammal — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'No bicycles have engines. This vehicle has an engine. This vehicle is a bicycle — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'Some birds are blue. Pico is a bird. Pico is blue — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'Some jars in the pantry are empty. All jars in the pantry are glass. Some glass jars are empty — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'No mushrooms are plants. Some fungi are mushrooms. All fungi are plants — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'All lifeguards can swim. Some campers can swim. Some campers are lifeguards — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'Some volunteers are nurses. All nurses are trained in first aid. Some volunteers are trained in first aid — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'All winners of the science fair built a model. No one who built a model used a kit. Some winners used a kit — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'Every guitarist in the band reads music. Some members of the band do not read music. Some members of the band are not guitarists — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'Some athletes are vegetarians. Some vegetarians are chefs. Some athletes are chefs — true, false, or uncertain?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Rain, Cloud, Snow, Sleet?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Cube, Circle, Square, Triangle?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Nurse, Doctor, Clinic, Dentist?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Salmon, Trout, Mackerel, Dolphin?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Mile, Ounce, Pound, Ton?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Praise, Insult, Compliment, Flatter?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Sonnet, Haiku, Ballad, Novel?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Thrifty, Wasteful, Economical, Frugal?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Ocean, Peninsula, Island, Isthmus?')::UUID,
  md5('verbal' || '|' || 'Which word does NOT belong with the others: Biography, Diary, Fable, Memoir?')::UUID
);
