-- 036 — Add 50 quantitative questions
--
-- Pure insert, no passage. Ids are deterministic:
-- md5(section || '|' || prompt)::UUID with ON CONFLICT DO NOTHING, so
-- re-running this file is a no-op. Nothing existing is deleted or updated,
-- and user_question_history is never touched.

WITH q(prompt, options, correct_index, difficulty, explanation) AS (VALUES
  ('Look at this series: 6, 13, 20, 27, 34, ... What number should come next?', '["40", "41", "42", "44"]'::JSONB, 1, 1, 'Each term is 7 more than the one before: 6, 13, 20, 27, 34. So 34 + 7 = 41.'),
  ('Look at this series: 90, 81, 72, 63, ... What number should come next?', '["52", "53", "54", "56"]'::JSONB, 2, 1, 'Each term is 9 less than the one before: 90, 81, 72, 63. So 63 - 9 = 54.'),
  ('Look at this series: 2, 20, 200, 2000, ... What number should come next?', '["20000", "4000", "22000", "200000"]'::JSONB, 0, 1, 'Each term is 10 times the one before, so one more zero is added at every step: 2000 × 10 = 20000.'),
  ('Look at this series: 11, 15, 19, 23, 27, ... What number should come next?', '["29", "30", "33", "31"]'::JSONB, 3, 1, 'The terms go up by 4 each time: 11, 15, 19, 23, 27. So 27 + 4 = 31.'),
  ('Look at this series: 72, 66, 60, 54, ... What number should come next?', '["46", "47", "48", "50"]'::JSONB, 2, 1, 'Each term is 6 less than the one before: 72, 66, 60, 54. So 54 - 6 = 48.'),
  ('Look at this series: 7, 14, 28, 56, ... What number should come next?', '["63", "84", "118", "112"]'::JSONB, 3, 2, 'Each term is double the one before: 7, 14, 28, 56. So 56 × 2 = 112.'),
  ('Look at this series: 4, 7, 6, 9, 8, 11, 10, ... What number should come next?', '["13", "9", "12", "14"]'::JSONB, 0, 2, 'The steps alternate: add 3, subtract 1, add 3, subtract 1. The last step was a subtraction, so an addition comes next: 10 + 3 = 13.'),
  ('Look at this series: 2, 4, 8, 14, 22, 32, ... What number should come next?', '["40", "44", "42", "46"]'::JSONB, 1, 2, 'The differences are 2, 4, 6, 8, 10 - each one 2 larger than the last. The next difference is 12, so 32 + 12 = 44.'),
  ('Look at this series: 5, 10, 20, 35, 55, ... What number should come next?', '["70", "75", "80", "85"]'::JSONB, 2, 2, 'The differences are 5, 10, 15, 20 - each one 5 larger than the last. The next difference is 25, so 55 + 25 = 80.'),
  ('Look at this series: 3, 6, 18, 72, 360, ... What number should come next?', '["720", "1080", "1800", "2160"]'::JSONB, 3, 3, 'The multipliers grow one at a time: x2, x3, x4, x5. The next multiplier is 6, so 360 × 6 = 2160.'),
  ('Look at this series: 2, 4, 10, 28, 82, ... What number should come next?', '["244", "164", "238", "246"]'::JSONB, 0, 3, 'Each term is 3 times the previous term minus 2: 2x3-2=4, 4x3-2=10, 10x3-2=28, 28x3-2=82. So 82x3-2 = 244.'),
  ('Look at this series: 5, 7, 11, 19, 35, ... What number should come next?', '["51", "67", "69", "70"]'::JSONB, 1, 3, 'The differences double each time: 2, 4, 8, 16. The next difference is 32, so 35 + 32 = 67.'),
  ('Look at this series: 2, 9, 4, 18, 6, 27, 8, ... What number should come next?', '["10", "30", "36", "45"]'::JSONB, 2, 3, 'Two series are woven together. The 1st, 3rd, 5th and 7th terms are 2, 4, 6, 8; the 2nd, 4th and 6th are 9, 18, 27. The next term belongs to the second series: 27 + 9 = 36.'),
  ('Examine the figures described and find the best answer. Figure A is a rectangle 7 by 4. Figure B is a square with side 5.', '["Figure A has the greater area and the greater perimeter.", "Figure B has the greater area.", "The perimeters are equal.", "Figure B has the greater perimeter, but A has the greater area."]'::JSONB, 0, 1, 'A: area 7 × 4 = 28, perimeter 2(7+4) = 22. B: area 25, perimeter 20. A is larger both ways.'),
  ('Examine the figures described and find the best answer. Figure A is a square with side 10. Figure B is a rectangle 20 by 5.', '["Figure A has the greater area and the greater perimeter.", "The areas and the perimeters are equal.", "The areas are equal, but B has the greater perimeter.", "Figure B has the greater area."]'::JSONB, 2, 1, 'Both areas are 100 (10 × 10 and 20 × 5). Perimeters: 40 for the square and 2(20+5) = 50 for the rectangle. The longer, thinner shape needs more fence.'),
  ('Examine the figures described and find the best answer. Figure A is a triangle with base 8 and height 5. Figure B is a rectangle 4 by 6.', '["The areas are equal.", "Figure B has the greater area.", "Figure A has the greater area.", "The area of A is twice the area of B."]'::JSONB, 1, 1, 'A: (1/2) × 8 × 5 = 20. B: 4 × 6 = 24. So B is larger.'),
  ('Examine the figures described and find the best answer. Figure A is a rectangle 6 by 2. Figure B is a triangle with base 6 and height 4.', '["Figure A has the greater area.", "Figure B has the greater area.", "The area of B is twice the area of A.", "The areas are equal."]'::JSONB, 3, 1, 'A: 6 × 2 = 12. B: (1/2) × 6 × 4 = 12. A triangle covers half of the rectangle that shares its base and height.'),
  ('Examine the figures described and find the best answer. Figure A is a right triangle with legs 6 and 8. Figure B is a rectangle 5 by 7.', '["Figure A has the greater perimeter and the greater area.", "Figure B has the greater perimeter.", "The perimeters are equal, but B has the greater area.", "The areas are equal."]'::JSONB, 2, 2, 'The triangle is a 6-8-10 right triangle, so its perimeter is 24 and its area is (1/2)(6)(8) = 24. The rectangle''s perimeter is 2(5+7) = 24 and its area is 35.'),
  ('Examine the figures described and find the best answer. Figure A is a circle with radius 10. Figure B is a rectangle 20 by 15. Use pi = 3.14.', '["Figure A has the greater area.", "Figure B has the greater area.", "The areas are equal.", "The area of B is twice the area of A."]'::JSONB, 0, 2, 'A: 3.14 × 10 × 10 = 314. B: 20 × 15 = 300. The circle is larger.'),
  ('Examine the figures described and find the best answer. Figure A is a rectangular box 3 by 3 by 6. Figure B is a cube with edge 4.', '["Figure A has the greater volume and the greater surface area.", "The volumes are equal.", "Figure A has the greater surface area.", "Figure B has the greater volume and the greater surface area."]'::JSONB, 3, 2, 'Volumes: 3 × 3 × 6 = 54 and 4 × 4 × 4 = 64. Surface areas: 2(9 + 18 + 18) = 90 and 6 × 16 = 96. The cube wins on both counts.'),
  ('Examine the figures described and find the best answer. A rectangle 12 by 8 has a rectangle 4 by 3 cut away from one corner; the part that remains is shaded. Figure B is a square with side 9.', '["Figure B is greater than the shaded part of A.", "The shaded part of A is greater than B.", "The shaded part of A equals B.", "The shaded part of A is twice B."]'::JSONB, 1, 3, 'Shaded area = 96 - 12 = 84. Square B = 9 × 9 = 81. The shaded part is larger, by 3.'),
  ('Examine the figures described and find the best answer. Figure A is a triangle with sides 13, 13 and 10, with a height of 12 drawn to the side of length 10. Figure B is a rectangle 6 by 12.', '["The perimeters are equal, but B has the greater area.", "Figure A has the greater perimeter.", "The perimeters are equal, but A has the greater area.", "The areas are equal."]'::JSONB, 0, 3, 'A: perimeter 13 + 13 + 10 = 36, area (1/2)(10)(12) = 60. B: perimeter 2(6+12) = 36, area 72. Same perimeter, but the rectangle encloses more.'),
  ('Examine the figures described and find the best answer. Figure A is a square whose area is 64. Figure B is a square whose perimeter is 40.', '["Figure A has the greater perimeter and the greater area.", "The areas are equal.", "Figure B has the greater area and the greater perimeter.", "The area of B is twice the area of A."]'::JSONB, 2, 3, 'A has side 8, so its perimeter is 32. B has side 40/4 = 10, so its area is 100. B is bigger both ways, and 100 is not twice 64.'),
  ('Examine the figures described and find the best answer. Figure A is a trapezoid with parallel sides 5 and 11 and height 6. Figure B is a triangle with base 12 and height 8.', '["Figure A has the greater area.", "The areas are equal.", "Figure B has the greater area.", "The area of B is twice the area of A."]'::JSONB, 1, 3, 'Trapezoid: (1/2)(5 + 11)(6) = 48. Triangle: (1/2)(12)(8) = 48. They match.'),
  ('Examine the figures described and find the best answer. A square with side 12 has a circle of diameter 12 removed from it; the four corner pieces that remain are shaded. Use pi = 3.14.', '["The shaded area is between 20 and 25.", "The shaded area is between 35 and 40.", "The shaded area is more than half the square.", "The shaded area is between 30 and 32."]'::JSONB, 3, 3, 'Square = 144. The circle has radius 6, so its area is 3.14 × 36 = 113.04. Shaded = 144 - 113.04 = 30.96.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 3 × 4   (b) 2 × 7   (c) 24 divided by 2', '["(b) is the greatest, and (a) equals (c).", "(a), (b), and (c) are all equal.", "(a) is the greatest, and (b) equals (c).", "(c) is less than (a), and (b) is the smallest."]'::JSONB, 0, 1, '(a) = 12, (b) = 14, (c) = 12. So (b) is largest and (a) ties with (c).'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 1/3   (b) 0.3   (c) 30%', '["All three are equal.", "(b) is greater than (a), and (c) is the smallest.", "(a) is the greatest, and (b) equals (c).", "(c) is the greatest."]'::JSONB, 2, 1, '(b) and (c) are both 0.30, but 1/3 = 0.333..., which is slightly more.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 10 - 4   (b) 10 divided by 2   (c) 3 × 2', '["All three are equal.", "(a) equals (c), and both are greater than (b).", "(a) equals (b), and both are greater than (c).", "(a) is greater than (c)."]'::JSONB, 1, 1, '(a) = 6, (b) = 5, (c) = 6. So (a) and (c) tie at 6, and both beat 5.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 5% of 200   (b) 10% of 100   (c) 20% of 60', '["All three are equal.", "(a) is greater than (b).", "(b) is greater than (c).", "(c) is the greatest."]'::JSONB, 3, 1, '(a) = 10, (b) = 10, (c) = 12. So (c) is the greatest.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 2/5   (b) 0.45   (c) 3/8', '["(b) is greater than (a), and (a) is greater than (c).", "(a) is the greatest.", "(c) is greater than (a), and (a) is greater than (b).", "(a) equals (b)."]'::JSONB, 0, 2, 'As decimals: 2/5 = 0.400, (b) = 0.450, 3/8 = 0.375. So (b) > (a) > (c).'),
  ('Examine (a), (b), and (c) and find the best answer. (a) the average of 6 and 14   (b) the average of 8, 10, and 12   (c) the average of 2, 8, 10, and 16', '["All three are equal.", "(c) is the smallest, and (a) equals (b).", "(a) is greater than (b), and (c) is the smallest.", "(c) is the greatest."]'::JSONB, 1, 2, '(a) = 20/2 = 10, (b) = 30/3 = 10, (c) = 36/4 = 9.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 2/3 of 1/2   (b) 1/2 of 2/3   (c) 3/4 of 1/2', '["All three are equal.", "(a) is the greatest.", "(a) equals (c), and (b) is greater than both.", "(a) equals (b), and (c) is greater than both."]'::JSONB, 3, 2, '(a) and (b) are both 1/3, since the order of multiplication does not matter. (c) = 3/8, and 3/8 is greater than 1/3.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 1/2 + 1/4 + 1/8   (b) 1 - 1/8   (c) 0.9', '["(c) is the greatest, and (a) equals (b).", "All three are equal.", "(a) is greater than (c), and (b) equals (c).", "(b) is the greatest."]'::JSONB, 0, 3, '(a) = 7/8 and (b) = 7/8, both equal to 0.875. (c) = 0.900, which is larger.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 3/7   (b) 5/11   (c) 4/9', '["(a) is the greatest and (c) is the smallest.", "(c) is greater than (b).", "(b) is the greatest and (a) is the smallest.", "(a) equals (c)."]'::JSONB, 2, 3, 'Cross-multiply in pairs: 3/7 against 4/9 gives 27 against 28, so 4/9 is bigger; 4/9 against 5/11 gives 44 against 45, so 5/11 is bigger. Order: (b) > (c) > (a).'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 25% of 64   (b) 64 decreased by 75%   (c) 64 divided by 4', '["(b) is smaller than (a), and (a) equals (c).", "(a), (b), and (c) are all equal.", "(a) is greater than (c).", "(c) is the greatest."]'::JSONB, 1, 3, 'Taking 25%, taking away 75% (which leaves 25%), and dividing by 4 are three ways to do the same thing. Each gives 16.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) the number of 1/4s in 5   (b) 5 + 4   (c) 5 divided by 1/4', '["All three are equal.", "(a) equals (b), and both are greater than (c).", "(c) is the smallest.", "(a) equals (c), and both are greater than (b)."]'::JSONB, 3, 3, 'Asking how many 1/4s fit into 5 is the same as dividing 5 by 1/4, so (a) = (c) = 20, while (b) = 9.'),
  ('Examine (a), (b), and (c) and find the best answer. (a) 3 cubed minus 2 cubed   (b) 2 × 3 squared   (c) 4 squared plus 3', '["All three are equal.", "(b) is the greatest.", "(b) is the smallest, and (a) equals (c).", "(a) is greater than (c), and (b) is the smallest."]'::JSONB, 2, 3, '(a) = 27 - 8 = 19, (b) = 2 × 9 = 18, (c) = 16 + 3 = 19.'),
  ('What number is 5 more than 1/4 of 40?', '["15", "10", "14", "20"]'::JSONB, 0, 1, 'One fourth of 40 is 10, and 10 + 5 = 15.'),
  ('What number is 3 less than half of 22?', '["7", "11", "8", "14"]'::JSONB, 2, 1, 'Half of 22 is 11, and 11 - 3 = 8.'),
  ('What number is twice the sum of 7 and 8?', '["15", "30", "22", "56"]'::JSONB, 1, 1, 'The sum of 7 and 8 is 15, and twice 15 is 30.'),
  ('One third of what number is 15?', '["5", "18", "48", "45"]'::JSONB, 3, 1, 'If one third of the number is 15, then the whole number is 3 × 15 = 45.'),
  ('What number is 10% of 1/2 of 400?', '["4", "20", "40", "200"]'::JSONB, 1, 2, 'Half of 400 is 200, and 10% of 200 is 20.'),
  ('What number is 7 more than the product of 4 and 6?', '["17", "28", "34", "31"]'::JSONB, 3, 2, 'The product of 4 and 6 is 24, and 24 + 7 = 31.'),
  ('60% of what number is 3 times 9?', '["45", "16", "27", "54"]'::JSONB, 0, 2, 'Three times 9 is 27. If 60% of a number is 27, the number is 27 divided by 0.6, which is 45.'),
  ('What number is 4 less than 3/4 of the difference between 100 and 20?', '["60", "71", "56", "76"]'::JSONB, 2, 3, 'The difference is 100 - 20 = 80. Three fourths of 80 is 60, and 60 - 4 = 56.'),
  ('Two thirds of what number is 5 more than 1/2 of 30?', '["20", "25", "45", "30"]'::JSONB, 3, 3, 'Half of 30 is 15, and 15 + 5 = 20. If two thirds of a number is 20, the number is 20 × 3/2 = 30.'),
  ('What number is 1/6 of the sum of 4 squared and 2 cubed?', '["3", "4", "5", "6"]'::JSONB, 1, 3, '4 squared is 16 and 2 cubed is 8, so the sum is 24. One sixth of 24 is 4.'),
  ('What number is 12 more than 40% of 150?', '["54", "60", "72", "78"]'::JSONB, 2, 3, '40% of 150 is 60, and 60 + 12 = 72.'),
  ('Three times a number, decreased by 8, equals half of 44. What is the number?', '["10", "6", "12", "14"]'::JSONB, 0, 3, 'Half of 44 is 22, so three times the number is 22 + 8 = 30, which makes the number 10.'),
  ('What number is 1/3 of 1/4 of 20% of 300?', '["4", "5", "15", "20"]'::JSONB, 1, 3, '20% of 300 is 60; one fourth of 60 is 15; one third of 15 is 5.')
)
INSERT INTO questions (id, section, passage, prompt, options, correct_index, difficulty, explanation)
SELECT md5('quantitative' || '|' || q.prompt)::UUID, 'quantitative'::section_type, NULL,
       q.prompt, q.options, q.correct_index, q.difficulty, q.explanation
FROM q
ON CONFLICT (id) DO NOTHING;

-- ── Verification: expect 50 rows ─────────────────────────────────────
SELECT '036 quantitative' AS migration, COUNT(*)::TEXT AS present, '50' AS expected
FROM questions
WHERE id IN (
  md5('quantitative' || '|' || 'Look at this series: 6, 13, 20, 27, 34, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 90, 81, 72, 63, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 2, 20, 200, 2000, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 11, 15, 19, 23, 27, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 72, 66, 60, 54, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 7, 14, 28, 56, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 4, 7, 6, 9, 8, 11, 10, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 2, 4, 8, 14, 22, 32, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 5, 10, 20, 35, 55, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 3, 6, 18, 72, 360, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 2, 4, 10, 28, 82, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 5, 7, 11, 19, 35, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Look at this series: 2, 9, 4, 18, 6, 27, 8, ... What number should come next?')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a rectangle 7 by 4. Figure B is a square with side 5.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a square with side 10. Figure B is a rectangle 20 by 5.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a triangle with base 8 and height 5. Figure B is a rectangle 4 by 6.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a rectangle 6 by 2. Figure B is a triangle with base 6 and height 4.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a right triangle with legs 6 and 8. Figure B is a rectangle 5 by 7.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a circle with radius 10. Figure B is a rectangle 20 by 15. Use pi = 3.14.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a rectangular box 3 by 3 by 6. Figure B is a cube with edge 4.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. A rectangle 12 by 8 has a rectangle 4 by 3 cut away from one corner; the part that remains is shaded. Figure B is a square with side 9.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a triangle with sides 13, 13 and 10, with a height of 12 drawn to the side of length 10. Figure B is a rectangle 6 by 12.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a square whose area is 64. Figure B is a square whose perimeter is 40.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. Figure A is a trapezoid with parallel sides 5 and 11 and height 6. Figure B is a triangle with base 12 and height 8.')::UUID,
  md5('quantitative' || '|' || 'Examine the figures described and find the best answer. A square with side 12 has a circle of diameter 12 removed from it; the four corner pieces that remain are shaded. Use pi = 3.14.')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 3 × 4   (b) 2 × 7   (c) 24 divided by 2')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 1/3   (b) 0.3   (c) 30%')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 10 - 4   (b) 10 divided by 2   (c) 3 × 2')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 5% of 200   (b) 10% of 100   (c) 20% of 60')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 2/5   (b) 0.45   (c) 3/8')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) the average of 6 and 14   (b) the average of 8, 10, and 12   (c) the average of 2, 8, 10, and 16')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 2/3 of 1/2   (b) 1/2 of 2/3   (c) 3/4 of 1/2')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 1/2 + 1/4 + 1/8   (b) 1 - 1/8   (c) 0.9')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 3/7   (b) 5/11   (c) 4/9')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 25% of 64   (b) 64 decreased by 75%   (c) 64 divided by 4')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) the number of 1/4s in 5   (b) 5 + 4   (c) 5 divided by 1/4')::UUID,
  md5('quantitative' || '|' || 'Examine (a), (b), and (c) and find the best answer. (a) 3 cubed minus 2 cubed   (b) 2 × 3 squared   (c) 4 squared plus 3')::UUID,
  md5('quantitative' || '|' || 'What number is 5 more than 1/4 of 40?')::UUID,
  md5('quantitative' || '|' || 'What number is 3 less than half of 22?')::UUID,
  md5('quantitative' || '|' || 'What number is twice the sum of 7 and 8?')::UUID,
  md5('quantitative' || '|' || 'One third of what number is 15?')::UUID,
  md5('quantitative' || '|' || 'What number is 10% of 1/2 of 400?')::UUID,
  md5('quantitative' || '|' || 'What number is 7 more than the product of 4 and 6?')::UUID,
  md5('quantitative' || '|' || '60% of what number is 3 times 9?')::UUID,
  md5('quantitative' || '|' || 'What number is 4 less than 3/4 of the difference between 100 and 20?')::UUID,
  md5('quantitative' || '|' || 'Two thirds of what number is 5 more than 1/2 of 30?')::UUID,
  md5('quantitative' || '|' || 'What number is 1/6 of the sum of 4 squared and 2 cubed?')::UUID,
  md5('quantitative' || '|' || 'What number is 12 more than 40% of 150?')::UUID,
  md5('quantitative' || '|' || 'Three times a number, decreased by 8, equals half of 44. What is the number?')::UUID,
  md5('quantitative' || '|' || 'What number is 1/3 of 1/4 of 20% of 300?')::UUID
);
