-- 037 — Add 50 math questions
--
-- Pure insert, no passage. Ids are deterministic:
-- md5(section || '|' || prompt)::UUID with ON CONFLICT DO NOTHING, so
-- re-running this file is a no-op. Nothing existing is deleted or updated,
-- and user_question_history is never touched.

WITH q(prompt, options, correct_index, difficulty, explanation) AS (VALUES
  ('What is 9 × 12?', '["96", "108", "99", "117"]'::JSONB, 1, 1, '9 × 12 = 9 × 10 + 9 × 2 = 90 + 18 = 108.'),
  ('What is 7² − 3²?', '["16", "49", "40", "58"]'::JSONB, 2, 1, '7² = 49 and 3² = 9, so 49 − 9 = 40. Squaring the difference gives 16, which is not the same.'),
  ('Round 4,682 to the nearest hundred.', '["4,600", "4,700", "4,680", "5,000"]'::JSONB, 1, 1, 'The tens digit is 8, which is 5 or more, so the hundreds digit rounds up from 6 to 7.'),
  ('What is 0.4 × 0.2?', '["0.6", "0.8", "0.08", "8"]'::JSONB, 2, 1, '4 × 2 = 8, and the two factors have one decimal place each, so the product has two.'),
  ('Which of these numbers is prime?', '["29", "21", "27", "33"]'::JSONB, 0, 1, '29 has no factors besides 1 and itself; 21 = 3 × 7, 27 = 3 × 9, and 33 = 3 × 11.'),
  ('What is 3/5 expressed as a percent?', '["30%", "35%", "53%", "60%"]'::JSONB, 3, 1, '3 ÷ 5 = 0.6, and 0.6 × 100 gives 60%.'),
  ('What is the value of 4a + 3 when a = 6?', '["27", "13", "24", "42"]'::JSONB, 0, 1, 'Substitute, then multiply before adding: 4(6) + 3 = 24 + 3 = 27.'),
  ('What is −7 + 12?', '["−19", "5", "−5", "19"]'::JSONB, 1, 1, 'Starting at −7 and moving 12 units to the right on the number line lands on 5.'),
  ('What is 6 − (−4)?', '["−10", "−2", "10", "2"]'::JSONB, 2, 1, 'Subtracting a negative is the same as adding the positive: 6 + 4 = 10.'),
  ('What is 1/3 of 21?', '["3", "18", "7", "63"]'::JSONB, 2, 1, '''Of'' means multiply: (1/3) × 21 = 21 ÷ 3 = 7.'),
  ('What is the perimeter of a rectangle with length 15 cm and width 9 cm?', '["24 cm", "60 cm", "135 cm", "48 cm"]'::JSONB, 3, 1, 'Perimeter = 2(15) + 2(9) = 30 + 18 = 48 cm. Adding each side only once gives 24, and 135 is the area.'),
  ('What is the area of a square with side length 7?', '["14", "28", "42", "49"]'::JSONB, 3, 1, 'Area of a square is side × side = 7 × 7 = 49; 28 would be the perimeter.'),
  ('How many minutes are in 3.5 hours?', '["195", "300", "210", "350"]'::JSONB, 2, 1, '3.5 × 60 = 180 + 30 = 210 minutes.'),
  ('What is 25% of 60?', '["15", "12", "20", "24"]'::JSONB, 0, 1, '25% is the same as 1/4, and 60 ÷ 4 = 15.'),
  ('Find the median of: 8, 3, 12, 5, 10.', '["8", "5", "7.6", "12"]'::JSONB, 0, 1, 'In order the values are 3, 5, 8, 10, 12, so the middle value is 8. The mean, 7.6, is a different measure.'),
  ('What is 7/8 expressed as a decimal?', '["0.78", "0.87", "1.142", "0.875"]'::JSONB, 3, 1, '7 ÷ 8 = 0.875 exactly, so it does not stop at 0.87.'),
  ('What is the value of 3 × (8 − 5)²?', '["9", "27", "54", "81"]'::JSONB, 1, 1, 'Parentheses first (8 − 5 = 3), then the exponent (3² = 9), then multiply: 3 × 9 = 27.'),
  ('Which fraction is equivalent to 3/4?', '["9/12", "4/3", "6/9", "12/15"]'::JSONB, 0, 1, 'Multiplying 3/4 by 3/3 gives 9/12. The others reduce to 4/3, 2/3, and 4/5.'),
  ('What is 10² ÷ 5?', '["4", "20", "50", "100"]'::JSONB, 1, 1, 'The exponent comes first: 10² = 100, then 100 ÷ 5 = 20. Dividing before squaring would wrongly give 4.'),
  ('Which of these values is the greatest: 2/3, 0.6, 5/8, or 0.58?', '["0.6", "5/8", "0.58", "2/3"]'::JSONB, 3, 1, 'As decimals they are about 0.667, 0.600, 0.625, and 0.580, so 2/3 is the largest.'),
  ('What is the sum of the interior angles of a quadrilateral?', '["180°", "270°", "540°", "360°"]'::JSONB, 3, 1, 'A quadrilateral splits into two triangles and each triangle holds 180°, so the sum is 2 × 180 = 360°.'),
  ('How many inches are in 4 feet?', '["36", "48", "40", "52"]'::JSONB, 1, 1, 'One foot is 12 inches, so 4 × 12 = 48 inches.'),
  ('What is 1/4 + 1/3?', '["1/7", "2/7", "5/12", "7/12"]'::JSONB, 3, 1, 'Rewrite with the common denominator 12: 3/12 + 4/12 = 7/12. Adding tops and bottoms separately gives 2/7, which is wrong.'),
  ('A recipe uses 3 eggs to make 12 pancakes. At the same rate, how many eggs are needed for 20 pancakes?', '["5", "4", "6", "8"]'::JSONB, 0, 2, 'Three eggs per 12 pancakes is 4 pancakes per egg, so 20 ÷ 4 = 5 eggs.'),
  ('Solve for x: (x − 3)/2 = 6', '["9", "12", "18", "15"]'::JSONB, 3, 2, 'Multiply both sides by 2 to get x − 3 = 12, then add 3 to get x = 15. Adding 3 first gives 9, a common slip.'),
  ('What is 2/5 ÷ 3/10?', '["3/25", "4/3", "3/4", "12/25"]'::JSONB, 1, 2, 'Dividing means multiplying by the reciprocal: (2/5) × (10/3) = 20/15 = 4/3. Multiplying instead gives 3/25.'),
  ('On a map, 1 inch represents 25 miles. Two cities are 3.5 inches apart on the map. How far apart are they?', '["70 miles", "75 miles", "87.5 miles", "105 miles"]'::JSONB, 2, 2, 'Multiply the map distance by the scale: 3.5 × 25 = 87.5 miles.'),
  ('After a 25% discount, a jacket costs $60. What was the original price?', '["$80", "$45", "$75", "$85"]'::JSONB, 0, 2, 'The sale price is 75% of the original, so the original is 60 ÷ 0.75 = $80. Adding 25% to $60 gives $75, which is too small.'),
  ('What is the slope of the line passing through (2, 3) and (6, 11)?', '["1/2", "4", "8", "2"]'::JSONB, 3, 2, 'Slope is the change in y over the change in x: (11 − 3)/(6 − 2) = 8/4 = 2. Flipping the fraction gives 1/2.'),
  ('The area of a circle is 49π square units. What is its circumference, in terms of π?', '["7π", "14π", "24.5π", "98π"]'::JSONB, 1, 2, 'πr² = 49π gives r = 7, so the circumference is 2πr = 14π. Using 7π forgets to double the radius.'),
  ('A rhombus has diagonals of length 6 and 8. What is its area?', '["14", "28", "24", "48"]'::JSONB, 2, 2, 'The area of a rhombus is half the product of the diagonals: (6 × 8)/2 = 24. Forgetting to halve gives 48.'),
  ('What is the value of (2/3)²?', '["2/9", "4/9", "4/3", "8/27"]'::JSONB, 1, 2, 'Squaring a fraction squares both parts: (2 × 2)/(3 × 3) = 4/9. Squaring only one part gives 2/9 or 4/3.'),
  ('What is 15% of 240?', '["16", "24", "40", "36"]'::JSONB, 3, 2, '10% of 240 is 24 and 5% is half of that, 12, so 15% is 24 + 12 = 36.'),
  ('Three-fifths of a number is 24. What is the number?', '["14.4", "30", "40", "48"]'::JSONB, 2, 2, 'Divide rather than multiply: 24 ÷ (3/5) = 24 × 5/3 = 40. Multiplying by 3/5 instead gives 14.4.'),
  ('A box contains 5 red, 3 blue, and 4 green marbles. One is drawn at random. What is the probability that it is NOT blue?', '["1/4", "1/3", "3/4", "2/3"]'::JSONB, 2, 2, 'There are 12 marbles and 9 of them are not blue, so the probability is 9/12 = 3/4. The value 1/4 is the chance it IS blue.'),
  ('In the proportion 3/8 = x/40, what is x?', '["15", "5", "12", "24"]'::JSONB, 0, 2, 'Since 40 is 8 × 5, the numerator must also be multiplied by 5: x = 3 × 5 = 15.'),
  ('When a number is increased by 12, the result is three times the number. What is the number?', '["6", "3", "4", "9"]'::JSONB, 0, 2, 'The equation n + 12 = 3n gives 12 = 2n, so n = 6.'),
  ('The average of four numbers is 15. Three of the numbers are 12, 18, and 20. What is the fourth number?', '["8", "10", "13", "25"]'::JSONB, 1, 2, 'The four numbers total 4 × 15 = 60, and 12 + 18 + 20 = 50, so the missing number is 60 − 50 = 10.'),
  ('How many 3-inch pieces can be cut from a ribbon that is 4 feet long?', '["12", "14", "16", "48"]'::JSONB, 2, 2, 'Four feet is 48 inches, and 48 ÷ 3 = 16 pieces. Skipping the unit conversion gives 48.'),
  ('Two vertical angles measure 3x degrees and 75 degrees. What is the value of x?', '["15", "35", "45", "25"]'::JSONB, 3, 2, 'Vertical angles are equal, so 3x = 75 and x = 25. They are not supplementary.'),
  ('If x + 1/x = 5, what is the value of x² + 1/x²?', '["10", "25", "23", "27"]'::JSONB, 2, 3, 'Squaring both sides gives x² + 2 + 1/x² = 25, so x² + 1/x² = 25 − 2 = 23.'),
  ('What is the units digit of 7 raised to the 25th power?', '["1", "7", "3", "9"]'::JSONB, 1, 3, 'The units digits of powers of 7 repeat 7, 9, 3, 1 every four powers, and 25 leaves remainder 1 when divided by 4.'),
  ('A 6-liter mixture is 1/3 alcohol. How many liters of water must be added so that the mixture is 1/4 alcohol?', '["2", "1", "1.5", "3"]'::JSONB, 0, 3, 'The 2 liters of alcohol stay fixed, so 2/(6 + w) = 1/4 gives 6 + w = 8 and w = 2 liters.'),
  ('What are the solutions of x² − 5x − 14 = 0?', '["x = −7 and x = 2", "x = 2 and x = 7", "x = −2 and x = 7", "x = −7 and x = −2"]'::JSONB, 2, 3, 'Factor as (x − 7)(x + 2) = 0; the factors must multiply to −14 and add to −5, giving x = 7 or x = −2.'),
  ('The length of a rectangle is increased by 20% and its width is decreased by 20%. What happens to the area?', '["It decreases by 4%", "It stays the same", "It increases by 4%", "It decreases by 20%"]'::JSONB, 0, 3, 'The new area is 1.2 × 0.8 = 0.96 of the original, a 4% decrease, because the percents apply to different amounts.'),
  ('The interior angles of a regular polygon sum to 1080°. How many sides does the polygon have?', '["8", "6", "7", "10"]'::JSONB, 0, 3, 'The angle sum is (n − 2) × 180°, so n − 2 = 1080/180 = 6 and n = 8.'),
  ('What is the measure of the smaller angle formed by the hands of a clock at 3:30?', '["15°", "90°", "105°", "75°"]'::JSONB, 3, 3, 'At 3:30 the minute hand points at 180° and the hour hand has drifted halfway past 3, to 105°, leaving a 75° gap.'),
  ('Ann can finish a job alone in 12 days and Ben can finish the same job alone in 18 days. They work together for 4 days, then Ann leaves. How many more days does Ben need?', '["6", "8", "7", "9"]'::JSONB, 1, 3, 'Together they complete 1/12 + 1/18 = 5/36 per day, so 4 days finishes 20/36. Ben does the remaining 4/9 at 1/18 per day, taking 8 days.'),
  ('A square garden has an area of 144 square feet. A path 2 feet wide surrounds the garden on all sides. What is the area of the path alone?', '["112 square feet", "56 square feet", "96 square feet", "256 square feet"]'::JSONB, 0, 3, 'The garden is 12 by 12, and 2 feet on each side makes the outer square 16 by 16 = 256, so the path is 256 − 144 = 112 square feet.'),
  ('In a class, 18 students play soccer, 15 play basketball, 7 play both sports, and 5 play neither. How many students are in the class?', '["26", "31", "33", "38"]'::JSONB, 1, 3, 'Those playing at least one sport number 18 + 15 − 7 = 26, and adding the 5 who play neither gives 31.')
)
INSERT INTO questions (id, section, passage, prompt, options, correct_index, difficulty, explanation)
SELECT md5('math' || '|' || q.prompt)::UUID, 'math'::section_type, NULL,
       q.prompt, q.options, q.correct_index, q.difficulty, q.explanation
FROM q
ON CONFLICT (id) DO NOTHING;

-- ── Verification: expect 50 rows ─────────────────────────────────────
SELECT '037 math' AS migration, COUNT(*)::TEXT AS present, '50' AS expected
FROM questions
WHERE id IN (
  md5('math' || '|' || 'What is 9 × 12?')::UUID,
  md5('math' || '|' || 'What is 7² − 3²?')::UUID,
  md5('math' || '|' || 'Round 4,682 to the nearest hundred.')::UUID,
  md5('math' || '|' || 'What is 0.4 × 0.2?')::UUID,
  md5('math' || '|' || 'Which of these numbers is prime?')::UUID,
  md5('math' || '|' || 'What is 3/5 expressed as a percent?')::UUID,
  md5('math' || '|' || 'What is the value of 4a + 3 when a = 6?')::UUID,
  md5('math' || '|' || 'What is −7 + 12?')::UUID,
  md5('math' || '|' || 'What is 6 − (−4)?')::UUID,
  md5('math' || '|' || 'What is 1/3 of 21?')::UUID,
  md5('math' || '|' || 'What is the perimeter of a rectangle with length 15 cm and width 9 cm?')::UUID,
  md5('math' || '|' || 'What is the area of a square with side length 7?')::UUID,
  md5('math' || '|' || 'How many minutes are in 3.5 hours?')::UUID,
  md5('math' || '|' || 'What is 25% of 60?')::UUID,
  md5('math' || '|' || 'Find the median of: 8, 3, 12, 5, 10.')::UUID,
  md5('math' || '|' || 'What is 7/8 expressed as a decimal?')::UUID,
  md5('math' || '|' || 'What is the value of 3 × (8 − 5)²?')::UUID,
  md5('math' || '|' || 'Which fraction is equivalent to 3/4?')::UUID,
  md5('math' || '|' || 'What is 10² ÷ 5?')::UUID,
  md5('math' || '|' || 'Which of these values is the greatest: 2/3, 0.6, 5/8, or 0.58?')::UUID,
  md5('math' || '|' || 'What is the sum of the interior angles of a quadrilateral?')::UUID,
  md5('math' || '|' || 'How many inches are in 4 feet?')::UUID,
  md5('math' || '|' || 'What is 1/4 + 1/3?')::UUID,
  md5('math' || '|' || 'A recipe uses 3 eggs to make 12 pancakes. At the same rate, how many eggs are needed for 20 pancakes?')::UUID,
  md5('math' || '|' || 'Solve for x: (x − 3)/2 = 6')::UUID,
  md5('math' || '|' || 'What is 2/5 ÷ 3/10?')::UUID,
  md5('math' || '|' || 'On a map, 1 inch represents 25 miles. Two cities are 3.5 inches apart on the map. How far apart are they?')::UUID,
  md5('math' || '|' || 'After a 25% discount, a jacket costs $60. What was the original price?')::UUID,
  md5('math' || '|' || 'What is the slope of the line passing through (2, 3) and (6, 11)?')::UUID,
  md5('math' || '|' || 'The area of a circle is 49π square units. What is its circumference, in terms of π?')::UUID,
  md5('math' || '|' || 'A rhombus has diagonals of length 6 and 8. What is its area?')::UUID,
  md5('math' || '|' || 'What is the value of (2/3)²?')::UUID,
  md5('math' || '|' || 'What is 15% of 240?')::UUID,
  md5('math' || '|' || 'Three-fifths of a number is 24. What is the number?')::UUID,
  md5('math' || '|' || 'A box contains 5 red, 3 blue, and 4 green marbles. One is drawn at random. What is the probability that it is NOT blue?')::UUID,
  md5('math' || '|' || 'In the proportion 3/8 = x/40, what is x?')::UUID,
  md5('math' || '|' || 'When a number is increased by 12, the result is three times the number. What is the number?')::UUID,
  md5('math' || '|' || 'The average of four numbers is 15. Three of the numbers are 12, 18, and 20. What is the fourth number?')::UUID,
  md5('math' || '|' || 'How many 3-inch pieces can be cut from a ribbon that is 4 feet long?')::UUID,
  md5('math' || '|' || 'Two vertical angles measure 3x degrees and 75 degrees. What is the value of x?')::UUID,
  md5('math' || '|' || 'If x + 1/x = 5, what is the value of x² + 1/x²?')::UUID,
  md5('math' || '|' || 'What is the units digit of 7 raised to the 25th power?')::UUID,
  md5('math' || '|' || 'A 6-liter mixture is 1/3 alcohol. How many liters of water must be added so that the mixture is 1/4 alcohol?')::UUID,
  md5('math' || '|' || 'What are the solutions of x² − 5x − 14 = 0?')::UUID,
  md5('math' || '|' || 'The length of a rectangle is increased by 20% and its width is decreased by 20%. What happens to the area?')::UUID,
  md5('math' || '|' || 'The interior angles of a regular polygon sum to 1080°. How many sides does the polygon have?')::UUID,
  md5('math' || '|' || 'What is the measure of the smaller angle formed by the hands of a clock at 3:30?')::UUID,
  md5('math' || '|' || 'Ann can finish a job alone in 12 days and Ben can finish the same job alone in 18 days. They work together for 4 days, then Ann leaves. How many more days does Ben need?')::UUID,
  md5('math' || '|' || 'A square garden has an area of 144 square feet. A path 2 feet wide surrounds the garden on all sides. What is the area of the path alone?')::UUID,
  md5('math' || '|' || 'In a class, 18 students play soccer, 15 play basketball, 7 play both sports, and 5 play neither. How many students are in the class?')::UUID
);
